### ISSUE TITLE
Error thrown when choosing color for fit in demag_gui

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#104]
When choosing one of the provided colors for a fit in the dropdown in the Interpretation Editor, this error is given and the color doesn't change:

<img width="433" alt="screen shot 2017-01-23 at 6 26 32 pm" src="https://cloud.githubusercontent.com/assets/4332322/22231698/e23c83ae-e199-11e6-81c2-656b47d65ac8.png">

**Comment by Caoimhinmg** [comment]
Hey @Swanson-Hysell, so the error message itself is intentional. It is supposed to fire when you try to create a new colour by entering a name:hexcolor_or_rgbtuple into the box then hitting enter, but you put in a invalid hex or name or whatever. I can't figure out why it would pop up when you just select a colour; the event shouldn't even get prompted, and for the life of me I can't recreate this. So perhaps this evening or morning at the forum you can show me how you got to this error?

**Comment by Swanson-Hysell** [comment]
This turns out to be a non-issue. Thanks Kevin.
