### ISSUE TITLE
naming conventions causing problem with CIT conversion

### ISSUE THREAD

**Issue by jmiristock** [PmagPy/PmagPy#108]
I have CIT format files with names such as:
 * 1&2PAP1.2
* JUN--086-A.1

and these do not load using the Pmag GUI on Windows 10
but no error message is received in binary

**Comment by Caoimhinmg** [comment]
Hi @jmiristock I have looked into this issue by taking some of my own CIT formatted data and putting & and -- in the names to create a test dataset which should break the code if these symbols are the problem. So the conundrum is that the code runs fine. With no error I have no way of tracking down what is truly going on with the datasets you had fail. Would it be possible for me to obtain some of the data you have been having trouble with so I can use it to fix this issue? Because I can safely say it is not the strange symbols in the names, but it could be some other naming convention or such that is creating this issue. Thanks.

**Comment by jmiristock** [comment]
Hi

here is a zip file with some of the files that had the problem.

Thanks for looking into this,


Joann

**Comment by jmiristock** [comment]
Hi Kevin

here is a zip file with another set of demagnetization data in CIT 
format that also did not load correctly.

Thanks for your help,

Joann

**Comment by jmiristock** [comment]
[1&2P.zip](https://github.com/PmagPy/PmagPy/files/743423/1.2P.zip)
[JUN--08.zip](https://github.com/PmagPy/PmagPy/files/743424/JUN--08.zip)

**Comment by Caoimhinmg** [comment]
Thanks for your quick response @jmiristock. I'll have a fix out in a few days, probably, and it should then be included in the next release of the GUI's and easily usable then.

Cheers,
Kevin

**Comment by jmiristock** [comment]
Thanks very much.  I did not mean to close this thread.  I am still learning how this all works.

**Comment by Caoimhinmg** [comment]
So the trouble is defiantly in your treatment steps on some of your samples. So broadly speaking there are 4 problems:

1. Some of the LN2 steps are named lN2 or ln2 and it is inconsistent. (I fixed this in the conversion script, by making everything uppercase)
2. There are some AF steps that in the step type field (the first 2 to 3 characters on a line in a sample file) that are too long getting up to 7 characters long which means the treatment types are partly in the treatment step field where the temperature or AF strength should be. I can't do much about this in the script as this is just the CIT convention (outlined here: http://cires1.colorado.edu/people/jones.craig/PMag_Formats.html) and it would probably break the script for other CIT files if I changed it. So it'll have to be fixed in the sample files, which just doesn't sound fun.
3. There are IRM steps which currently there is no conversion check for this in the script. (I should fix this I just need to look quick for the codes and what not when I get time)
4. There are decimal values on the treatment steps. such as 273.7, 288.8, 274.4, 271.6, etc. I have no idea what these mean. I assume these are not the actual temperature values because I've never seen anyone run a temperature step with on a decimal degree. Is it a naming system is it like the decimal IZZI system? (.0 is zero field, .1 is in field, .2 is PTRM, .3 is Tail check, etc.) If so what are the designations, and does it conflict with the above system? If so I'll need to be able to distinguish them to fix this.

Examples of all of the above problems can be seen in the sample file 1&2P2PF.6 if you want to see what I'm talking about. So there isn't much I can do until the sample files treatment steps have been shorted to CIT convention and even then I need to know what the decimal convention is. Though this is mostly about the 1&2 data set there are also problems akin to the second one outlined above in JUN--08. This may not be the easiest data set to convert. So while I fixed problem 1 and can fix problem 3 and possibly could fix problem 4 with some information, there is nothing I can do about problem 2 and I can't convert these files without that fixed first.

Sorry I couldn't be more help,
Kevin

**Comment by jmiristock** [comment]
Hi Kevin

that is really helpful to know.  Probably there are other people's files 
that may have the same issues.  I will have to find out what those codes 
for the treatment steps are, so I will ask around to some of the other 
people who were using the Caltech magnetometers at these times.  Anyway 
at least we know now what we ought to focus on.

(Steve: can you forward this to anybody else who might have similar 
issues?  I don't have Sara's email address and probably not

email addresses of all the other relevant people either.)

Thanks

Joann

**Comment by Caoimhinmg** [comment]
Hi @jmiristock,

So I gave this another try by changing the CIT magic script, I just finished translating and fixing all the conversion scripts anyway. So I managed to change some things that made the conversion run and at least for the JUN--08 dataset I got a reasonable result, the 1&2 data set is still completely wild but it produced an output at least. Some assumptions/changes I had to make to get this to work were:

- Assumed that a treatment type MAF is the same as AF, there are a number of these in JUN--08 and can be easily seen JUN--0806C-A.1
- AFz and AFmax is the same as AF and MAF, there are a lot of these in 1&2
- Finally and I think this is the real weird one, if the treatment step value is not in the spot it should be which would be starting on the 3rd or 4th character of the line then the treatment step is given by the next character after a white space character. Unless there are nothing but white space characters in this area then I assume the treatment step is 0 or NRM, because some lines just have nothing here so if it's marked AF and has no mT value I just have to assume there is no field. This was reconstructed by looking at a lot of steps in 1&2 and JUN--08.
- I added an IRM section to the CIT script

So my thought is that the decimal treatment step thing above was just these steps lacking a treatment step. It's probably also worth mentioning that your .LSQ files don't import so there probably has been some changes to the data (which at least in the case of 1&2 looks pretty crazy). I've attached the output data which can be looked at in Demag GUI.
[1&2P_magic.zip](https://github.com/PmagPy/PmagPy/files/797689/1.2P_magic.zip)
[JUN--08_magic.zip](https://github.com/PmagPy/PmagPy/files/797690/JUN--08_magic.zip)

**Comment by moonshoes87** [comment]
I'm trying to clean up old issues.  Since this hasn't had any activity in many months, I'm going to close it.  @jmiristock, @Caoimhinmg, feel free to reopen this or create a new issue if there are unresolved elements related to this problem.
