### ISSUE TITLE
Git protocols

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#137]
I have a few suggestions for good git protocols, especially as our project may be growing to include more contributors.  

1. Commits should have descriptive names that briefly explain what was done

2. Commit names like “Fixes #100” should have additional context so that they make sense when you aren’t looking at the git log through Github.

3. Commits should deal with one concern at a time — spanning multiple files is fine, but commits with many unrelated changes are confusing and should be broken up.  This makes it easier for someone else to understand what happened, and if something broke in a particular commit it is easier to track it down if the changes are more isolated.  

Anybody have others?  I think it will be helpful for us to try to be more strict on these things :)  I am happy to incorporate these items into CONTRIBUTING.

**Comment by Caoimhinmg** [comment]
I think it's a great idea @moonshoes87. Even though I know I just did a "Fixes #100" commit. :) More smaller commits with related changes would make versioning and reverting when we encounter bugs. I'll do my best to improve my commits.

It might help also if we were to use branches more for features that are so big that they cannot be fully implemented in one commit without that commit being huge and having lots of unrelated changes. Like Thellier GUI marking things bad is definitely too big a change to be one commit, but putting that on master would ruin the live version of the GUIs. So just including in the CONTRIBUTING a bit on using branches or forks if they're not a contributor for large changes that need to be broken into pieces and which might break critical functionality on master otherwise.

**Comment by moonshoes87** [comment]
Yes, I've done my share of cryptic commits too :)  

I agree, using branches for large features is a good addition to the list.

Anything else we should add?

**Comment by Swanson-Hysell** [comment]
These protocols sound good to me.

**Comment by ltauxe** [comment]
I agree.  I will try to be better.  first off, i will try to wean myself off emails and onto the git issues :)

**Comment by Caoimhinmg** [comment]
I don't have anything to add to the protocols they look like good to me. Also thought I'd share one of my favourite features of the Github website, which, being built for developers has a bunch of hotkeys for functionality which really make it easy to get into the habit of living on the github issues and code pages here's their spreadsheet of these: https://help.github.com/articles/using-keyboard-shortcuts/
I personally have really found these useful especially if your internet is not always lightening fast as it minimizes things reloaded by not reloading the header or anything else consistent between pages.
