### ISSUE TITLE
Proposed. What file format would you like exported from LIMS?

### ISSUE THREAD

**Issue by dmafackler** [PmagPy/PmagPy#147]
For SRM,, JR6a, KLY4s?

Proposing not a report, but a web service that emits either the exact plain/text you require, or application/json to parse. Whether I hear from you or not, going to give it a whirl for SRM at least based on the output  of iodp_srm_magic.py

- Much better plan than continued maintenance of scripts following ever changing reports.
- Should reduce the amount of file management required by any given operator, at least w/respect to JRSO content.
- Long term greater stability of interface with potential for more direct ingestion into MagIC database.

jr_fackler@ship.iodp.tamu.edu

**Comment by Caoimhinmg** [comment]
Hi @dmafackler, so the place to look is https://www2.earthref.org/MagIC/data-models/3.0 to see the data model with descriptions (the required tables for analysis are Locations, Sites, Samples, Specimens, Measurements). The tables themselves are just tab separated value files with short headers and you can see what they look like from the output of the iodp_srm_magic script. 

The iodp_srm_magic script to look at if you want to see the current code is in the PmagPy/PmagPy repo under programs/conversion_scripts/iodp_srm_magic.py. There are 2 iodp_srm_magic scripts because we are currently in process of converting the scripts to our 3.0 data model.

I think it would be great if there could be a output MagIC tables option on the iodp site. Let me know if you have any questions or would like to converse. (caoimhin@berkeley.edu)

**Comment by njarboe** [comment]
Hello David Fackley @dmafackler,
My name is Nick Jarboe (njarboe@ucsd.edu). I work at Scripps for the MagIC group on getting data into the MagIC database. It would be great, as you stated, to have a system on your end that exported data into the MagIC 3.0 format. Then we do not have to keep up with the changing file formats on your end. Have you made any progress on this system? We would like to start ingesting the LIMS data as soon as possible. Is there anything I can do to help? Maybe we could meet with Skype or Zoom with Katerina to discuss the best way forward.

**Comment by moonshoes87** [comment]
@njarboe, should I keep this issue open?  I am trying to clean house and I kind of assume this has either happened or isn't going to.

**Comment by njarboe** [comment]
Doug Fils is working with IODP data now and we should be able to work with his software to get the IODP data imported. I'll close this issue.
