### ISSUE TITLE
thellier_gui phantom message window

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#149]
after completing thellier auto interpreter,  the box that says "Running Thellier auto interpreter
It may take several minutes depending...."  stays open well after the auto interpreter has finished.  This is a new bug....

**Comment by moonshoes87** [comment]
I've been able to get Thellier GUI to auto interpreter to run through this problem, but I'm not sure that the problem is actually solved.

Some of the relevant code, in dialogs.thellier_interpreter.run_interpreter:
                pars=thellier_gui_lib.get_PI_parameters(self.Data,self.acceptance_criteria,self.preferences,s,tmin,tmax,self.GUI_log,THERMAL,MICROWAVE)
                ...
                pars=thellier_gui_lib.check_specimen_PI_criteria(pars,self.acceptance_criteria)
                ...
                B_anc=pars['specimen_int_uT']
                ....
                if sample not in Grade_A_samples.keys():
                    Grade_A_samples[sample]={}
                if s not in Grade_A_samples[sample].keys() and len(All_grade_A_Recs[s])>0:
                    Grade_A_samples[sample][s]=[]

                if pd.notnull(B_anc):  # I added this line to skip null values, which makes the interpreter run successfully to completion
                    Grade_A_samples[sample][s].append(B_anc)

For some specimens, B_anc is null (grabbed from pars['specimen_int_uT']).  Those null values, in Grade_A_samples (which later becomes Grade_A_sorted), were causing the auto interpreter to hang.  

I'm not terribly familiar with this code.  @ltauxe, @ronshaar, let me know what you think.  I can dig some more but I'd like some input first.  I've pushed my two line fix (see above).
