### ISSUE TITLE
Demag GUI main function

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#152]
This commit breaks running Demag GUI for the pip install: 8b9229c

When Demag GUI is running from pip, __name__ will not be "__main__".  Getting arguments from sys.argv needs to be in the "main" function.  You can see how it is done in Pmag GUI, which is compatible with both pip and developer installs.  

In my commit 374b6b0 I was trying to leave the structure as you had it with your 'main' function in , but I think it would really be better to change it to the style of Pmag/Magic GUIs.

**Comment by moonshoes87** [comment]
This same issue will also break the pip installation in combine_magic:  8f808af

**Comment by Caoimhinmg** [comment]
This is strange. So running directly from the command line if it is pip installed doesn't name the top level script __ main __? This defeats the whole purpose of the __ name __==" __ main __ " check.

Putting the sys.argv into the main function is a bit of a hack though because it can result in some serious side effects as it basically overwrites the input variables for the main function from a mutable global list variable (sys.argv). 

So there is the scenario where you call Demag GUI and because we have the same flags I overwrite the WD input variable with the -WD flag because it is in sys.argv so demag GUI opens in the original directory not the one Pmag GUI is in now. Or even worse if we use the same flag for different variables we run the risk of name space collisions, and as most command line flags are one character this is a real chance as there are only 26 uniques. That is why python generally uses the __ name __==" __ main __ " solution, this is particularly evident in the conversion scripts which need to be both module and script and have the WD flag in all of them meaning if I solved this by dropping the command line portion into the main function you would only ever be able to run Pmag GUI in the directory you start in if you use the WD flag. 

---------------------------------------------------------------------------------------------------------------------

After looking at a bunch of pip setup_tools docs it looks like this is an artefact of setup_tools which actually wraps scripts in another script to run it for "reasons". They recommend solving this using entry points which are look like a bit of a pain. Though I guess this can be solved by having more functions one that reads command line arguments and one that starts the GUI or converts data. i.e for the GUI:

start(**kwargs) : starts the wx.App and GUI
main() : reads command line flags and parses data into kwargs which it passes to start
if __ name __==" __ main __ " : just call main as that is the entry point for pip

The point of the break of these pieces is that if they are together one has to take precedence over the other this way they are separate and Pmag GUI can start Demag GUI without having to worry about what was passed in the console. I'll have to go through and fix this in a number of places though including the conversion scripts and Pmag Dialogs. Thoughts @moonshoes87?

**Comment by moonshoes87** [comment]
In response to this comment:  So there is the scenario where you call Demag GUI and because we have the same flags I overwrite the WD input variable with the -WD flag because it is in sys.argv so demag GUI opens in the original directory not the one Pmag GUI is in now. 

This shouldn't be a problem because Pmag GUI passes in the working directory to Pmag GUI:

    def on_run_demag_gui(self, event):
        outstring = "demag_gui.py -WD %s"%self.WD
        print "-I- running python script:\n %s"%(outstring)
        demag_gui.main(self.WD, standalone_app=False, parent=self, DM=self.data_model_num)

So we can make sure it is written so that Demag GUI only looks for those values from sys.argv if those values aren't passed in from a parent GUI, which should eliminate that problem.  

I'm also confused as to why this should be a problem in the conversion scripts.  In general, the conversion scripts should not be run directly from Pmag GUI.  Instead, the underlying ipmag function should be called, which takes things like WD as an argument and should not be taking that from sys.argv in that situation.

**Comment by moonshoes87** [comment]
Entry_points are what we currently use in the setup for pip:

    entry_points={
            'console_scripts': programs_list,
            'gui_scripts': [
                    'magic_gui.py = programs.magic_gui:main',
                    'pmag_gui.py = programs.pmag_gui:main',
                    'demag_gui.py = programs.demag_gui:do_main',
                    'thellier_gui.py = programs.thellier_gui:main',
                    'pmag_gui = programs.pmag_gui:main',
                    'magic_gui2.py = programs.magic_gui2:main'}

So main is still what is run.

**Comment by moonshoes87** [comment]
Sorry, the conversion programs mostly aren't in ipmag.py.  

But they should still be run without needing to get anything from sys.argv, i.e.:

    program_ran, error_message = utrecht_magic.main(command_line=False, **options_dict)

**Comment by Caoimhinmg** [comment]
In response to the first scenario, it still requires one of the 2 values to take precedence over the other so there is the situation where one of us changes the value of the WD flag and causes a name space collision which we can just avoid all together with the second scheme, and in general the running of a script should be independent of platform to prevent these side effects.

As to the second, the conversion scripts which translate magnetometer data to MagIC data do not use ipmag functions for the main body of their work they do it locally. They used to parse data independently in the main function into variables according to a boolean which defined which of the 2 values (command line or kwarg) should be used. This resulted in a lot of redundant code and a unnecessary kwarg. So to make things more pythonic and standardized as well as shorter I moved things into the standard python script structure. Now if this doesn't work I'll have to group them as suggested above. Putting them in main would again result in the same problem which value do you use and either redundant code or the possibility for future collisions? For the conversion scripts this is a very real question as Pmag GUI has a -WD flag and so do the conversion scripts, and they have a WD kwarg.

The 2 function solution separates operation from input and doesn't add more than a line to the code for a new function declaration. It also allows us to make it universal in PmagPy that main is just the command line input function and should not be called from the python interpreter or other scripts avoiding all possible name space problems and mutations.

**Comment by Caoimhinmg** [comment]
Yeah I saw the entry points in setup.py, and I didn't really get how the setup_tools team meant them to be a solution except to allow a encapsulation of the command line setup which is kinda my suggestion above.

**Comment by moonshoes87** [comment]
Ok, as I see it, there are two important things.  

1.  Any time a conversion script or a GUI is called from within Pmag GUI, it should NOT use anything from sys.argv, but only values that have been passed into the function from the GUI.

2.  Scripts must be able to be called independently from the command line without relying on __name__ == "__main__", to be compatible with pip/setuptools installation.

Do you agree on both of the above?

So, currently in a lot of the conversion scripts that I integrated with Pmag GUI there is a command_line boolean passed into main that specifies where to get values (from the command line or from kwargs).  I don't really see a big problem with how that has worked so far, but your solution of pulling the functionality out into two pieces is fine with too.

Similarly, the way this is done in Thellier GUI is to prefer values passed in to main, and only searching for sys.argv if there is a missing value.  

Does that make sense?  I don't necessarily mind changing how this is done, but I want to make sure we are on the same page first.  I'm not exactly sure what you mean by "future collisions".

**Comment by Caoimhinmg** [comment]
I agree completely to the above.

So the reason why I suggest doing this a different way is to maintain the original purpose of the __ name __ == " __ main __ " statement which is to separate the operation of a script from the input of a script, basically allowing a file to be a script and a module. This separation technique also prevents future name collisions if say one of us decides to change the name of kwargs or flags. Because one of these has to be favoured over the other if this were to happen instead of breaking and throwing a AttributeError so you could fix the problem this external script which is theoretically using the other script would grab from the other incorrect variable and continue working incorrectly making debugging more challenging and possibly creating further errors. Basically this proofs these scripts more powerfully against changes. A further benefit is that we can make this function that encapsulates command line parsing a standard name which means it can be understood by devs not to call this function as it is not meant to be used except by the top level. Also should make the whole entry point section in setup.py easier because every entry point will be the same.

**Comment by Caoimhinmg** [comment]
Okay think I got them all I'll merge into release and we can move on to creating the next set of binaries and a new pip install.

**Comment by moonshoes87** [comment]
Looks good in the conversion scripts.

@Caoimhinmg, maybe it is too late, but in the future if you use these functions from pmag.py:


    def get_named_arg_from_sys(name, default_val=None, reqd=False):

and

    def get_flag_arg_from_sys(name, true=True, false=False):

it can make the gathering up of arguments a lot less verbose.


i.e.

    samp_con = pmag.get_named_arg_from_sys(“-samp”, default_val=1)
    # or kwargs[‘samp_con’] = pmag.get_named_arg_from_sys(“-samp”, default_val=1)

instead of:

    samp_con = 1
    if “-samp” in sys.argv:
        ind = sys.argv.index(“-samp”)
        samp_con = sys.argv[ind + 1]
