### ISSUE TITLE
sio_magic native 3 conversion script

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#154]
@Caoimhinmg, some odd things are happening in the sio_magic conversion.  I've been working with the data_files/Measurement_Import/sio_magic/sio_af_example.dat

Thing one:

It looks like specimen, sample, site, and location tables are all getting populated with a bunch of empty records.  The programs seems to be adding a record to SpecRecs for each MagRec, most of which are empty.  So, right before the specimen table is created, SpecRecs looks like this:

    SpecRecs [{'sample': 'sc12b1', 'specimen': 'sc12b1'}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}]

This then results in the MagIC tables being all wonky.  

Thing two:

Also, I made a few changes in how the contribution is created, so these lines aren't necessary:

    con.add_empty_magic_table('specimens')
    con.add_empty_magic_table('samples')
    con.add_empty_magic_table('sites')
    con.add_empty_magic_table('locations')
    con.add_empty_magic_table('measurements')

What that does is to add a table to the contribution of the proper type with default required headers and/or headers you specify (so that you can build up a table piece by piece with MagicDataFrame.add), but you are overwriting most of those defaults anyway by assigning df in these lines: 

    con.tables['specimens'].df = DataFrame(SpecRecs)
    # etc.

later.  

This ends up missing some stuff that should happen in the MagicDataFrame \_\_init\_\_, like making sure the index is set correctly.  To address this I added in a data parameter to the MagicDataFrame \_\_init\_\_.  So I changed sio_magic to add MagicDataFrames in a one-liner:

    con.tables['specimens'] = MagicDataFrame(dtype='specimens', data=SpecRecs)

This part two isn't an action item for you, I just wanted to explain what I've done.  I may do similar edits in some of the other conversion scripts as well.  Sorry that functionality was missing before, but I think that this should work better.  

I would appreciate your input on item one, though.

**Comment by moonshoes87** [comment]
The changes mentioned above have been pushed to the release branch.

**Comment by Caoimhinmg** [comment]
@moonshoes87 for item one I have a set of code in a number of the other conversion scripts I'm trying to propagate through all the scripts that it looks like I slightly messed up in sio_magic. Basically looks like this:

```python
if specimen!='' and specimen not in map(lambda x: x['specimen'] if 'specimen' in x.keys() else '',SpecRecs):
#add stuff to SpecRec and append to SpecRecs
if sample!='' and sample not in map(lambda x: x['sample'] if 'sample in x.keys() else '',SampRecs):
#add stuff to SampRec and append to SampRecs
...
```

So in sio_magic it looks like I forgot to put that last bit the append to *Recs in the if statement but rather put it at the end so it appends every time even if it is not populated. I'll push a fix in the next hour.

For thing 2, I like this method much better. I will  propagate this change through all of the conversion scripts. Though I'd feel better to if there was a way to encapsulate (like con.add_data or something) writing data to a contribution table that didn't rely on accessing internal variables like .tables or .df because then if there are future changes to the internal structure of the Contribution class like this I won't have to go through and change how every conversion script works it can just be done in the Contribution class. Thoughts?

**Comment by moonshoes87** [comment]
Yeah, I can make a "add_data" method.  Sounds reasonable.  Maybe with an "append" or "overwrite" option.  Will push that soon.

**Comment by moonshoes87** [comment]
Just made a Contribution method `add_magic_table_from data`.  It is implemented in sio_magic, which seems to be working well!

I still need to fix #155 and work on Lisa's issues before we do a new release.

**Comment by Caoimhinmg** [comment]
Prefect I'll go through and implement this in all the new conversion scripts, possibly going through Demag GUI and trying to change the many instances of this same kind of underlying variable access to this much cleaner function. I might have to modify the new function to have a translate option from 2 -> 3. Let you know how it goes.

**Comment by moonshoes87** [comment]
Great.  Currently there is no "append" option, it just overwrites.  But I think that's fine for the moment.
