### ISSUE TITLE
Issue in pmag.dia_vgp

### ISSUE THREAD

**Issue by Jollyfant** [PmagPy/PmagPy#158]
Hi devs, I was converting a direction at a given site to a VGP and then back at that same location to a direction expecting to get the same vector. Here is my code:

    site_latitude = 20
    site_longitude = -100
    dec = 40
    inc = 50

    vgp = dia_vgp(dec, inc, 1, site_latitude, site_longitude)
    dir = vgp_di(vgp[1], vgp[0], site_latitude, site_longitude)

    print dir
    >>> (320.0, 50.000000000000028)

This is unexpected and does match my original input. I think it is being caused by addition of 360 if the pole longitude is negative in dia_vgp:

    plong = plong+2*np.pi

if I comment out this line the result becomes:

    >>> (40.000000000000007, 50.000000000000014)

which is my original direction. So perhaps we should keep the returned pole longitude between -180 and 180 instead of 0 and 360. Let me know if I'm mistaken ..

Best and thanks!

**Comment by Swanson-Hysell** [comment]
Thanks for the bug report. 

The issue looks to be arising when a site longitude is being entered as being between -180 to 0 and a VGP longitude is being entered between 0 and 360. I think the ideal solution would be to modify pmag.vgp_di such that it can deal with this situation (rather than restricting the output from pmag.dia_vgp to be between -180 and 180). I will have a go at addressing this.

**Comment by Swanson-Hysell** [comment]
I put in a bug fix that is now synced up with the master that should address this issue. Here is what your example looks like now. 
```
In [1]: import pmagpy.pmag as pmag

In [2]: site_latitude = 20
   ...: site_longitude = -100
   ...: dec = 40
   ...: inc = 50
   ...: 
   ...: vgp = pmag.dia_vgp(dec, inc, 1, site_latitude, site_longitude)
   ...: dir = pmag.vgp_di(vgp[1], vgp[0], site_latitude, site_longitude)
   ...: 
   ...: print dir
   ...: 
(39.999999999999972, 49.999999999999986)
```
