### ISSUE TITLE
Pmag_gui conversion to 3.0 needs help

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#159]
The conversion process for pmag_criteria.txt does not convert sample_aniso_mean to samples.aniso_mean.  Also this needs to be added to the data model.  Rupert?  Lori?  
Also, the conversion should change all the ACCEPT under criterion to the IE-SPEC, etc. names
as is done in thellier_gui.py

**Comment by moonshoes87** [comment]
The column samples.aniso_mean is not in the current data model that I just downloaded from Earthref.  With the most up to date data model, sample_aniso_mean will be translated into specimens.int_corr_aniso_mean (this was not the case in the older, cached data model, which I will update shortly).  

From the data model json:

        "sample_aniso_mean": {
          "table_column": "specimens.int_corr_aniso_mean",
          "criterion_operation": "<="
        },

If this isn't correct, @rminnet and @ltauxe might need to clarify what should be in the data model here.

**Comment by rminnett** [comment]
Yes, although, looking back at the emails, the question I asked about mapping was a bit ambiguous. Among other things, we created **samples.int_corr_aniso_mean** (not in 2.5) and renamed **pmag_specimens.specimen_int_corr_anisotropy** to **specimens.int_corr_aniso**.

**specimens.int_corr_aniso_mean** isn't a valid 3.0 column, though. I believe the **pmag_criteria.sample_aniso_mean** should be mapping criteria rules to **samples.int_corr_aniso_mean**.

I've updated MagIC and the 3.0.json file now should map **pmag_criteria.sample_aniso_mean** rules to **samples.int_corr_aniso_mean** instead of **specimens.int_corr_aniso_mean**:

https://earthref.org/MagIC/data-model

**Comment by moonshoes87** [comment]
Ok, I pushed the updated cached data model.  @ltauxe,  the pmag_criteria.txt file you sent me now translates to this:

<img width="797" alt="screen shot 2017-03-14 at 4 45 24 pm" src="https://cloud.githubusercontent.com/assets/1836578/23925634/c05d0250-08d5-11e7-929b-32c0418dada8.png">


In the file you sent me, you have 

This study	IE-SAMP	<=	1	acceptance criteria for study	samples.aniso_mean

but if I'm understanding correctly, it looks like the right 3.0 column is actually samples.int_corr_aniso_mean

So now all we need to do is make the change in convert_intensity_criteria so that the mapping is:

sample_aniso_mean --> samples.int_corr_aniso_mean

instead of

sample_aniso_mean --> samples.aniso_mean, since samples.aniso_mean isn't a valid 3.0 column.  Then the translation will happen correctly in Thellier GUI.

@ltauxe, is that correct?

**Comment by ltauxe** [comment]
ok.  i guess i can fiddle with the ACCEPT problem later.  thanks!
lisa

**Comment by ltauxe** [comment]
THANKS!  I just pushed a version that does it exactly like this.  
lisa
