### ISSUE TITLE
experiment names 

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#163]
These originally were  intended to propagate from the measurements table up through all the other tables, but now with combined results using both anisotropy (for example) and intensity calculations (for example) the experiments column will no longer map directly to a single experiment block.  so finding a particular experiment name in the experiment column from measurements should no longer be required.  this is a data model thing.

**Comment by moonshoes87** [comment]
So all that needs to be changed is this validation?

<img width="1151" alt="screen shot 2017-03-17 at 12 11 31 pm" src="https://cloud.githubusercontent.com/assets/1836578/24056917/0f3ece08-0b0b-11e7-8195-15f0e21e5468.png">

**Comment by rminnett** [comment]
That column is a list so it can already contain multiple experiment names in it. But, if there is a measurements table in the contribution, each specimens.experiments value should be an experiment name defined in the measurements table. Is that not sufficient?

**Comment by ltauxe** [comment]
No because then there will be ultra-long, redundant lists of experiments.  can we just relax the requirement that the experiment name has to be the same in measurements/specimens?  
lisa

**Comment by rminnett** [comment]
Perhaps, but just so I understand properly:

If you have experiments A, B, and C, and a specimen that was interpreted from data in experiments A and B, you're wanting to enter a new non-experiment name in specimens.experiments (e.g. "AB") instead of "A:B", which could be quite long if the experiment names are long or there are lots of experiments to list? If so, how do we record which experiments were used to create that interpretation?

specimens.experiments isn't required, though it would be a shame not to record that information if it's available in PmagPy.

Also, if you have lots of specimens with the same, long, specimens.experiments list, we could prioritize the MagIC text file feature to list columns with shared values once in the header block:

```
tab     specimens
+ experiments A:Long:List:of:Experiments
specimen  citation
A1        This study
A2        This study
A3        This study:DOI_A
>>>>>>>>>>
tab     specimens
+ experiments A:Different:Long:List:of:Experiments
specimen  citation
A4        This study
A5        This study:DOI_B
A6        This study
```

**Comment by ltauxe** [comment]
This has been an issue for a long time because Ron Shaar made up experiment names in thellier gui without looking up the correct experiment name in the measurements file.  so all of our contributions already in the database have this violation.  I can either re-write thellier gui to do it ‘properly’,  skip the whole thing (as all the info is in the method_code column or hunt down all the correct measurements.experiment names and concatenate them.  but because the experiment names are already a colon delimited list in the measurements table it is not clear how to concatenate them in a way that would be recognizable.  because all the info is in the method codes, i think it best to just skip the experiment name in the specimens table. agreed?

**Comment by rminnett** [comment]
Not ideal - but, if the information is there, we can go back improve the contributions in the future.

Although it's uncommon so far, the standard way of escaping colons in MagIC text file lists is to enclose the values in quotes:
"An:experiment:name":"Another:experiment:name"
