### ISSUE TITLE
map_magic.py

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#164]
in attempting to clean up the 2.5<=>3.0 mapping problems, I messed up the SPD => magic mapping
could you have a look?

**Comment by moonshoes87** [comment]
I see the commit but exactly where are you finding problems?  It looks like you only edited the aniso mappings, and everything seems to still run correctly for me.

**Comment by ltauxe** [comment]
I edited the aniso mappings and also the magic mappiing.  maybe we don’t use the spd <=> magic mapping anymore?  
lisa

**Comment by moonshoes87** [comment]
Ok, you're talking about this commit: 

b3bed30

Why do you say the mapping is messed up?  Is there an error somewhere I'm not seeing?

The spd2magic_map is used in SPD (according to grep):

./SPD/spd.py:            self.pars = map_magic.mapping(self.pars, map_magic.spd2magic_map)

That's where the SPD parameters are translated to MagIC parameters for Thellier GUI (and maybe Demag GUI).  Note that what is currently implemented is translating SPD to 2.5, not to 3.0.

**Comment by ltauxe** [comment]
I haven’t found an actual error resulting from this, but the current list in pmagpy/mapping/map_magic is totally screwed up.    but that is not where we are pulling this from?  we are still using SPD/spd.py?  then that is ok.

**Comment by moonshoes87** [comment]
I see what you're saying.  

It looks like SPD/that mapping are still using in thellier_gui_lib:

./thellier_gui_lib.py:    Pint_pars = spd.PintPars(Data, str(s), tmin, tmax, 'magic', preferences['show_statistics_on_gui'],acceptance_criteria)

So, that means that that mapping should still matter.  Now that I understand where the potential problem is, I can take a look at it soon.

**Comment by moonshoes87** [comment]
I think the problem is because you edited the “magic” list with reference to "magic3", not with reference to "spd".  So the SPD mapping got all crazy.  I am going to revert back so that the spd —> magic translation still works as when originally implemented.  

I can't find a place where the  “magic3” variable was actually ever used, and when you edited it and “magic” you were actually trying to fix a different translation (it looks like you edited the global variable magic3 and the local variable magic3 from the function convert_intensity_criteria each time you made changes).  But I’m not 100% sure I got this all right.

Can you check Thellier GUI, and make sure it is still working the way you expect it to mapping wise?   It looks fine to me.

The magic --> spd mapping is now back to looking like this:

[('specimen_coeff_det_sq', 'R_corr2'),
 ('specimen_PCA_sigma_int', 'PCA_sigma_int_Free'),
 ('specimen_PCA_sigma_max', 'PCA_sigma_max_Free'),
 ('specimen_int_ptrm_tail_n', 'n_tail'),
 ('specimen_dpal', 'delta_pal'),
 ('specimen_tail_drat', 'DRAT_tail'),
 ('specimen_md', 'MD_VDS'),
 ('specimen_ac_n', 'n_add'),
 ('specimen_dac', 'delta_AC'),
 ('specimen_cm_y', 'y_Arai_mean'),
 ('specimen_int_mad', 'MAD_Free'),
 ('specimen_int_ptrm_n', 'n_ptrm'),
 ('specimen_drat', 'DRAT'),
 ('specimen_z_md', 'IZZI_MD'),
 ('specimen_frac', 'FRAC'),
 ('specimen_cdrat', 'CDRAT'),
 ('specimen_dec', 'Dec_Free'),
 ('specimen_mdev', 'mean_DEV'),
 ('specimen_drats', 'DRATS'),
 ('specimen_z', 'Z'),
 ('specimen_maxdev', 'max_DEV'),
 ('fail_arai_beta_box_scatter', 'fail_arai_beta_box_scatter'),
 ('specimen_gmax', 'GAP-MAX'),
 ('specimen_ptrms_mad', 'pTRM_MAD_Free'),
 ('specimen_ptrms_dec', 'ptrms_dec_Free'),
 ('specimen_int_mad_anc', 'MAD_Anc'),
 ('fail_ptrm_beta_box_scatter', 'fail_ptrm_beta_box_scatter'),
 ('specimen_ptrms_angle', 'ptrms_angle_Free'),
 ('specimen_scat_bounding_line_low', 'scat_bounding_line_low'),
 ('specimen_PCA_sigma_min', 'PCA_sigma_min_Free'),
 ('specimen_int_uT', 'B_anc'),
 ('specimen_scat', 'SCAT'),
 ('specimen_r_sq', 'R_det2'),
 ('specimen_PCA_v1', 'best_fit_vector_Free'),
 ('specimen_b_beta', 'specimen_b_beta'),
 ('specimen_YT', 'specimen_YT'),
 ('specimen_dck', 'delta_CK'),
 ('lab_dc_field', 'lab_dc_field'),
 ('specimen_inc', 'Inc_Free'),
 ('specimen_mdrat', 'mean_DRAT'),
 ('specimen_theta', 'theta'),
 ('specimen_ptrm', 'max_ptrm_check'),
 ('measurement_step_min', 'tmin'),
 ('specimen_cm_x', 'x_Arai_mean'),
 ('fail_tail_beta_box_scatter', 'fail_tail_beta_box_scatter'),
 ('specimen_dtr', 'delta_TR'),
 ('specimen_int_alpha', 'alpha'),
 ('specimen_fvds', 'specimen_fvds'),
 ('specimen_b_sigma', 'specimen_b_sigma'),
 ('specimen_b', 'specimen_b'),
 ('specimen_g', 'specimen_g'),
 ('specimen_f', 'specimen_f'),
 ('measurement_step_max', 'tmax'),
 ('specimen_int_n', 'specimen_int_n'),
 ('specimen_q', 'specimen_q'),
 ('specimen_int_dang', 'DANG'),
 ('specimen_ptrms_inc', 'ptrms_inc_Free'),
 ('specimen_k_sse', 'SSE'),
 ('specimen_gamma', 'gamma'),
 ('specimen_scat_bounding_line_high', 'scat_bounding_line_high'),
 ('specimen_k', 'specimen_k'),
 ('specimen_int_crm', 'specimen_int_crm'),
 ('specimen_dt', 'specimen_dt'),
 ('specimen_k_prime', 'specimen_k_prime'),
 ('specimen_k_prime_sse', 'specimen_k_prime_SSE')]

**Comment by moonshoes87** [comment]
Sorry @ltauxe -- I hadn't actually pushed the relevant commits when I left the last message.  All is now up to date!

**Comment by ltauxe** [comment]
i’m using the magic3 mapping in the criteria reading/writing thing and now it works so please don’t touch that.  can we just move the spd <=> magic mapping somewhere else?  

lisa

**Comment by moonshoes87** [comment]
Can you show me where you use the magic3 variable (which file, which approximate line)?  I couldn’t find it.  I want to organize to make sure we don’t have any namespace collisions and that SPD/magic stays separate from magic3/magic2.

The current state of master doesn’t have the magic3 variable, but I’ll stick it back in based on the last commit you did (ce11ee8) where it was working.

**Comment by moonshoes87** [comment]
Ok, also, as of your last commit to map_magic (ce11ee8), the mapping between magic and magic3 is definitely broken.  I grabbed the two lists from your last commit (before I had done anything with map_magic) and tried zipping them together, and they are definitely off.  So, if you are using this translation somewhere, you are getting rubbish things like specimen_md —> specimens.int_dac.

**Comment by moonshoes87** [comment]
I think you are just using 

                crit3_0=map_magic.convert_intensity_criteria('magic3',crit)

which does not use the global magic3 variable, but a local magic3 variable defined in ‘convert_intensity_criteria’.

**Comment by ltauxe** [comment]
for the mapping in thellier_gui.  
I call it here: 

m2_name=map_magic.convert_intensity_criteria('magic2',crit['table_column’])
[ this one is fine!]  

here: 

new_data=map_magic.convert_aniso('magic3',new_aniso_parameters) # turn new_aniso data to 3.0
[which is also fine]

here: 
new_data = map_magic.convert_spec('magic3', new_spec_data) # turn new_specimen data to 3.0

[which calls your new maps.all_maps and is also fine]

here:  
new_data = map_magic.convert_samp('magic3',new_sample_or_site_data) # convert to 3.0
[which calls maps.all_maps]

here: 
 meas_data2_5 = meas_data3_0.rename(columns=map_magic.meas_magic3_2_magic2_map)
[also ends up in maps.all_maps]

so i think i avoid that bad spot and we should just remove it.  

lisa

**Comment by moonshoes87** [comment]
Yes, great.  We should be good with what I removed, then.  Let me know if you spot any sketchy behavior, but I think we are fine.
