### ISSUE TITLE
default to 3.0 with all scripts

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#172]
I'm planning to switch defaults so that the plotting programs and import scripts on the command line are all 3.0.

This includes:

- switching the names of some plotting programs (i.e., core_depthplot3.py becomes core_depthplot.py, and core_depthplot.py becomes core_depthplot2.py and is eventually deprecated).

- making sure @Caoimhinmg's native import scripts are available in the pip install and on the command line by default (they are currently default in Pmag GUI).  This will probably mean moving them into the programs directory, and perhaps moving the 2.5 scripts into a subdirectory.

If anybody sees a problem with this, let me know.

**Comment by Caoimhinmg** [comment]
Hey @moonshoes87 I would request that we keep the 3.0 scripts in the conversion_scripts directory because it would separate them from the very different analysis programs and simply because the programs directory is jam packed with files. Also makes it easier to see which data formats we support at a glance rather than combing the programs directory. I know this means altering the pip install to add this directory to path and possible import issues, but I think it makes sense from a development and usage stand point. I'd also propose sticking the 2.5 scripts in depreciated/conversion_scripts/ so the python imports are similar and that it is obvious the 2.5 model is depreciated as a bonus you can stick programs like core_depthplot2 here too to make things consistent and reduce clutter. Thoughts?

**Comment by moonshoes87** [comment]
@Caoimhinmg, I can see your overall organizational point.  I agree about moving the 2.5 scripts to a deprecated folder.

 The reason I don't want to leave the 3.0 scripts where they are is for the developer install.  Fixing the pip install is trivial and occurs behind the scenes, but the more we separate out programs into different folders, the more lines are required to set the user's path manually.  

Right now all that is actually needed is something like this:

    PATH=/Users/***/PmagPy/programs:$PATH
    export PYTHONPATH=$PYTHONPATH:/Users/***/PmagPy/

But if we separate out programs, we have to add a line for each subfolder that contains programs that should be accessible on the command line.  This is particularly annoying  in Windows.  

Organizationally, it could make sense to have a lot more separation in the programs directory, but I dislike the additional install hassle.  @ltauxe, @Caoimhinmg, @Swanson-Hysell ?

**Comment by moonshoes87** [comment]
@Caoimhinmg, can you tell me what's going on with programs/cit_magic3.py and programs/cit_magic.py?  Should both of those be kept and deprecated in favor of programs/conversion_scripts/cit_magic, or can one be deleted and one deprecated?

**Comment by Caoimhinmg** [comment]
So @moonshoes87 you can fix the PATH issue by somewhat throwing caution to the wind and adding all subdirectories of programs to PATH as described [here](http://unix.stackexchange.com/questions/17715/how-can-i-set-all-subdirectories-of-a-directory-into-path). This is considered somewhat hazardous as it allows malicious ware to add a exe or subdirectory to path without needing sudo and makes it easier to accidentally add malicious ware to PATH. Though this is mostly true for setting a directory to path outside a protected folder in the first place which already happens in most traditional developer installs so it seems like a mote point. 

Alternatively we could set up symbolic links that take advantage of the protected directories in PATH and redirect you out of /usr/bin/local or whatever to where you're going. They exist on all platforms described here for [Linux and Mac](https://kb.iu.edu/d/abbe) and [Windows](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/). This would be more work for us but should make it easier for users trying to set up a dev install as we could automate it to a script.

As to the programs/cit_magic and programs/cit_magic3 can either both be depreciated or cit_magic depreciated and cit_magic3 removed as all it does is translate cit_magic to the 3.0 data model before exporting and was just created to get @Swanson-Hysell's lab up using the 3.0 data model while the framework was being put into place in the GUIs.

**Comment by moonshoes87** [comment]
The Linux/Unix solution of adding all subdirectories won't work for PATH setting in Windows, unless the user has cygwin or something like that.  

I do like the idea of having a dev install script.  That is basically how PmagPy used to be installed pre-pip.  However, we had a lot of trouble setting PATH in a script for windows (@rminnett worked on this) in a way that was consistently successful.  That is why we ended up with the old solution of making a custom PmagPy prompt for Windows.  I will send you the discussion chain where we were struggling with this.

Can you explain a little more how using symlinks would help with this problem?

Thanks for the explanation on cit_magic, I will deprecate cit_magic along with the other upgraded 2.5 scripts and remove cit_magic3.

**Comment by moonshoes87** [comment]
@Caoimhinmg, I still want to move forward with this one way or another.

Options:

1.  We leave conversion_scripts as is, modify the Cookbook to add another required line for the developer install, and don't worry about people developing on Windows.

2.  We temporarily move conversion_scripts into the main programs directory which keeps the developer install simpler and try to make a dev install script later.

Or something else?

I would like to make a new pip release soon that includes the native 3.0 conversion scripts.  I also want to make sure the 2.5/3.0 difference is organizationally clear so developers like @njarboe  don't waste time barking up the wrong tree.  

I am currently focused on usability of Pmag/Magic GUIs and edge cases, then figuring out Canopy Python 3, so making a dev install script is not something I can devote time to right now.  Let me know if you want to work on that now, or have input on one of the other solutions.  Thanks!

**Comment by Caoimhinmg** [comment]
@moonshoes87 I agree that we should just do this quick and figure out a better solution later. For now I think we should do option1 as it keeps the structure the way we want it assuming I can create a cross platform install script. Also I can't think of anyone using a Windows dev install right now so that problem is basically null. I've almost got a unix install script done having just taken a quick hack at it, I'll see how troublesome windows is.

**Comment by moonshoes87** [comment]
@ronshaar I believe is developing on Windows, but he mainly does fixes on Thellier GUI which will not be affected.  I don't think we can ignore Windows for too long.  

I've gone ahead and shuffled some things around.  I will update the Cookbook shortly to reflect the temporary developer install instructions, make sure the pip install still works, and make a new pip release.  

Also, in making this transition I noticed a few programs that should probably be updated to native 3.0 and incorporated into Pmag GUI: iodp_samples_magic, and huji_sample_magic.  @Caoimhinmg, would you be able to do the 3.0 switchover?  I am happy to plug them into Pmag GUI, but thought you might be the right person for the conversion since you've done a bunch of them already.

**Comment by Caoimhinmg** [comment]
I'm working on the Windows script there is some issues with setting environment variables to run python.exe when using .py files and for some reason as @rminnett points out in the email train you sent me there is this ridiculous limit on PATH variable length such that it can only be ~300 characters. I'm also having some issues testing in a VM because of how administrator privileges work.

I noticed iodp_samples_magic, but as far as I can tell it doesn't work on any of the IODP file types I have been given from IODP, found on their website, or have test data for. As such I assumed it had been outmoded for iodp_dscr_magic.py which is described as "converts ODP LIMS discrete sample format files to magic_measurements". The huji_sample_magic was one I previously asked about where I mentioned that I had no useful test data for it and all the test data I had in huji format was convertible with just the new huji_magic.py. This made me assume that this is also an outdated unnecessary script. If you can find me some test data that needs these scripts I'd be happy to convert them quickly.

**Comment by moonshoes87** [comment]
Ok, keep me posted about the Windows install shenanigans.  

That’s right, I forgot.  Well, maybe both of those scripts are unneeded.  I’ll leave them for the moment.

**Comment by Caoimhinmg** [comment]
Okay, here is what I've come up with for a Windows and Unix combined install script. It's written in python and only uses native libraries. It has worked on both my Linux distro and my Windows VM after removing my manual path setting. My goal in using python was to require python be pre-installed and so it can be more or less maintained by anyone working on the project. It needs more testing, and can be rerun on windows as much as you want but should only be run on Unix once or it can stack up more directories in PATH (still need to fix that). The script must be run from the PmagPy directory and in Windows it needs to be run as an administrator or nothing works, and in windows to get behaviour similar to Unix I need the user to supply the location of their python.exe after the -p flag. I'd ask as many devs (@moonshoes87, @rminnett, @njarboe, @Swanson-Hysell) with as many different distributions and VMs to backup their changes to .bashrc, .bash_profile, and .profile and run the script to test it, or in Windows to save their PATH and PYTHONPATH variables to a text file then run the script and if you need to restore variables run setx PATH %SAVEDPATH% and setx PYTHONPATH %SAVEDPYTHONPATH%. Where you copy and paste those saved PATH variables to replace the above %% place holders. Let me know how it goes and thanks.

**Comment by Caoimhinmg** [comment]
Just gave the dev_setup.py script a major update, it mostly works the same, but now has uninstall and reinstall options details on usage can now also be found in documentation accessed by running python dev_setup.py -h. Let me know if anyone runs into any troubles.

**Comment by moonshoes87** [comment]
Thanks @Caoimhinmg, I'll try to test this out today.

**Comment by moonshoes87** [comment]
@Caoimhinmg, the dev install script worked for me without a hitch on OS X.

One question, for the Unix install, do you need to duplicate the $PATH information in three places?  Just to make sure it is hit no matter what?  This leads to a very long $PATH, which isn't an operational problem but is annoying for someone who wants to glance at their $PATH and understand what's in it.

I also tried it on a Windows 10 virtual machine, and the install was successful, but the uninstall failed with this error:
![screen shot 2017-04-18 at 12 44 01 pm](https://cloud.githubusercontent.com/assets/1836578/25149863/c595f1bc-2434-11e7-99f2-7fe26e69ac4f.png)
 
Overall, it's looking good!  I did make a few small clarifying edits in the help text.

One last semi-unrelated note: it is better to use this style of link:  https://earthref.org/PmagPy/cookbook/#pip_install, instead of this style:  https://earthref.org/PmagPy/cookbook/#x1-80001.2.1.  The latter can change when the LaTeX is re-compiled, but the customlinks stay the same.  Unfortunately that means that you have to go into PmagPy.tex to find the customlink names, but it is more robust.

**Comment by Caoimhinmg** [comment]
@moonshoes87, the duplication of the PATH in the 3 configuration files is done because of the different kinds of bash shells that can run. Login vs. non-login and because of a failure I found when having it tested by a user on OSX. Theoretically .bash_profile shouldn't need to have the lines because it truly is duplication of .profile which is preferable as it is shell type independent, but for some reason it didn't work when tested on OSX. So I added .bash_profile. The add to .bashrc is important because in non-login bash shells it always works even if it isn't always the recommended method for this. Though bash should only read from one....I could alter the added bash code to make sure it doesn't allow duplicates. I'll look into it. 

In other news the Windows problem is easily resolved. I simply forgot that Python is unreasonable about using functional programming techniques and therefore doesn't have a empty list case in their reduce function. Should be fixed in next comment.

**Comment by Caoimhinmg** [comment]
Also one more side note on that Unix thing, you're actually not supposed to put environment changes in your .bashrc, but if you don't then I have to ask the user to restart their computer to affect changes. This is because .profile is only read in on start up so if you pull and there are directory changes you have to restart to fix it.

**Comment by Caoimhinmg** [comment]
All right @moonshoes87 give the dev_setup another go it should no longer duplicate paths in PATH during the Unix install and the Windows uninstall should no longer error.

**Comment by moonshoes87** [comment]
Hmm, I've never seen anything that says you shouldn't put environment changes in your .bashrc.  Just curious, where does that recommendation come from?  I've always preferred having things in .bashrc so I can make edits and not restart, as you mention.  

Also, I still have duplicate paths when installing on Mac even after pulling commit ee7dc9d29835c3c358aefb14784275d5172d0056

I will re-check the Windows uninstall.

**Comment by moonshoes87** [comment]
Windows install/uninstall works great for me!  

The duplicate paths aren't necessarily a huge deal, if it turns out to be a pain to fix.

**Comment by Caoimhinmg** [comment]
Darn, @moonshoes87 can you manually remove the edits made to the configuration files by the script and try the unix install again. It is probably just that my uninstaller is not working so great for the old form of the bash code. I had to make a few structural changes to prevent duplicates.

Also the recommendation to not put environment changes in .bashrc is coming from just about every forum I found on the topic (most on StackOverflow of course). For some reason all the answers said the same things put env changes in .profile. I have absolutely no idea why.

**Comment by moonshoes87** [comment]
That's funny, when I googled around I couldn't find any advice like that.  I guess we're in different google bubbles, somehow ;)  

I gave the install/uninstall another try, and I still get duplicates.  I'm not sure why, because your logic looks correct.  Maybe it has to do with exactly when the $PATH s from the .profile, .bashrc, .bash_profile are actually concatenated?  

Also, we shouldn't need the main "PmagPy" directory in the $PATH, only in $PYTHONPATH for imports.

**Comment by Caoimhinmg** [comment]
Fair point @moonshoes87, I'll remove the PmagPy directory to prevent name space collisions and simplify PATH.

Also [here](https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path)'s an answer from one of the StackOverflow posts I found which helped to create this script. He details/links lots of ways to manipulate environment variables and links to another post which goes very in depth on the difference between the 3 standard Unix shell configuration files. It's really quite interesting, and has proved extremely useful.
