### ISSUE TITLE
In the demag_gui "add fit" does not save the fit name if one makes a custom fit name 

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#186]
Maybe I am not using the GUI correctly, but when I make a fit I would like to create my own name for the fit and then use that name on many specimens. If I click on add fit, I can change the default name from "Fit 1" to say "ChRM". I then select the demag steps I want for the fit. If I then go to the next specimen, "ChRM" is not available and I have to type ChRM in every time. This also happens if I hit save on the first fit. Is this expected behavior? I imagine people at Berkeley are not typing in the fit name over and over, so I am probably missing something. If you can help me out, that would be great.

**Comment by Caoimhinmg** [comment]
When you click the "add fit" button in the main frame of Demag GUI you will always get a fit with a default name, the same occurs if it is your first fit and you double click on the list. This is because there isn't a good way to pick out what name to use so it picks a default generally of the form "Fit #". 

If you want to rename a fit you have created click on the text potion of the fit drop down menu and overwrite the name then push enter to save it. This does require you to do it manually as you do your analysis however.

If you want to analyse the data more quickly, or edit interpretations in mass you should use the Demag GUI tool Interpretation Editor (IE). The IE can be found under the tools menu of Demag GUI and allows mass creation of fits, mass alteration of fits, mass deletion of fits, easy marking interpretations bad/good, and easy high level means interpretation.

This is usually the way I use Demag GUI to manage interpretations. Here's an example:

If you want to rename say all default named interpretations called "Fit 1" to "LowT" or "Mag" you would

- Open IE (hotkey: ctrl-e)
- Ensure your current level is the level over which you want to enact change (usually this is set to site, but if you want to say edit all interpretations in the study you will need to change it to study). It is the second drop down box on the top.
- Type "Fit 1" into the search bar
- type new name into the name box
- click and highlight using shift/control/command/or ctrl-a all interpretations
- click "apply changes to highlighted fits"

You can also change color, or bounds using the same method. Searching using the search bar just helps if you have a large dataset.

You can use the IE help menu to get in context help by clicking on "Usage and Tips" (hotkey: ctrl-h) then clicking on what you want more info on.
There is more about it here: https://earthref.org/PmagPy/cookbook/#x1-510005.1.1

**Comment by njarboe** [comment]
Thanks for the info @Caoimhinmg. I guess it makes more sense when you are getting new data you just call it Fit 1, Fit 2, etc because until you have done quite a few, you may not know what caused the components yet. Especially for you guys doing 0.5-1 Ga rocks. When I am loading studies already published, I know all the fits and just want to set them straight away. Maybe a feature for the future.
