### ISSUE TITLE
Earth-Ref MagIC builder in model 3.0 overwrites sample orientation in samples.txt

### ISSUE THREAD

**Issue by ronshaar** [PmagPy/PmagPy#196]
Environment: 
MagIC model 3.0 , Python 3.6, osx.10.11

I use orientation_magic in pmag_gui to calculate sample orientation. orientation_magic.py writes two lines to samples.txt:  one with "SO-MAG" and second one with "SO-MAG:SO-CMD-NORTH"

When Im using Earth-Ref MagIC builder to add ER data the program delete the line with "SO-MAG:SO-CMD-NORTH" leaving only  "SO-MAG", 

What is the best solution? Should orientation_magic.py  write just one line to samples.txt?

**Comment by ltauxe** [comment]
If you put the higher priority orientation first (SO-CMD-NORTH) in the file, that would be better.   What absolutely has to be in the samples table is the one that is used.

**Comment by moonshoes87** [comment]
I can check and see why this is happening.  Could you send the files that you are using that have produced this error?  Thanks!

**Comment by moonshoes87** [comment]
I've made some progress on this.  

I fixed the problem in Pmag GUI step 3 where some lines from the sample file were incorrectly deleted.  @ronshaar, could you give this another try and let me know if it seems to work as you expect?

There is another problem in orientation_magic with MagIC 3:

If there is pre-existing data for a sample, cooling rate and method codes appear to be overwritten in orientation_magic, so we lose that information.  For example, if there are records with LP- method codes, those are swept away by orientation_magic.  What is the desired behavior:

- Append the method codes, so that you end up with LP-\*:SO-\*, etc., in each row for a given sample?  

- What if there are multiple pre-existing rows with different method codes?  Should orientation_magic just add new rows if method codes would be overwritten, so if a sample_A has two rows to begin with it ends up with four or five?

@ltauxe, @ronshaar ?

**Comment by njarboe** [comment]
Hello @ronshaar ,

I was trying to figure out how to solve your problem and I was wondering why you want to record three different ways of measuring the orientation of a sample? Lori gave me this file as an example of your data.
[output_samples.txt](https://github.com/PmagPy/PmagPy/files/1033055/output_samples.txt)

Do you want people to be able to choose a different one if they want? I would think that you would decide what is best and give that as the "true" orientation of the sample. @ltauxe, do you have any reasons why we would want to support multiple orientation types for a single sample?

**Comment by ltauxe** [comment]
in the 2.5 version, ONLY the one used was kept, so that does make sense.  I can imagine a scenario in which someone might want to compare different orientation methods (like we did in Cromwell’s Jan Mayen study), but I’m happy with just keeping the ‘best’ one in the database.  makes life simpler.  
lisa

**Comment by moonshoes87** [comment]
Also, just to clarify, I completely invented the orientation file that I used with Ron’s data and populated it with arbitrary values, so it isn’t very “realistic”.

Getting rid of all but the best orientation is definitely a simple solution to implement...

**Comment by moonshoes87** [comment]
@njarboe & @ltauxe , what is the status with this?  Should I update ipmag.orientation_magic to only keep the top orientation?  Also, what about appending vs. not appending method codes?

**Comment by ltauxe** [comment]
sorry - i’ve been working on something that was due a while ago.  will try to catch up this week.  
lori - maybe we can skype tuesday?  
lisa

**Comment by moonshoes87** [comment]
@njarboe, @ltauxe, and @ronshaar -- some pieces of this issue were fixed.  We have two remaining questions:

1.  Should we delete all but the highest-priority orientation?

2.  How should we deal with pre-existing method codes when running orientation_magic?  We can either append method-codes together, or create a new row if there is any pre-existing information in method_codes for that specimen.

**Comment by moonshoes87** [comment]
Since the main problem we had with orientation_magic was fixed, I'm going to assume that remaining questions raised in this issue are not important.  Re-open if you disagree.
