### ISSUE TITLE
demag_gui does not handle multiple locations

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#219]
@moonshoes87 @Caoimhinmg 

Using the Python 3 stand-alone of pmag-gui and these files:
[SheepCreekMagICFiles.zip](https://github.com/PmagPy/PmagPy/files/1072362/SheepCreekMagICFiles.zip)

when I open the demag gui, only the sites in the first location "Western Locality" is displayed. If I change the display level to location the only option is "Western Locality" and the two others in the locations.txt file do not display. Maybe the Nick S-H group has only worked on files with one location, so this problem has not come up before. We definitely need a way to switch between viewing different locations and it would also be nice if when one is at the site display level that the location level is displayed somewhere.

**Comment by Caoimhinmg** [comment]
@njarboe It should be able to handle multiple locations I used to test regularly with multi-location projects just in case. I'll give it a look and see if I can figure out what's up.

**Comment by Caoimhinmg** [comment]
Hey @njarboe, sorry about the like 2 month delay on a real response to this. So I just looked in depth on this and the problem seems to be mostly with the data. The measurements.txt has the no dec or inc data for any of the specimens in any of the locations besides Western Locality so Demag GUI doesn't allow the user to try to display the measurement data as it doesn't exist. In addition the some of the fields are improperly filled in measurements.txt with what appears to be sample and specimen name data in dir_csd and dir_dec, though you could probably fix this in a spreadsheet program. Though the GUI seems to work normally on other data with more than one location, so I'm going to close this issue.

**Comment by njarboe** [comment]
@Caoimhinmg, Thanks for taking a look at this. The file was quite malformed. I'll take a closer look at that in the future before reporting problems with pmag_gui. Hope you are enjoying Rice so far and the flooding is not too crazy where you are.
