### ISSUE TITLE
latitude/longitude in generic_magic input

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#226]
Should this be "location" latitude/longitude?  Otherwise this only makes sense if you only have a single site in your measurement file....  And, of course, it is possible to have more than one location.  This seems a bit confusion and might benefit from clarification.  @Caoimhinmg, this is your addition, right?   

<img width="323" alt="screen shot 2017-06-14 at 11 53 31 am" src="https://user-images.githubusercontent.com/1836578/27149540-dd4d0e4e-50f8-11e7-9895-f8800fbd49cc.png">

**Comment by ltauxe** [comment]
i don’t think this should be in pmag_gui at all.  i found it confusing.  we should have the site lat/lon data filled in via orientation_magic or the gui, not at the study level.  
lisa

**Comment by moonshoes87** [comment]
I removed the input box for latitude/longitude in Pmag GUI, but left it alone in sio_magic itself.

**Comment by Caoimhinmg** [comment]
@moonshoes87 Yes I did this, mostly because there didn't seem to be a method for adding this and for Demag GUI this information is extremely useful for outputting tables and generating figures. I knew it was a bit hack and slash but I figured it was better than nothing. Though if there are other better channels to allow adding this data then this method should certainly be removed.
