### ISSUE TITLE
marking good/bad measurements in Demag_GUI 

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#24]
The good/bad measurement highlighting behavior still seems a little unintuitive.  

First of all, it doesn’t seem like I can simply right click on a measurement — I actually have to select it with a left click and then right click.  Additionally, I was confused when I accidentally double-clicked on a measurement (trying to mark it as good/bad) and the whole fit was recalculated.  Last thing, measurements outside of the fit cannot be marked — is this the desired behavior?  

A possible UI solution: maybe we could introduce a 6th column in the measurements list with a checkbox the denotes a ‘bad’ measurement (or ‘good’).  This might be a slightly irritating to implement with wxPython, but I think it would make a lot of sense from a user perspective.  

Thoughts on this?  @Swanson-Hysell, @Caoimhinmg , @ronshaar

**Comment by moonshoes87** [comment]
I think there are two things that make sense to fix:

1.  If possible, make it so that the highlighting for "bad" measurements stays highlighted when the user is selecting the fit parameters.

2.  Have a checkbox type column.  This is easy to do in wx.grid, but as this is a list ctrl I'm not sure if it works the same way.  Even if it is a ghetto checkmark that's just, say, an X for bad and a blank space for good, I believe it would help communicate more clearly.

**Comment by Caoimhinmg** [comment]
* I added a "Flag Measurement Data" drop down box to the edit menu that lets you flag highlighted fits good/bad to try and make this more intuitive.
* The checkbox idea sounds great though I'm also not sure how easy that would be to do in a listctrl.
* as to the keeping bad things marked bad when selecting fit parameters. Done and done.

**Comment by Swanson-Hysell** [comment]
Having the drop down box is nice as it exposes the functionality to users who don't know about the right-click option. And it is good that the "keeping bad things marked bad when selecting fit parameters" issue is now fixed and there is the ability to mark good and bad outside of the fit.

I agree with Kevin that the checkbox idea is a good one, but given space limitations in the GUI and not wanting to add too much more complexity to the main screen, I think it may be best not to add that at present so am closing the issue for now since I think the other smaller items have now been addressed.
