### ISSUE TITLE
Windows troubles with default program to open .py files

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#243]
On my Windows 10 virtual machine, I set Atom as the default program to open .py files.  This was a big mistake, and now when I try to run PmagPy programs, Atom is opened.  I tried resetting it using "choose default apps" for .py files, but there is no appropriate python option available that way.  I suspect I would have to go into the registry and select python.exe, or something like that.  

This stack overflow question gets at the same thing: https://stackoverflow.com/questions/15121714/how-do-i-get-a-python-program-to-run-instead-of-opening-in-notepad

This seems like a problem a user easily might encounter, too.  I can just spin up a new virtual machine, but I am stumped on how to simply fix this, which we would want a user to be able to do.  

Anyone with more Windows savvy have thoughts on this?  @Caoimhinmg, @rminnett?

**Comment by njarboe** [comment]
I had a similar problem with the .py extension being attached to the wrong
program and never did find a solution. Now on windows 10, so left the
problem behind on my window 7 install.

**Comment by Caoimhinmg** [comment]
No, this is one of the dumb problems Windows has with interpretive languages like python. The thing is .py is encoded as a text file not an executable so Windows will by default always try to open a word processor or text editor. Which means to run the .py files you have to run through a shell or compile the text file to an executable there is no option to treat it like an executable by default and pass it through the interpreter unless you manually find python and set it by hand. There might be a way to do this last bit with a batch script but I'm not Windows savvy enough to know how. As I see it though most users on windows will just use the executables anyway, if not they're going to be using the scripts in a shell so in general it shouldn't be much of an issue.

**Comment by rminnett** [comment]
Yes, I agree, we could possibly include a jscript to set the extension to run the Python interpreter, but that's not really how those scripts are intended to be used. The .py files are meant to be used on the command line with arguments, not executed by clicking on the file. If this is what users are doing, the effort is better spent on adding instructions to the cookbook or directing people to the cookbook than on getting .py files to run the interpreter.

**Comment by moonshoes87** [comment]
This problem occurs not only when clicking on a file, but also when trying to run the executable on the command line.  So I think this is a significant concern for anyone doing development on Windows -- if you choose, say, Atom as your .py default, you will no longer be able to run .py files as executables from the command line.

**Comment by rminnett** [comment]
Oh, I see, well if they're just trying to run a single Python script then adding "python " in front of the script's name on the command line should work if Python is installed. 

Otherwise, at least for Windows 10, to reassociate the .py files with the python interpreter they have installed:
- in a command line type "where python" and make a note of the location of their preferred python interpreter or (if it's not in their environment variables, find the python.exe file they want to use)
- right click on any .py file in File Explorer
- click "Change" next to "Opens with:"
- click "More Apps" at the bottom
- click "Look for another app on this PC" at the bottom
- browse to the location of and select the python.exe file from the first step above

**Comment by moonshoes87** [comment]
Thanks Rupert!  I was able to follow those steps successfully.  Unfortunately, that resulted (I think) in python no longer working on the command line.  

    'python' is not recognized as an internal or external command, operable program or batch file

Anaconda Python is still in my path, though (which is looking a bit weird because of running dev_setup.py...):

<img width="1108" alt="screen shot 2017-09-30 at 3 43 18 am" src="https://user-images.githubusercontent.com/1836578/31045133-961ae972-a591-11e7-88fd-73d71082afa5.png">

Perhaps I just need to create a new Windows VM and discard this one, because things have gotten so mucked up.  But I am concerned about the user experience of Windows.  Thoughts?

**Comment by njarboe** [comment]
As you might have heard, Microsoft recently added the ability to run various linux environment in windows. I'm wondering if this might be a better path to take. I have not installed any of these myself and this might just be another rabbit hole to go down, but it could be much better to set windows people up in the linux environment, if they want to run on the command line. PmagPy was built on a unix type system and works with a lot less problems there. We could promote the stand-alone for people on windows who just want to run the GUIs and a windows linux environment for people who want the command line or the development branch from git.
Do you know much about this new possibility @Caoimhinmg ?

Here is a starting blurb from this Microsoft webpage: https://msdn.microsoft.com/en-us/commandline/wsl/about

The Windows Subsystem for Linux lets developers run Linux environments -- including most command-line tools, utilities, and applications -- directly on Windows, unmodified, without the overhead of a virtual machine.

**Comment by rminnett** [comment]
Hmmm, that PATH environment variable looks suspiciously messy (Windows is supposed to ignore extra backslashes, but you also have duplicate entries and appear to include Anaconda, which should give you at least one python.exe) . Before giving up on that VM, you could:
- right click on the Windows icon on the left of the taskbar
- select "System"
- click on "Advanced system settings"
- click on "Environment Variables"
- select "Path" in the bottom "System variables" and click "Edit..."
- click "Edit Text" and copy the "Variable Value" to a text editor
- remove of extra backslashes
- remove all duplicate entries (and the last entry of "C:\Windows\s" looks incomplete)
- copy and paste the cleaned text back into the "Variable Value" and click "OK" on the three windows

If that doesn't let you execute "python" on the command line, it might be time for clean VM.

The Windows Subsystem for Linux option might be a cleaner solution for Windows users, but it requires Windows 10 Anniversary Update (August 2016) or newer on 64-bit and requires the user to install additional software other than just a python distribution and PmagPy. I don't know if that's too restrictive for some older lab computers?

**Comment by moonshoes87** [comment]
Ultimately, I removed all PmagPy/Python stuff from my PATH manually as @rminnett explained above, then reinstalled.  I don't think there's a really clean solution to the Windows madness.  Hopefully if anyone gets into this same situation, they will find this issue as a reference.

**Comment by mvhanson** [comment]
you can also right click on the file you want to open (a .py file) and then select "open with" and then "choose another app" and then "more apps" and then scroll down until you see "Look for another app on this pc" and then find your python27 or python37 folder and then right click on the "python" file and then select "troubleshoot compatability" and then "try recommended settings." And then "test the program" it should pop up a command window with python in it. Click next, and then "save these settings for this program" and then close the troubleshooter. 

I was trying to figure out how to just click on a python file and have it run (including args that I needed to input) because running python programs in an IDE or interpreter just slows them down.

If they can run in a command window that speeds them up a bit plus if you've put in "print" commands here and there you can see the progress -- most IDEs just stall out leaving you clueless. 

Anyways, hope this is helpful for Windows 10 python users.

**Comment by kolipakakondal** [comment]
Right-click on a file > Open With > Choose default Program > Click on Browse > Select python.exe 

I found python.exe in the **C:\Users\Kondal\AppData\Local\Programs\Python\Python37**

**Comment by RSwarnkar** [comment]
Here is screenshot of this error: 

![image](https://user-images.githubusercontent.com/24961188/123199805-2e978c00-d4cd-11eb-983f-5853b8d49a70.png)
