### ISSUE TITLE
dev_setup.py not working as expected on Windows

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#244]
Dev_setup.py hasn't been working correctly on my Windows 10 VM.  (It appears to work correctly on OS X).   I had to update some of the syntax from Python 2:

ce891f251a28abfa4c8ef5997f61e164e1078343

7ae354b4d0c25c5859e178452663373324add73b

Once I fixed those issues, I tried again to install.  The install reported success, but with the character limit issue:

<img width="1108" alt="screen shot 2017-09-23 at 2 57 24 pm" src="https://user-images.githubusercontent.com/1836578/30777451-b06b19d6-a06f-11e7-8a56-510c82e61605.png">

However, the install then doesn't actually work, even though PmagPy and PmagPy/programs are both in my path:

<img width="1108" alt="screen shot 2017-09-23 at 3 46 33 pm" src="https://user-images.githubusercontent.com/1836578/30777735-873f1858-a076-11e7-9611-b987dcf85943.png">

When I try to uninstall and try again, there is a syntax error:

<img width="999" alt="screen shot 2017-09-23 at 2 54 11 pm" src="https://user-images.githubusercontent.com/1836578/30777430-2726bc8e-a06f-11e7-80c4-4fa1eafd5d56.png">

@Caoimhinmg, I am sure you are busy with other things, but is there any way you could look into this or help me get on the right track with it?

**Comment by Caoimhinmg** [comment]
I'll give it a shot on my Windows partition and get back to you, this solution was always a bit of a hack. It seems to have something wrong with the file delimiters going nuts. Might  take me a few days, my Windows partition isn't set up with any python gear.

**Comment by moonshoes87** [comment]
Sorry to ask this -- I've been trying to set up so I can consistently release Windows standalones.  I appreciate your help!  I'm happy to work on this as well, but I might need a little guidance.  Thanks!

**Comment by moonshoes87** [comment]
@Caoimhinmg, have you had a chance to look at this?

**Comment by Caoimhinmg** [comment]
@moonshoes87, I yeah I looked at it a bit. I'm having a little bit of an issue setting up my Windows distribution it's been finicky lately for completely different reasons related to my linux install blowing up (which is why I haven't really replied).

What I did try seemed to work on my distro. The command I'm using to add these files to path permanently, setx, is notoriously tricky and can cause some of the above problems you show if run multiple times without reseting PATH. I thought I accounted for this but I might not have done it properly. Python also has a tendency to replace 1 \ with 2 if you're not careful about DOS paths, and setx only allows your permanent env. variable designation to be 1024 characters long which then throws the error in your third screen capture. So it could be any one or a couple of the above things. I think it most likely is the setx reseting badly because of the multiple slashes which means fixing the \\\\ should do it once you set the PATH back to the default option which you should do manually before rerunning it as the reinstall option is defiantly not working right (should be able to find a commented section with how to do this in dev_setup).

**Comment by moonshoes87** [comment]
Thanks @Caoimhinmg.  I did have success after manually fixing the PATH.  I'll try this again on a clean Windows VM and see what happens.  

Should we remove the windows reinstall option?

**Comment by Caoimhinmg** [comment]
@moonshoes87, no we should keep the reinstall option because it exists particularly for the purpose of avoiding this. If you use reinstall it should restore the old path before trying to install again, the problem should only occur when you install more than once not reinstall. If the reinstall option is buggy that means the uninstall option is buggy and we should address that because we don't want the user to be unable to uninstall.

**Comment by moonshoes87** [comment]
Ok.  Windows :\  Do you want me to work on or test this some more?  Or is there information I can give you that would be helpful for debugging, e.g. do one round of install/uninstall on a fresh VM and see what my PATH looks like before and after?  

I wonder if I somehow installed two or more times in a row without uninstalling, and that is what caused all the trouble?

**Comment by Caoimhinmg** [comment]
I'll give it a shot on my windows partition. Saving the original PATH so I can revert once I have messed it up. Then I'll try to find out what happens when I just install then uninstall then install. I'll test the reinstall feature once install and uninstall work, though to be honest all reinstall does is a clean uninstall and install so it is dependent on the other 2. I'll give a progress update when I can tell you more about what's wrong.

**Comment by moonshoes87** [comment]
Sounds good -- I tried to uninstall/reinstall again just now so I could test the pip installation, and shenanigans followed.  

<img width="1205" alt="screen shot 2017-11-28 at 2 29 10 pm" src="https://user-images.githubusercontent.com/1836578/33347685-934d4042-d448-11e7-827f-e8a12b0ce4ac.png">

**Comment by moonshoes87** [comment]
@Caoimhinmg, did you ever have a chance to look at this further?  I tried again, and had a new issue -- after uninstalling, PmagPy was removed from my PYTHONPATH, but PmagPy and Pmagpy/programs remained in my PATH.

Then reinstalling failed as before.  Let me know if you  have made any progress or will have time to look at this -- if not, I'll have a look at it or at least add a disclaimer to the Cookbook and in the script.

**Comment by yanyongg** [comment]
dev_setup.py doesn't work on my Windows 10.

I have used pmagpy for a long time within comment line. Recently, Dear Lisa came to China and give a lecture, then I reinstall the Pmagy with pip, and it work for several months. Last week, the eqarea.py plotting is frequently get stuck. So I reinstall it follow the developer install instruction, it is good to work.
But after I had a try on the "git pull" to update, embarrassing things happened. All the functions doesn't work.
![6](https://user-images.githubusercontent.com/38656591/48111520-de704a80-e28c-11e8-8bb3-461a5def3f04.png)

I tried to resintall it and the anaconda3 is ok, the dev_setup.py successfully installed, but the functions not really work.
PATH and PYTHONPATH are showed here.
![2](https://user-images.githubusercontent.com/38656591/48111598-3eff8780-e28d-11e8-993b-86e82295b7ca.png)
![3](https://user-images.githubusercontent.com/38656591/48111602-42930e80-e28d-11e8-9260-53b93072bed1.png)
![4](https://user-images.githubusercontent.com/38656591/48111603-44f56880-e28d-11e8-95d0-aba594ca33cb.png)
![5](https://user-images.githubusercontent.com/38656591/48111605-4757c280-e28d-11e8-8fb7-c7203aee6a3a.png)
Who can provided any suggestion on the problem?

Another odd error is that I even can not install pmagpy with pip now.
![1](https://user-images.githubusercontent.com/38656591/48111700-b7664880-e28d-11e8-830c-4254c712daf4.png)

**Comment by moonshoes87** [comment]
@yanyongg, thanks for adding to this issues.  Here are a few things that may help.

`dev_setup.py` does have some significant problems on Windows (@Caoimhinmg, is this something you are able to look into soon?)  However, when you run `git pull` you should *not* need to re-run `dev_setup.py`.  


Here is what you should try:

1.  It looks like you have a misspelling in your path variable: it should be `PYTHONPATH` not `PATHONPATH`.  Try fixing that and restarting your Command Prompt.

2. Based on the error message you sent, it looks like there may have just been a syntax error in the version of pmagpy you got with the `git pull`.  I recommend that you try `git pull` from your `C:\lenovo\PmagPy` directory again after you have fixed the `PYTHONPATH` variable.

And if you want to try installing with `pip` again:

3. First run `pip uninstall pmagpy` and then try to `pip install pmagpy` again.

Please let me know what works and what doesn't!


Also, something to know:

    zeq -h

will call pmagpy as installed by pip.

    zeq.py -h

will call the pmagpy installed directly into your PATH with the developer install.  That is why you are getting two different errors.

**Comment by yanyongg** [comment]
@moonshoes87  good news, it is ok.
First, I fix the spelling error of PYTHONPATH. Restarting the command prompt as well as the PC, it still doesn't work.

Then, I tried uninstall and reinstall with pip, the error is still there.
![1](https://user-images.githubusercontent.com/38656591/48180998-b7834880-e360-11e8-8392-b680689a7112.png)
At last, I delete the file folder of Pmagpy in C:\lenove\PmagPy and re-clone it with "git clone https://github.com/PmagPy/PmagPy.git " to the same place. and run the dev_setup.py with the python.exe position "C:\ProgramData\Anaconda3\python.exe"

Restart the command prompt, it works.
![image](https://user-images.githubusercontent.com/38656591/48181142-4c864180-e361-11e8-9a4a-03a4c69d0f7b.png)

After all,  the spelling error of PYTHONPATH seems the point, shame~
However, the unknown error of pip install is still puzzling. It seems a .png file named with "..._POLE_map_.png" is the trouble maker.

Yes, we should use zeq.py not zeq in developer install. 

All in all. Thank you very much for you kind help !

**Comment by moonshoes87** [comment]
@yanyongg, the problem with the pip install has also been fixed!  The latest version (pmagpy-4.2.8) works correctly now, and you should be able to install without problems.  Please let me know if you run into anything else!

**Comment by moonshoes87** [comment]
It would be great to fix this, but it seems likely to be time-consuming and buggy to do.  If someone wants to do a developer install on Windows, they can follow the [Cookbook instructions](https://earthref.org/PmagPy/cookbook/#setting_path) to do so.
