### ISSUE TITLE
NavigationToolbar error with some versions of wxPython & matplotlib

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#250]
Both analysis GUIs are failing to open on Windows.  I believe this must have something to do with either the latest matplotlib or the latest wxPython, since it didn't happen with my old VM.  

<img width="1108" alt="screen shot 2017-10-03 at 9 23 39 am" src="https://user-images.githubusercontent.com/1836578/31136277-964b1e98-a81c-11e7-8ac6-71008982f698.png">

Edit:  solution is upgrading as follows

    # this will install >= 1.1.0
    conda install basemap --channel conda-forge
    # matplotlib should be upgraded automatically when installing basemap 1.1.0, otherwise
    conda install matplotlib --channel conda-forge
    #  install wxPython 4.0.0b2 or higher
    pip install --upgrade --pre -f https://wxpython.org/Phoenix/snapshot-builds/ wxPython   

See below for discussion and a solution for Linux

**Comment by moonshoes87** [comment]
I tried downgrading to Python 3.5, and then got a different error:

<img width="1108" alt="screen shot 2017-10-03 at 6 06 52 pm" src="https://user-images.githubusercontent.com/1836578/31155802-b6ea51fc-a865-11e7-91c0-b8c25743d5cd.png">

I resolved this error by reinstalling wxPython.  Then I was back to the same error as before.  

I tried to downgrade matplotlib to 1.5, but couldn't:

<img width="1108" alt="screen shot 2017-10-03 at 6 23 28 pm" src="https://user-images.githubusercontent.com/1836578/31156234-0af6f12c-a868-11e7-8365-bcf3adc89689.png">

Then Windows crashed, so I'll have to get back to this later.

**Comment by moonshoes87** [comment]
Tried to install pyqt 4.* and matplotlib 1.5.1 and see if that helps.  The original error persists with downgraded matplotlib.  

Maybe the trouble comes from wxPython-phoenix going from 3.* to 4.*.  Trying to use: https://anaconda.org/newville/wxpython-phoenix 3.* instead of https://wxpython.org/Phoenix/snapshot-builds/ 4.* and see if that fixes it.

**Comment by moonshoes87** [comment]
Somehow in the process of trying to upgrade back to python 3.6 etc. conda was uninstalled.  I can't find a simple way to reinstall it in the same location yet.

**Comment by moonshoes87** [comment]
@Caoimhinmg, do you know anything about the NavigationToolbar module, from when you were doing the Python 2 to Python 3 upgrade?

**Comment by moonshoes87** [comment]
This may be the same issue: https://github.com/wxWidgets/Phoenix/issues/527

**Comment by moonshoes87** [comment]
Looks like this version of wxPython works:

    pip install -U --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython==4.0.0a1

**Comment by moonshoes87** [comment]
I will update the cookbook instructions to install this version, for now.  I believe that this problem will be resolved by a later version of matplotlib that isn't released yet.

**Comment by moonshoes87** [comment]
Installing the latest matplotlib (2.1.0) and the latest wxPython fixes this issue.

**Comment by moonshoes87** [comment]
Canopy doesn't have matplotlib 2.1.0.

Also, conda won't install matplotlib 2.1.0 by default with `conda upgrade matplotlib` -- instead you have to use `conda install matplotlib=2.1.0`

**Comment by Caoimhinmg** [comment]
Hey @moonshoes87, I've been looking into this a bit myself (just realized you had this issue open once you changed the name). It looks like an internal problem though it's defiantly an issue for PmagPy's accessibility. I've got this problem on linux and I managed to fix it by rolling back wxpython to 4.0.0a1 as you suggest above. This is a real shame though as 4.0.0b2 has some major updates particularly for linux as it switches to gtk3 finally and alters all the visuals. It looks way more modern though it needs some fine tuning to make look pretty.

I've tried updating matplotlib as you suggest and it works with the new wxpython 4.0.0b2, but the newest version of matplotlib (2.1.1) on my system doesn't play nice with the latest version of basemap which I need for research and pmagpy uses for some of it's tools. So this is why I am planning on using the older version of wx for now.

Though this whole problem has made me worry about basemap as a project mostly because of [this thread](https://github.com/SciTools/cartopy/issues/920) and because if you look at the [analytics](https://github.com/matplotlib/basemap/graphs/contributors) basemap has seen only around a dozen commits in the last year. This coupled with it's problem with matplotlib in the newest version available through pypi makes me hope that the project will keep up as time goes on. Though perhaps we should consider alternatives like cartopy.

Let me know if you come up with a better solution to this or if this basemap issue exists on mac as well.

**Comment by moonshoes87** [comment]
Yikes, I knew Basemap wasn't that well maintained but I didn't realize it was that bad.  

Well, I finally got everything to work by upgrading as follows:

basemap                   1.1.0            conda-forge
matplotlib                  2.1.1            conda-forge
wxPython                  4.0.0b2  

I don't know what problems you've run into, but with those updates Basemap works correctly without the Python 3 division error that I was seeing with earlier Basemap versions:

    Traceback (most recent call last):
      File "basemap_contour.py", line 20, in <module>
        m2.contour(xx, yy, data, levels)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py", line 521, in with_transform
        return plotfunc(self,x,y,data,*args,**kwargs)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py", line 3542, in contour
        xx = x[x.shape[0]/2,:]
    IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

So this now works:

    plot_magmap.py -el B

    Figure saved as:  igrf2016.0.png

Do you have other issues with the upgraded basemap/matplotlib/wxPython combo?

And yeah, it sounds like we should at least start looking at cartopy (auto-correct wants carroty, haha).

**Comment by Caoimhinmg** [comment]
Well it's possible to get this to work, but it's very sketchy on linux. You cannot get basemap from pypi so it's easiest to install using aptitude (the built-in debian package manager). The version there is 1.0.7 and you get a namespace collision because the matplotlib in aptitude is 1.5.1 and everything falls apart when you update matplotlib using pip because for some reason it installs matplotlib 2.1.1 alongside 1.5.1.

So I found a fix, it's linux specific and if you're using anaconda it shouldn't matter, but no one needs 3 copies of python which is what you'd get if you used anaconda on a ubuntu distribution without a really custom install. So here are the package commands:

```bash
sudo apt-get install python3-mpltoolkits.basemap
sudo -H pip3 install -U matplotlib
sudo dpkg -r --force-depends "python3-matplotlib"
sudo gedit /var/lib/dpkg/status
```

Then find "Package: python3-mpltoolkits.basemap" in the now open text editor and remove python3.matplotlib from the end of the "Depends:" list and save. This is a complete hack but it works, also you're right it seems that basemap 1.0.7+ doesn't have a major issue with matplotlib 2.1.1 unlike matplotlib 2.1.0 so between anaconda and this hack it should work on all systems. Though I'm still a bit worried about basemap's longevity.

**Comment by moonshoes87** [comment]
Messy indeed.  But good to have a fix.  I'm going to leave this issue open, and create a new one for trying out/switching to cartopy.
