### ISSUE TITLE
Demag GUI dropping duplicate rows from MagIC files

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#262]
find out why this error message happens:

    test_click_demag_gui (pmagpy_tests.test_pmag_gui.TestMainFrame3) ...    
    /Users/***/anaconda/lib/python3.6/site-packages/pandas/core/frame.py:881: UserWarning: DataFrame columns are not unique, some columns will be omitted.
      "columns will be omitted.", UserWarning)

Is it a problem with the data file?

**Comment by moonshoes87** [comment]
This issue happens in Demag GUI when a file has multiple rows for the same item.  This can cause problems in MagIC 3.  This line in get_data_info:

    data_er_samples = samp_data2.T.to_dict()

is the problem.  Unlike a dataframe index, a dictionary can't have non-unique keys, so data is lost.

For example, when this abridged samples table is turned into a dictionary:

          azimuth
    sample              
    hz05a      240 
    hz05a     
    hz05b      190 
    hz05b     

It could look like:

    {'hz05a': {'azimuth': ''},
     'hz05b': {'azimuth': ''}

or:

    {'hz05a': {'azimuth': 240},
     'hz05b': {'azimuth': 190}}

There is no way to predict which.

One solution would be to propagate certain columns values in each table (whatever is important for Demag GUI, like orientation headers in the samples table).  This could definitely slow things down, though, especially with large tables.  


   samples.front_and_backfill(['azimuth'])

            azimuth
    sample         
    hz05a     240.0
    hz05a     240.0
    hz05b     190.0
    hz05b     190.0

Then it won't matter which row gets turned into a dictionary, at least with respect to azimuth.  We could choose a list of important columns, and make sure the values in those columns are applied to every row.

Alternately, we could try dropping non-important rows, possibly by method code, before turning the DataFrame into a dictionary.

Demag GUI people, any thoughts on this?  @Swanson-Hysell, @Caoimhinmg, @ltauxe?

**Comment by Caoimhinmg** [comment]
Hey @moonshoes87, I've tried mitigating this by making it so that there is less need to have more than one record for any single specimen, sample, or site (simply propagating intensity/geologic/directional data all into one line which is not always perfect). To this end I call drop_duplicates on some of the exports so the output looks more like what Demag GUI actually uses. I also often use DataFrame.to_dict('records') which makes a list of dictionaries which has the nice property of not requiring a unique index because indices are all numbers. Though due to backwards compatibility with the old MagIC format and the nature of Demag GUI's backend this is not always possible. If I could see the exact data I could possibly diagnose or fix this better.

**Comment by moonshoes87** [comment]
An example of this problem is in data_files/Pmag_GUI/3_0/.  (Ron Shaar's Tel Hazor/Tel Megiddo study).  

Demag GUI must have a strategy for reading in files like this, since they are to be expected in MagIC 3 and a user may or may not have used a PmagPy conversion script.  Maybe there is a relatively simple way to decide which of the two rows for each sample is more relevant for Demag GUI, either by using a method code or checking for a filled in field?

Alternatively, we could switch to using `DataFrame.to_dict('records')` in these cases.  This would require some refactoring of the Demag GUI code, so that data_er_samples/data_er_sites/etc.  are formatted as lists of dicts instead of dicts of dicts.  This might require some significant digging, though, and it would be easy break things along the way.

**Comment by Caoimhinmg** [comment]
Hey @moonshoes87 I don't think it's a matter reading in data that is the problem here when it reads in it just tosses the intensity data to the side so it doesn't fall apart same as it's always worked. It's the writing out when the analysis is done and this is a problem I've struggled with for a while.

I had originally assumed that the idea with Magic 3 was to have a simple yet extensive set of vocab so you would only need one line for a single magnetic component in the specimens table and one measurement record per actual physical measurement in the measurement table; so I built Demag GUI with this in mind. So it does collapse the rows trying to merge them in a sensible manner to simplify the table. I think this vision was different from the intended one, and it makes a lot of sense to keep the intensity or IRM data on a seperate line from the directional analyses, however, I have yet to go into the code and specifically figure out an alternate method.

This is mostly because Demag GUI has magnetic components which are a level bellow specimens but as they don't have their own table they have the same index in the specimens, samples, and locations tables and can be a huge headache. This is because it is hard to decide if a row should be kept or not as any combination of database merging techniques won't work if I need to potentially remove rows from both of the merging databases and keep some rows while merging some columns it's too selective and would required a extensive hard coded vocabulary. I could do an iterative process with a thousand hard coded checks but it starts to take real human time when I do as pandas is not made for that and when Demag GUI can have 3+ components per 1000+ specimens, 100+ sites, some locations that's a lot of iteration (this was my first try about a year and a half ago). As every save from Demag GUI has the potential to add rows to the tables and remove them a systematic method for handling this has to be developed. The one I made was to simplify and merge and just have every record hold as much data as it could then I could just worry about magnetic components and not lose anisotropy or intensity data. It's not perfect but it worked for pure directional data and preserved data in mixed datasets so nothing was lost though it looks strange in the table.

This problem mostly exists if you try to do directional analysis in Demag GUI on a mixed information dataset (directional and intensity or anisotropy, etc) which is why I don't think we've heard much complaint about it. Though to this day I'm not sure how to make it any better. If you can think of a good solution to this I'd be happy to implement it or perhaps a method that can be added to the Contribution object to handle merging directional data into mixed data tables?

Sorry for the monologue I'm just getting back into the code and remembering some past frustrations and what still needs to be done and I just kinda got on a roll. Also this problem has peeved me for some time as I have never been happy with my solution to it.

**Comment by moonshoes87** [comment]
Yes, it is a little messy with how potentially heterogenous the data can be.  I haven't noticed specific problems at the measurement/specimen level, but it sounds like there is potential for trouble.  I don't really have a solution to the mixed data issue.  I have added a few methods to MagicDataFrame to help get rid of potentially unneeded rows that may have gotten added:

    drop_stub_rows  # drops rows that are entirely null, ignoring specified columns

    drop_duplicate_rows # same as drop_stub_rows except only drops rows that have a duplicated index

So in this data:


              citations        dip
    mc01     This study        10
    mc01     This study
    mc02     This study
    mc03     This study        8


This line:

    df.drop_stub_rows(ignore_cols=['citations'])

would drop the second and third rows, since both rows are blank except for an ignored column.

    df.drop_duplicate_rows(ignore_cols=['citations'])

would drop the second row only, since even though the row for mc02 is blank except for citations, there is no other row with the index mc02.

This can be helpful for cleaning up output, at least. 

But there also *is* a problem with reading in higher level data.  At the sample level, geographic data that is used by Demag GUI (azimuth, dip, etc.) may or may not be kept depending on which values the to_dict method grabs.  You can see my second comment on this issue.

For example, you won't be able to check orientation if azimuth and dip are missing, which they could be if to_dict() drops them even if they were present in the sample data file.  Like I've said, I do have a fix for this, but it is somewhat slow, depending on the size of the dataset.  Do you think it's worth it?  I don't have a different solution that doesn't involve rewriting Demag GUI to use a different data structure.

**Comment by moonshoes87** [comment]
This still concerns me, because we can lose orientation data depending on where it is put in the data file.  But, I'm not the person to fix this.  I've closed this, but we can revisit in the future if someone who is more involved with Demag GUI wants to.
