### ISSUE TITLE
add functionality to Demag GUI for averaging multiple measurements

### ISSUE THREAD

**Issue by lfairchild** [PmagPy/PmagPy#328]
Currently, the only option for averaging multiple measurements at the same treatment step appears during the initial conversion of magnetometer files to MagIC format. Even then, the conversion scripts are pretty inflexible as they require you to make the choice between importing everything and averaging for *all* replicate measurements in the dataset. 

It would be great if Demag GUI provided the option to selectively average "good" replicate measurements for each sample in addition to the "bad measurement" flags already available. It seems that implementing this in the GUI could be tricky though. @Caoimhinmg what do you think?

**Comment by Caoimhinmg** [comment]
@lfairchild this would not be a trivial thing...Demag GUI is very much set up so that modifying the measurements file is not done beyond writing a b or g in quality. I'd either need to hack this in with a custom session file keeping track of what to average (of course then this wouldn't get published in MagIC) which I'm reluctant to do. Alternatively something would need to be added to the vocabulary to indicate to Demag GUI that 2 measurements should be averaged, unless we want to remove lines from the measurements file which is less than ideal as you cannot unaverage a measurement if the user changes their mind. @njarboe, @rminnett what do you think about the vocabulary thing? This might be a good addition as it could modify how the current importing scripts are handling averages which is by only reporting the average measurement, which involves a loss of information as explained above.

**Comment by moonshoes87** [comment]
@lfairchild and @Caoimhinmg, let me know if I should leave this issue open, since it has not been touched in over a year.

**Comment by moonshoes87** [comment]
I'm closing this issue.  If someone wants to work on it, go ahead and reopen.
