### ISSUE TITLE
Thellier GUI: confusion about site/sample level when averaging by sample in Save MagIC Tables

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#335]
Following the Pmag GUI tutorial instructions, something weird is happening in Thellier GUI save magic tables.  It looks like sample names are showing up in the site column.  I'm not sure why/how this is happening.  

<img width="1088" alt="screen shot 2018-04-15 at 12 54 23 pm" src="https://user-images.githubusercontent.com/1836578/38782690-2d0b2bfc-40ac-11e8-8577-f5959e74b001.png">

@ltauxe, do you have any ideas?  If not, I will look into it.

**Comment by moonshoes87** [comment]
Oh, or maybe this is correct?  Since we are averaging by sample, the sample data gets moved up into the sites table?

**Comment by ltauxe** [comment]
Yes.  if averaging by sample, sample=site (by our MagIG definiation)
and if averaging by site, one would average by sample first.  it is confusing because the “site” is what you average over.  the sample is only relavant for oriented ones (in my opinion).  
2 different scenarios:  
1) a lava flow (site) with multiple oriented cores (samples) that have been chopped into multiple slices to measure (specimens).   If we are after a direction and orientation is the key source of uncertainty, then we would average multiple specimens by sample, then by site.  this is what most paleomagnetists do.  
2) we have a bunch of pot sherds from an archaeological level.  one might have initatially designated each level a “site” but the only thing we are really  sure got cooled under the same conditions are pieces from the same pot.  the pieces would be ‘samples’. if they can be tied together into a single pot, then the pot would be the “site”. but mostly we just get individual sherds that are unrelated.  here we average intensities by ‘sample” (sherd) and that is actually the ‘site’ by MagIC definitions.  At anyrate, the sample averages belong at the site level here.  site info entered as above must be preserved however. Ideally, if the samples were originally grouped into ‘sites’ but these are no longer appropriate because the ‘site’ mixed up things of different ages, then new site names must be invented that have all the metadata from the old site (geospatial info like lat/long/square/level/inferred age, etc.).  
Ron?

**Comment by moonshoes87** [comment]
I am closing this discussion of site/sample level averaging for archaeomag, since it hasn't been touched in about 2 years.
