### ISSUE TITLE
Pmag GUI tutorial: Thellier GUI adding invalid columns to sites table

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#339]
thellier_gui is inserting weird stuff into the site table which then messes up the upload process.  
The  before is sites_bak.txt
[sites_bak.txt](https://github.com/PmagPy/PmagPy/files/1917736/sites_bak.txt)
and the after (sites.txt)
[sites.txt](https://github.com/PmagPy/PmagPy/files/1917738/sites.txt)

This happens when we save MagIC tables from thellier_gui
also, thellier_gui is creating the phantom pmag_criteria.txt file when it saves MagIC tables. 

 finally:  demag_gui is putting in criteria (“ACCEPT”) into the sites  table where none were applied.  

I'm working with a few eager Chinese students (about 50 in all) to get them to use Pmag GUI and the magic data base.  If these few remaining issues could be addressed, that would make things go a lot smoother here.  :)

**Comment by moonshoes87** [comment]
I can't reproduce the Demag GUI ACCEPT bug.  I can't work out what steps you are doing differently.

I *can* reproduce the issue where Thellier GUI adds a bunch of columns from the samples table into the sites table, however those columns are all removed by upload_magic and then don't cause a problem when I upload.  I want to get to the bottom of where these extra columns are coming from, but if they're removed in the upload are they a problem right now?

Same with the phantom pmag_criteria file.

**Comment by ltauxe** [comment]
well, they aren’t being removed when I do it.  just ignored then caught by the MagIC website.  I think the upload_magic thing is putting them in. 
lisa

**Comment by moonshoes87** [comment]
can you send me or attach a zipfile of the entire directory before you run the upload_magic step?

**Comment by ltauxe** [comment]
so.. thellier_gui is adding a bunch of specimen level stuff to the sites table (see attached).  and then upload_magic puts it back in somehow if you trake it out.  
‘

**Comment by moonshoes87** [comment]
There's no attachment...

**Comment by moonshoes87** [comment]
It looks like this happens because we are averaging by sample, so sample records are being moved up into the sites table with all of their data.  You can see this in thellier_gui.py around line 4307.

So, this behavior is basically correct, but we should remove all invalid columns before writing back to file.  The only problem I see is that Thellier GUI uses a few non MagIC column names (we just take them out in RmKeys in upload_magic).  So, we need to make sure we remove non-site columns except for any Thellier GUI specific internal columns.

@ltauxe, does this seem right to you?

**Comment by moonshoes87** [comment]
This are the columns that will be removed (at least for the tutorial) with this fix:  azimuth_dec_correction texture site_definition dip timestamp sample_alternatives azimuth orientation_quality num cooling_rate_corr cooling_rate_mcd.

Should any of those be kept?

**Comment by ltauxe** [comment]
Yes that makes sense. One other thing is that geological info is not being
propagated to all tables where required- if that could happen, say in step
3, that would save steps for uploaders

**Comment by moonshoes87** [comment]
Great.  Which geological info is missing?  

During step 3, here are the current propagations that happen.  Lithology, type, and class propagate down from sites --> samples --> specimens.  Ages propagate down from ages --> all other tables.  Age also propagates up from sites --> locations.  Lat/lon propagate up from sites --> locations.  Lat/lon/height propagate up from samples --> sites. 

Anything else you want to happen?

**Comment by moonshoes87** [comment]
For step 2/orientation_magic, I think that what happens is that orientation_magic overwrites method_codes that are provided in the demag_orient grid in favor of method_codes that are provided in Calculate Sample Orientations.  Should I remove the method_codes column in the step 2 editable grid?  

<img width="593" alt="screen shot 2018-04-19 at 5 03 15 pm" src="https://user-images.githubusercontent.com/1836578/39024119-978846c8-43f3-11e8-8a50-cd7fdcb8b5a4.png">


For step 3, if you skip lithology/type/class at the specimen and sample level, then fill it in at the site level, it will automatically propagate down to samples and specimens.  So in general you don’t need to fill those columns in at the specimen and sample level.  I do make a note of this in the Cookbook tutorial, but I can see how you could miss that.  It's also in the "Help":

<img width="687" alt="screen shot 2018-04-19 at 5 01 06 pm" src="https://user-images.githubusercontent.com/1836578/39024079-67d614e6-43f3-11e8-83ab-1bae8de37379.png">


Other options: I could hide those columns at the sample/specimen level in Pmag GUI step 3.  Or, I could re-order the grids in step 3 so that sites comes first.  What do you think?

**Comment by ltauxe** [comment]
Yes take out the method codes from step 2 - it is redundant and yes I
missed the tip about the site level geology propagation- thanks
