### ISSUE TITLE
demag_gui debug message being thrown

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#34]
```
Debug: Unknown accel modifier: 'x'
```

get rid of pdb import too.

**Comment by Caoimhinmg** [comment]
this error is actually caused by hotkey differences in the menu between mac and pc it appears hotkeys that include more than one letter or number are invalid on mac and throw the error that there is no such accelerator. I am however leaving the pdb import as I remembered as I went over the code again that I added a user callable debugger to the help menu (hotkey ctrl(command for mac)-shift-d) this will open a pdb debugger which is extremely helpful for diagnosing problems and while this program is so heavily under development I think this feature should stay.
