### ISSUE TITLE
specimen in measurement table removed from specimens table by thellier_gui and other bugs

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#340]
when importing SrExample_thellier.txt to magic, an entry is made in SrExample_specimens.txt
It stays there through the demag_gui interpretations but  gets mysteriously removed by later events, apparently in the thellier_gui save MagIC tables step.    
this of course means that measurements.txt has a specimen that is not in the specimens.txt table and upload_magic will throw an error.  
I think this only happens when there is no interpretation for s01i.

**Comment by ltauxe** [comment]
upload_magic is also putting ACCEPT in the sites.txt file when there is no criteria file, then complaining about it.  If there are no acceptance criteria, then this column should be blank and upload_gui shouldn't worry about it.

**Comment by ltauxe** [comment]
And thellier_gui seems to put IE-SAMP in the samples table when there is no IE-SAMP in the criteria table.  then upload_magic gets upset.

**Comment by ltauxe** [comment]
AND:  thellier_gui is still writing out int_sigma and int_sigma_perc in the samples table, while these are now int_abs_sigma and int_abs_sigma_perc.  this sounds like the mapping module needs updating...

**Comment by moonshoes87** [comment]
I'll try to figure out the deleted specimen issue.

I don't get the int_sigma issue.  I'm getting int_abs_sigma and int_abs_sigma_perc, not int_sigma and int_sigma_perc.   Is it possible that you are somehow getting and older version of PmagPy?  Maybe you pip installed at some point?  

Here is the samples file that I get from following the tutorial:
[samples.txt](https://github.com/PmagPy/PmagPy/files/1917959/samples.txt)

**Comment by moonshoes87** [comment]
Around line: L3845 in thellier GUI in  on_menu_prepare_magic_results_tables,

                    # delete essentially blank records                                                              
                    condition = self.spec_data['method_codes'].isnull().astype(                                     
                        bool)  # find the blank records                                                             
                    info_str = "specimen rows with blank method codes"                                              
                    self.spec_data = self.spec_container.delete_rows(                                               
                        condition, info_str)  # delete them  

Removing these lines seems to prevent sr01i from being deleted.  I don't remember exactly why these lines were added, but they can be removed.  

If I remove the above section of code, here is the upload file that I get after running Pmag GUI steps 1-3, Thellier GUI interpretations and Save MagIC tables, Demag GUI interpretations and Save MagIC tables:

[Snake-River_16.Apr.2018_2.txt](https://github.com/PmagPy/PmagPy/files/1918033/Snake-River_16.Apr.2018_2.txt)

[ThisProject.zip](https://github.com/PmagPy/PmagPy/files/1918030/ThisProject.zip)

The only problem with it is the IE-SPEC/IE-SAMP is added to the sites table even though there is no criteria file.  Even so, this file can be uploaded to MagIC just fine (except for the final part of the upload step: https://github.com/earthref/MagIC/issues/338)

@ltauxe, do you want me to comment out these lines and push that change?

**Comment by moonshoes87** [comment]
I think I didn't find the specimen deletion issue initially because I was doing Demag GUI first then Thellier GUI, so those specimens got method codes added by Demag GUI and didn't get deleted.  Anyway, I will remove those lines above, since I am now confident that they are not producing a desired behavior.

**Comment by ltauxe** [comment]
oh yes.  i think they were added to get rid of zombie lines, but it shouldn’t delete things just because no method_codes.  yes please comment them out.

**Comment by ltauxe** [comment]
thanks that worked.  but now there is these  annoying bugs:  

thellier_gui is putting in criteria names  in the samples and sites tables when none have been set and there is no criteria file.  this should be blank

demag gui is putting in ACCEPT under criteria in the sites table even though nothing is set.  this should be blank

and the upload step fails where there are no criteria listed in the sites table.   You shouldn't HAVE to have criteria....   
[sites_errors.txt](https://github.com/PmagPy/PmagPy/files/1918151/sites_errors.txt)
[sites.txt](https://github.com/PmagPy/PmagPy/files/1918152/sites.txt)

**Comment by moonshoes87** [comment]
You can still upload even if some validations in Pmag GUI fail.  Even if some validations fail, should still generate an upload file.

That criteria validation comes from the data model.  




I don’t know how Rupert handles this on the database side.  I can make a global change to how the PmagPy validations are done so that Found In validations are ignored if the table is missing.  Does that seem like the right approach?  This will result in relaxed validations on other columns as well...

I still can’t generate the demag GUI ACCEPT bug.  When I run Demag GUI on the Pmag GUI tutorial dataset, I end up with no criteria column at all.  I only get a criteria column if I run thellier gui, and then the only values I get are IE-SPEC/IE-SAMP.  I have no idea what the difference is.  In Demag GUI, I just select temperature bounds for each specimen, then save magic tables without changing any of the defaults.

Try running Demag GUI in this directory:



It will help if you can figure out the exact steps that create those ‘ACCEPT’ values.

**Comment by moonshoes87** [comment]
I'm closing this issue since this specimen deletion problem has  been solved.  The Demag GUI "ACCEPT" issue can be tracked in #336
