### ISSUE TITLE
demag gui site mean option

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#349]
I can set the display level to "site" and the Mean Options to Fisher and Fit 1, but I have to do this for EVERY SPECIMEN.  Is there a way to keep these settings through out the session?  And better yet, set these as the defaults?

**Comment by moonshoes87** [comment]
It looks like if you choose "All" or "None" everything stays set, but if you choose Fit 1 then everything is reset when you go to the next specimen.  

Maybe this is based on the expectation that the fits will have custom names that won't stay consistent?  @Caoimhinmg, do you have thoughts on this?  Otherwise, I may see if I can get the Mean Options to behave more consistently.

**Comment by Caoimhinmg** [comment]
@moonshoes87, Interesting we both decided to look at this at the same time. Anyway it is partially me erasing the information when you switch specimens because I cannot be sure the same fits are around between any 2 specimens. Ideally it wouldn't default to None though, it should pick the fit at the same index as the one in the previous specimen or lacking that the first fit it can find. I'll see what I can do.
