### ISSUE TITLE
reorganization broke pmag_basic_dialogs.py imports for file format programs

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#36]
```
Traceback (most recent call last):
  File "/Users/Laurentia/PmagPy/dialogs/pmag_basic_dialogs.py", line 1017, in on_okButton
    import CIT_magic
ImportError: No module named CIT_magic
```

**Comment by moonshoes87** [comment]
Oops.  I’ll fix this shortly.

**Comment by Caoimhinmg** [comment]
I already fixed it quick "kinda" so I could convert some files. My fix is a bit of a patch though, instead of changing the imports to "from programs import ......" I just added ../programs/ to PYTHONPATH temporarily at the start of the file so that any time someone runs it it changes their PYTHONPATH for the duration of that instance of python.

**Comment by moonshoes87** [comment]
I made the export explicit (and correct) in the dialogs file.
