### ISSUE TITLE
chi_magic.py update to MagIC 3

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#365]
this program is still in data model 2 only.  needs upgrading to data model 3 and while we're at it, should go into ipmag as a notebook friendly version.

**Comment by ltauxe** [comment]
I made a notebook version in PmagPy_nb that works well.  maybe we should just move chi_magic.py to chi_magic2.py and use the version in PmagPy_nb  as a start for chi_magic.py which would be data_model 3 only.

**Comment by moonshoes87** [comment]
Sounds good.  Do you want me to put this on my list, or do you want to do it?

**Comment by ltauxe** [comment]
not urgent.  maybe i will get to it eventually. it works in _PmagPy_nb

**Comment by moonshoes87** [comment]
I've basically finished with upgrading chi_magic, although it is a little bit simplified from how it worked in 2.5.  There isn't interactive entry anymore, and it only generates two plots instead of 3 (I just adapted what you have in the notebook instead of upgrading chi_magic2 directly).  Have a test if you want, I can add more to it asap or we can also flesh this out later if it isn't a high priority.

**Comment by ltauxe** [comment]
thanks lori - this is not top priority.  
lisa
