### ISSUE TITLE
hysteresis_magic.py versus ipmag.hysteresis_magic

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#377]
the command line version works fine for data model 3, but the ipmag version has diverged somewhat and fails for cases in which specimens.txt is not present.  This should work just like the command line version - can these be reconciled?

**Comment by moonshoes87** [comment]
I'll check it out.

**Comment by moonshoes87** [comment]
This is exactly the frustrating place we are in with pmagplotlib and the tkinter backend.  With how pmagplotlib is written, it's hard to share plotting code that works in both the command line and in the notebooks.  So then we get these divergences and potentially have to make fixes in both places.

Second -- after starting to dig into this, I'm not convinced that ipmag.hysteresis_magic *ever* worked.  Fundamentally, this probably should be rewritten like aniso_magic, or, again, we have to rewrite pmagplotlib.  I think rewriting pmagplotlib will be less work in the long run, but it will be totally annoying right now.  

Either way, getting ipmag.hysteresis_magic to work doesn't really make sense, because it uses a bunch of pmagplotlib pieces that don't work well in the notebook.  For notebook use, we can still call hysteresis_magic command-line style.

**Comment by moonshoes87** [comment]
one other thing -- some of the problems were hidden in a general try/except block that was silently catching lots of different errors than it was expecting.  We should try to eliminate that syntax from the code wherever possible -- try/except should always be looking for specific error types.

**Comment by ltauxe** [comment]
no i think it never did.  so.. I have a pretty neat work around in _PmagPy_nb   take a look. 
if you like it, we can just close this and eliminate ipmag.hystersis_magic
lisa

**Comment by moonshoes87** [comment]
the dmag magic functionality looks very straightforward in the notebook.  For it to be totally smooth with varying contributions, we'll want to add in a few kinds of checks.  1., that the expected tables are present, and 2. that the expected column names are present.  I've often been burned by issues like that as contributions are so varied and sometimes are missing even required columns.  

How about if we use the template of dmag_magic to create a more general function that does the importing, merging, and fishing out of the relevant data for plotting by site?  This function could take as input the relevant method codes and the relevant column names, and then return appropriately trimmed down measurement data with merged in sample/site names for plotting.  (Or it would return appropriate warnings, that, for example, you're missing a samples table).  That would be a nice way to reuse that code cleanly and maintainably.

**Comment by ltauxe** [comment]
Great idea - it can be in pmag.py I guess

**Comment by moonshoes87** [comment]
Ok, I can do that.  hopefully this will simplify things a bit.

**Comment by moonshoes87** [comment]
I want to minimize as much as possible us cutting and pasting code and then having big maintenance to do!

**Comment by moonshoes87** [comment]
ipmag.hysteresis_magic has now been deleted.
