### ISSUE TITLE
measurements_methods3

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#397]
does not put in the required column "sequence".  It should.

**Comment by ltauxe** [comment]
Ok.  I just made sequence= treat_step_num which doesn't seem to be in Datamodel 3 anymore.

**Comment by moonshoes87** [comment]
treat_step_num is still in Data model 3:

![screen shot 2018-07-24 at 9 58 09 am](https://user-images.githubusercontent.com/1836578/43154127-1f0b3eb4-8f28-11e8-8055-42ad71e9b55e.png)

Also, isn't measurements.treat_step_num reset with each new specimen?  vs. measurements.sequence should go from 0( or 1) - n for each line in the file?

**Comment by ltauxe** [comment]
ah.  ok.  whatever.  sequence seems a bit arbitrary then and I think it shouldn’t be required.  
lisa

**Comment by moonshoes87** [comment]
I believe that sequence is so that the measurement file line order doesn't have to be preserved.  I think, also, @rminnet was planning to add it automatically if it is missing from a contribution.  

@ltauxe, I could relax that validation for PmagPy?  Or we could just add it in measurements_methods distinct from treat_step_num?

**Comment by ltauxe** [comment]
I fixed it in pmag.measurements_methods3
