### ISSUE TITLE
make_magic_plots.py log and error outputs

### ISSUE THREAD

**Issue by rminnett** [PmagPy/PmagPy#410]
@moonshoes87, @njarboe: Here are a few thoughts I had about the specs for adding reporting to make_magic_plots.py after the meeting today:

- Don't worry about trying to make an output txt file for every plot that didn't get made since that requires knowledge of all of the plots that are capable of being made with a contribution.

- _errors.txt_, _warnings.txt_, _log.txt_ should use the same format as long as multi-line entries are delimited and each entry has a UTC timestamp (possibly UTF-8 encoded text from the Python logging package?).

- _errors.txt_ should only be present in the current working directory after make_magic_plots.py runs if there was an exception or a plot failed to be made even though it appeared the requisite data were present.

- _warnings.txt_ should have entries if make_magic_plots.py didn't generate a plot because a column was missing (i.e. _sites.txt_ has directional data but no equal area plot was made; e.g. http://34.236.167.37/plots/16350/) or a method code wasn't present (if and when it's possible to detect this).

- _log.txt_ should just have info level messages about when make_magic_plots.py started and stopped in the current working directory and what command line programs and arguments were executed.

- If errors.txt or warnings.txt are present in the current working directory, delete them and start a new warnings.txt file with a warning entry that they were deleted from the previous run in case the user isn't aware that this is happening. _log.txt_ should just get appended to until it's manually deleted or renamed.

Just a few ideas to get a discussion started. Feel free to make better suggestions. :)

**Comment by moonshoes87** [comment]
@ltauxe, can I remove the logic for navigating Location_* directories in make\_magic\_plots.py, or do you think that will still be useful?  By default, ipmag.download_magic no longer splits a contribution out into separate directories, but that functionality is still available.  

I suspect that we don't need to support plotting by Location_* directories anymore in make_magic_plots, unless you think it is still useful.

**Comment by ltauxe** [comment]
by all means

**Comment by moonshoes87** [comment]
Right now make_magic_plots runs eqarea_magic for sites only.  If there is dir_dec/dir_inc at the measurement level, should equal area plots be created?  For instance: 
https://earthref.org/MagIC/16426

**Comment by ltauxe** [comment]
if we did that it would be specimen by specimen (as these are unoriented data) and would complement the zijderveld and arai plots. 
lisa

**Comment by moonshoes87** [comment]
Ok, I've added this specimen by specimen equal area plots.  We can take them out again if they aren't helpful.  

The plotting of intensity histograms has gotten messed up somehow:

McMurdo:
![lo _mcmurdo_ty _intensities_histogram _](https://user-images.githubusercontent.com/1836578/44162981-ce264600-a076-11e8-996b-7c1eeba40566.png)

contribution 11875:
![lo _iceland_ty _intensities_histogram _](https://user-images.githubusercontent.com/1836578/44161336-e051b580-a071-11e8-80e1-607ff7c3feb3.png)

I fixed it so that McMurdo looks better now:

![lo _mcmurdo_ty _intensities_histogram _](https://user-images.githubusercontent.com/1836578/44169670-02573200-a08a-11e8-834a-d9fbf2a3fe87.png)

but the Iceland plot still doesn't look great:

![lo _iceland_ty _intensities_histogram _](https://user-images.githubusercontent.com/1836578/44169713-274ba500-a08a-11e8-8062-5cf0b6398b12.png)

Maybe we need to mess with the bin size?  Or not plot datasets with so few intensity values?

Also, the frequency scale labeling doesn't seem right.

**Comment by moonshoes87** [comment]
@njarboe, I've started a new branch for working on make_magic_plots and error logging (error_logging).  I've implemented some logging, as well as made a few fixes along the way.

If you could try it out on the server, that would be helpful to me.  The program now produces up to two log files.  log.txt lists each PmagPy program that is run, along with a timestamp and location.  errors.txt contains warnings for known issues -- for instance, if you have the LP-HYS method code but no treat_temp column, you can't plot with quick_hyst.  

If you (or @rminnet) can point me towards more contributions that seems to be missing plots or having other problems, that would be great.  This will help me identify more possible issues.

**Comment by moonshoes87** [comment]
@rminnett, quite a few of the problems I am running into relate to invalid/incomplete contributions.  For example, in https://earthref.org/MagIC/11943, location name is present, but doesn't match the name in sites.txt.  Since I need to sort by location to plot, this causes problems.

I am trying to figure out if I should be building in safeguards and workarounds for this kind of thing, or if it will be moot once database validations are fully up and running.  Do you have any input on this?

**Comment by rminnett** [comment]
Ah, that makes sense. I'm working on running the validation rules against all of the existing contributions. Sometime next week I should be able to give you a list of all of the contributions with validation issues so you can avoid dealing with them.

Ideally, plotting should still do what it can with an incomplete contribution since it's very useful to start getting that visual feedback in the private workspace even if a contribution might not pass validation yet.  If you come across a contribution that is invalid, it's completely reasonable that it failed to plot and I wouldn't spend time generating nice plotting error messages because of validation issues, but it would be good to just double check that it did plot anything that it could.

**Comment by moonshoes87** [comment]
@rminnett, I think what I will do if the hierarchy is incomplete/incorrect is simply plot the entire contribution as if it were all one location.  That should be straightforward enough to implement.

**Comment by moonshoes87** [comment]
@rminnett, how about specimen/sample/site names with quotes in them?  For instance, contribution 16305 has a totally bonkers mix of quotation marks in names, I presume from cutting and pasting in some irregular way, which also messes up the hierarchy.  Is that something you will be fixing?

**Comment by moonshoes87** [comment]
note to self: currently works by a combination of reading in tmp\_\*.txt files and using dataframes.  Eventually we will fully switch to using the dataframes only.  For now, the logic is complicated and redundant since we're doing both.

**Comment by rminnett** [comment]
Yes, I see the quotes in 16305 - technically any non-tab characters should be allowed within the text columns of a table (we haven't considered escaping tabs in a tab-delimited MagIC text file, perhaps with quotes like in a CSV, but I don't think it's necessary).

Although those probably aren't intentional (maybe the web validation should produce a warning for this, but not an error), as long as the quotes are used consistently so that, for example, a site refers to a location that exists, this should be allowed (as should other non-alphanumeric characters like diacritics and hyphens, parentheses, etc.). This is a good case when an image table is better than plot file names that use try to use approximations of location, site, etc. names.

**Comment by moonshoes87** [comment]
In this case the quotes do seem to break the hierarchy.  I agree that this should generate a validation warning, not an error.  Make_magic_plots will handle this by plotting as if the entire contribution is one location.  

I also agree that an images table will be a better way of tracking the plots.  That will be part of round 2 of refactoring -- I want to redo the plotting programs so that I can pass the data in directly, instead of reading in the file.  This will have a side benefit of make_magic_plots running faster, and will make it more straightforward to create an images table.  (I'm adding this as a separate issue, #424)

Another contribution, 16410, has an extra descriptive header line in the sites table:

    tab delimited   sites
    site    location    lithologies lat lon elevation   dir_tilt_correction dir_dec dir_inc dir_alpha95 dir_r   dir_k   dir_n_samples   vgp_lat vgp_lon
    Site    Locality    Lithology   Latitude    Longitude   Elev (m)    Direction Tilt Correction   Dec Inc a95 R   K   N   VGP Lat VGP Lon

I think contributions like this are just going to throw errors -- it seems impractical to me to try and catch all deviations of this nature.  I could put in a lot of logic around these specific issues as I find them, but ideally I would rather leave that to your validations, @rminnett.  If anyone has other suggestions about how to handle this, let me know.

@njarboe, when you have time to do so, it would be great if you could check out the new make_magic_plots (currently on the error_logging branch).  It should be trying to generate more plots now, and because of that it may run into some new errors.  I've worked through ~10 contributions and I am getting good success with those, including useful error messages when certain plots can't be generated.  You can also ids of any contributions that don't seem to be creating plots you expect.

**Comment by njarboe** [comment]
@moonshoes87 I've pulled the latest version onto the plot server and checked out the error_logging branch. I'll run it on the 3.0 contributions (less the two huge ones) over the weekend and can take a look for possible problems next week.

Without validation being in place since the new system went online, I'm sure there are some very ugly formatted contributions that are now in the system. You don't need to deal with every bad case, but having plots with incomplete contributions would be useful for people looking at their data before it is complete.

**Comment by moonshoes87** [comment]
@njarboe, thanks for running these.  I've now merged the changes over into master, since I discovered and fixed some bugs in the process of working through make\_magic\_plots.  If you run through the contributions again, you can use master.

**Comment by njarboe** [comment]
@moonshoes87 Thanks Lori, I'll pull from master in the future for updates to make_magic_plots. 
 
Here are a couple of comments/suggestions/bug reports. @moonshoes87 Would you like me to make a new issue for each future bug/improvement suggestion for make_magic_plots to better keep track of them?

1) It would be nice if the errors were also sent to stderr. One can see them right away on the screen and also, if one is running the plotting on multiple files, one can see the errors all in one place by redirect all errors to one file. For example when running make_magic_plots on all of the old files I used to have one error file to look at to see which files had problems. Now I would have to look at every file directory to see if there was a problem. 

2) If it is a simple fix, would you also add the MagIC data file to the error message. That would also be helpful when running multiple files.

3) dir_tilt_correction is not a required field. If it is missing, default to 0 (ie, no tilt correction). This file:
[magic_contribution_16462.txt](https://github.com/PmagPy/PmagPy/files/2307484/magic_contribution_16462.txt)

produces these errors:
2018-08-19 11:04:01.264158	Eastern Sheep Creek	eqarea_magic.py	Directional data found, but 
missing dir_tilt_correction, can't plot directions
2018-08-19 11:04:01.264245	Eastern Sheep Creek	equarea_magic.py	28 dec/inc pairs fou
nd, but no equal area plots were made
2018-08-19 11:04:01.303456	Western Sheep Creek	eqarea_magic.py	Directional data found, but 
missing dir_tilt_correction, can't plot directions
2018-08-19 11:04:01.303530	Western Sheep Creek	equarea_magic.py	23 dec/inc pairs fou
nd, but no equal area plots were made
2018-08-19 11:04:01.339088	Valmy Contact Sheep Creek	eqarea_magic.py	Directional data fou
nd, but missing dir_tilt_correction, can't plot directions
2018-08-19 11:04:01.339162	Valmy Contact Sheep Creek	equarea_magic.py	10 dec/inc p
airs found, but no equal area plots were made
2018-08-19 11:08:46.738654	Sheep Creek	eqarea_magic.py	Directional data found, but missing 
dir_tilt_correction, can't plot directions
2018-08-19 11:08:46.738732	Sheep Creek	equarea_magic.py	23 dec/inc pairs found, but 
no equal area plots were made

**Comment by moonshoes87** [comment]
@njarboe, I just re-found this thread.  I will make these changes in the error_logging branch and then we can re-assess.

**Comment by moonshoes87** [comment]
@njarboe, I'm working on making the error messages better.  [magic_contribution_16462.txt](https://github.com/PmagPy/PmagPy/files/2307484/magic_contribution_16462.txt)  seems to be missing a contribution id.  Is that a bug?

**Comment by moonshoes87** [comment]
It loos like zeq\_magic is created incomplete image names, i.e.:

    zeq_magic.py -f tmp_measurements.txt -fsp tmp_specimens.txt -fsa tmp_samples.txt -fsi tmp_sites.txt -sav -fmt png -crd g
    -I- Using online data model
    1  saved in  04VC0101-2_g_eqarea.png

This is also in contribution 16462.  This should be fixed.

**Comment by moonshoes87** [comment]
Looks like the incomplete image names is only happening when `isServer == False`, so that's not a problem for now.

**Comment by njarboe** [comment]
@moonshoes87 adding location + contribution id would work fine. I'll try and figure out why 16462 doesn't have and id. They all should.

**Comment by moonshoes87** [comment]
I've added a few more fixes on the error\_logging branch.  Error output now should have location and contribution id if available.  Also, I've made some fixes for generating eqarea plots.

**Comment by moonshoes87** [comment]
This functionality has been added, fixes or additions can be requested in new issues as needed.
