### ISSUE TITLE
thellier GUI calculate anisotropy tensors failing with non numeric measurement_number

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#423]
**What happened:**

Tried to calculate anisotropy tensors with  BenYosif_2016 dataset:

    Traceback (most recent call last):
      File "/Users/nebula/Python/PmagPy/programs/thellier_gui.py", line 2851, in on_menu_calculate_aniso_tensor
        self.calculate_anisotropy_tensors(data_model=self.data_model)
      File "/Users/nebula/Python/PmagPy/programs/thellier_gui.py", line 3327, in     calculate_anisotropy_tensors
        if float(rec['measurement_number']) == i * 2 + 1:
    ValueError: could not convert string to float: 'jh10a3:LP-AN-ARM1'

**What I expected to happen:**

Calculation should be performed.

**Data file(s):**

**Screenshot(s):**

**PmagPy version:**

**Comment by moonshoes87** [comment]
Hmm.  The problem is that the "correct" data model conversion is measurement --> measurement_number.  But it seems like what Thellier GUI *really* wants is treat_step_num --> measurement_number.  

<img width="1074" alt="screen shot 2018-08-16 at 11 37 52 am" src="https://user-images.githubusercontent.com/1836578/44227998-f41c1b00-a148-11e8-97ac-ddeeb1f4d2c4.png">

Maybe I can add some custom logic into Thellier GUI like I did in contribution_builder to deal with this.

**Comment by moonshoes87** [comment]
It looks like Thellier GUI is functioning correctly.  The relevant contribution had measurements.measurement values like this: jh10a3:LP-AN-ARM1, and no treat_step_num.

However, I'm trying out adding code to extrapolate the measurement number from the experiment name.  In other words, measurement number should start at 1 and increment up until the experiment name changes.  Or, should it start at 0?  This is the logic in Thellier GUI that needs to work:

    for i in range(n_pos):
        for rec in aarmblock:
            if float(rec['measurement_number']) == i * 2 + 1:
                ...

where n_pos can be 6, 9, or 15 depending on the experiment.

@njarboe, can you check this and confirm that this makes sense to you (lisa is busy with grand baby!)?  Mainly I need to make sure that measurement_number should start at 1 or 0.

This change will allow for calculating anisotropy tensors even if there is only a non-numeric measurements.measurement column.  I can send you an example if you want, but I can't find the dataset on MagIC so I don't want to post it publicly.

**Comment by njarboe** [comment]
@moonshoes87 As this is still open I hope this response is useful.

We have three numbers in the measurement table that are related to measurement_number.

measurements.sequence: this is described as the order of the measurements and is a signed integer.  For each experiment lower values indicate that they came before higher values. In general one would just start at 1 and count upward for all measurements ending at say 5676, but some people could start at 1 and count up to say 12 for one experiment and start over at one again for the next experiment. They could also start a 0, or some negative number. Does not have to be a unique number for a measurement. This should generally be the time order of measurements.

measurement.display_order: Greig wanted a way to tell how the measurement should be displayed in an order different than from how they were acquired. We have a display_order for that. It is usually blank and it is assumed that the sequence is the display order when display order is not defined.

measurement.treat_step_num is where the lab can put in the customary value of the step during an experiment. For AF demag that would be mT (say 0,5,10,20,40, etc) and for thermal demag that would be degrees C (30,100,200,300, etc).

In the 2.5 measurement.number is the "Measurement identifier or lab number", so just a unique identifier for a measurement. I think Lisa usually just counted up from one for this column and maybe that is how Ron used it in Thellier gui but I don't know how that code works. I would guess that you should use the 3.0 measurement.sequence value for what Ron uses the 2.5 measurement.measurement_number for as he was using Lisa's lab and just assumed that measurement_number would be in sequence, but as defined it could be any alpha-numeric label.

**Comment by ltauxe** [comment]
jeez.  no wonder our code keeps breaking.  
right now PmagPy maps 2.5 magic_measurements.measurement_number to treat_step_num  which was NOT what you describe below, at least originally.  that would be measurement.sequence  which may or may not be present or filled in correctly because this apparently changed at some point after PmagPy’s mapping was set up.  

so… do we change PmagPy’s mapping?  I fear that most of the measurement data already in the database are a mish mash.  the function  pmagpy.measurements_methods3() , used in many of the conversion scripts,  puts in both measurement.sequence and measurement.treat_step_num  and they are the same. 

lisa

**Comment by ltauxe** [comment]
This now seems like a hopeless mess.  How are we going to fix all the existing contributions?  
i can meet on zoom if you like… 
lisa

**Comment by njarboe** [comment]
I'll be on the MagIC meeting Zoom, Lisa. Meet you there?

**Comment by moonshoes87** [comment]
I have a sick baby, so I can’t make zoom right now.  I do have a suggestion for our next step on the measurement_number/treat_step_num issue:  I will explore using pandas magic to create a usable treat_step_num type column for internal use.  This shouldn’t be *too* hard.  I think this is likely to be the best solution.

**Comment by njarboe** [comment]
@moonshoes87 
Lisa and I just chatted. This is what we are thinking
In a 3.0 data file, treat_step_num should be the 2.5 measurement_number. I will change the definition in the 3.0 data model page to reflect that clearly. In the past some non-SIO people may have used measurement_number not in that way so that some 3.0 data files have treat_step_num values that are not a sequence of integers increasing by one each step. These should be fixed in the data model and hopefully you should not have to write code to get Thellier GUI to work in those cases. Just use the order they are in the data file or you could pop up a message "This data file is not in a format that can be used with Thellier GUI. Please contact the MagIC database team (https://www.earthref.org/MagIC/contact) for help in fixing your datafile to work with Thellier GUI.

**Comment by njarboe** [comment]
We are making a list of problems with the data conversion from 2.5 to 3.0 (https://github.com/earthref/MagIC/issues/374) that we hope to fix soon after AGU.
