### ISSUE TITLE
Need to remove first underscore in _2g_magic.py program and everywhere else

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#434]
I'm removing the underscore in the PmagPy notebook where possible. Leaving it where needed to run the code.

**Comment by moonshoes87** [comment]
That won’t work. Python packages can’t start with a number, so renaming _2g_bin to 2g_bin will break Pmag GUI. That is why the underscore is there. We could change the name to use “two” instead of 2 or some different renaming scheme...

https://stackoverflow.com/questions/17487209/can-a-python-package-name-start-with-a-number

**Comment by njarboe** [comment]
Ok. Good to know. I'll put it back in.
