### ISSUE TITLE
pmag_gui_anaconda fails to start on new anaconda and pip install

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#438]
I'm going through the cookbook and got this error. I created a new user on my Mac for the install, MacOS10.13.6, did the anaconda and pip install. PmagPy in the interpreter works, running "eqarea.py -h" works, but this does not:

kamacite:anaconda3 testing$ pmag_gui_anaconda
-I- Importing Pmag GUI dependencies
Traceback (most recent call last):
  File "/Users/testing/anaconda3/bin/pmag_gui_anaconda", line 11, in <module>
    from programs.pmag_gui import main
  File "/Users/testing/anaconda3/lib/python3.6/site-packages/programs/pmag_gui.py", line 22, in <module>
    from dialogs import pmag_gui_dialogs as pgd3
  File "/Users/testing/anaconda3/lib/python3.6/site-packages/dialogs/__init__.py", line 2, in <module>
    from . import demag_dialogs
  File "/Users/testing/anaconda3/lib/python3.6/site-packages/dialogs/demag_dialogs.py", line 16, in <module>
    try: from mpl_toolkits.basemap import Basemap
  File "/Users/testing/anaconda3/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py", line 146, in <module>
    pyproj_datadir = os.environ['PROJ_LIB']
  File "/Users/testing/anaconda3/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'PROJ_LIB'

**Comment by ltauxe** [comment]
We’ll we can migrate to cartopy, but it is very slow and the contourf
function is buggy

**Comment by moonshoes87** [comment]
I'm working on submitting a bug report to cartopy for the contours problem.  I'm trying to simplify the example as much as possible first.

Basemap can be downgraded (for OSX 64 bit with python 3.6) with these commands:

    conda install https://conda.anaconda.org/conda-forge/osx-64/pyproj-1.9.5.1-py36_0.tar.bz2
    conda install https://conda.anaconda.org/conda-forge/osx-64/basemap-1.1.0-py36_4.tar.bz2

I can figure out the required commands for other systems if that is the way we want to go, although it will be awkward.

**Comment by moonshoes87** [comment]
https://github.com/SciTools/cartopy/issues/1131

**Comment by njarboe** [comment]
Running those commands allows pmag_gui to run for me. A bit clumsy, as you say, to make people do this, but if nothing else works then that will have to do. If these are installed and then things change so they are not necessary, if a person does a pip pmagpy update, will they have to know to uninstall them? That could create quite a bit of confusion for people.

I still get this error running pmag_gui, if it is of interest:
objc[78467]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa003ac90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1c1c2abcd8). One of the two will be used. Which one is undefined.

**Comment by Swanson-Hysell** [comment]
Since there is pretty minimal use of Basemap within pmag_gui (just within a VGP viewer within demag_gui I think) we could pull it out of there for the moment.

I am willing to help with the cartopy transition (our issue #292). It seems like this switch is necessary given the end-of-life declaration for Basemap: https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement
which is going to lead to more and more issues along these lines.

For example, I have been getting this error a lot ```'AxesSubplot' object has no attribute 'get_axis_bgcolor'``` when trying to use Basemap functions such as ```pmap.drawcoastlines(linewidth=0.25)```. @lfairchild dug into the Basemap code and found the issue (pull request forthcoming?), but it points to continued issues that we will have in this regard. Have we identified other issues on top of the contourf one that are going to be problematic for such a transition?

**Comment by ltauxe** [comment]
I agree.  I worked out the basics - it is pretty slow and contourf definately has problems, but we will have to go there eventually.  I’ll send you some attempts  by regular mail. 
lisa

**Comment by ltauxe** [comment]
i agree with Nick S-H - we should just take the basemap stuff out of pmag_gui.  
lisa

**Comment by Swanson-Hysell** [comment]
Thanks for the cartopy files, @ltauxe. @moonshoes87, is it going to cause any problems if we start switching out some functions to cartopy and make that package an install requirement?

Oddly, a conda install of cartopy bundles it with Basemap (but this probably doesn't concern us):

```
Polarwander:~ superior$ conda install cartopy
Solving environment: done

## Package Plan ##

  environment location: /anaconda3

  added / updated specs: 
    - cartopy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cartopy-0.16.0             |   py36h81b52dc_2         1.7 MB  conda-forge
    proj4-4.9.3                |       h470a237_8         3.2 MB  conda-forge
    geos-3.6.2                 |       hfc679d8_3         2.5 MB  conda-forge
    pyproj-1.9.5.1             |   py36h508ed2a_5          58 KB  conda-forge
    shapely-1.6.4              |   py36h164cb2d_1         318 KB  conda-forge
    pyshp-1.2.12               |             py_0          22 KB  conda-forge
    basemap-1.1.0              |   py36h50ae964_7        15.2 MB  conda-forge
    pyepsg-0.3.2               |             py_1           9 KB  conda-forge
    owslib-0.17.0              |             py_0         117 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        23.1 MB
```

**Comment by moonshoes87** [comment]
Yes, we definitely want to switch out Basemap for cartopy.   In the meantime, I put in some checks so that a missing (or broken) Basemap won't break anything.  So things are stable for the moment.

@Swanson-Hysell, if you want to make a cartopy branch, I think that would be great. I'd like to change over those dependencies in one fell swoop.

**Comment by moonshoes87** [comment]
I've left Basemap in demag_gui/thellier_gui -- but prevented it from causing any breaking problems.  For now, people can continue to use Basemap if they have a compatible version or are using it in a conda env.

**Comment by Swanson-Hysell** [comment]
Ok. I can start a cartopy branch. I will focus the implementation within ipmag. While I am at it, I might make some more "full service" functions that can generate a full figure. At present, the user always needs to generate a map to start with. This approach is great for flexibility and plotting multiple datasets on one map, but being able to generate a full figure with a single function has its appeal as well.

**Comment by moonshoes87** [comment]
That sounds great!  One small suggestion is don't edit existing notebooks in the branch -- merging those is always a mess.

**Comment by lfairchild** [comment]
@Swanson-Hysell Regarding the specific issue with the deprecated `get_axis_bgcolor` function, this [has already been fixed](https://github.com/matplotlib/basemap/commit/ef252cf943126357b131cd600a473e86e351d48d) on the Basemap github repository (>= v1.1.0). The problem seems to be that the version on the "defaults" conda channel has not been updated since v1.0.7, but you can just update Basemap via conda-forge as Lori suggested above:
```bash
conda install https://conda.anaconda.org/conda-forge/osx-64/basemap-1.1.0-py36_4.tar.bz2
```
This is pretty trivial compared to the more complicated Basemap issues outlined above by Lori, but I just wanted to let you know that at least this particular problem has been resolved. It actually looks like Basemap was updated to v1.1.0 during your cartopy install, so I expect you aren't seeing that specific error anymore.

Let me know if I can help with anything as you start work on the cartopy branch.

**Comment by moonshoes87** [comment]
In the install instructions we’ve been recommending:  conda install basemap —channel conda-forge

which also does the trick without needing a specific url.  Sounds like this will not be an issue for much longer, though.

**Comment by moonshoes87** [comment]
@njarboe, could you try again installing the new pmagpy/pmagpy-cli and verify that it works in your fresh environment?  If you run the programs in your base env (which is what you will do by default), Basemap should just fail gracefully and be ignored.  If you create a pmagpy environment:

    conda create --clone base --name pmagpy
    source activate pmagpy

you should be able to actually use the Basemap parts.

**Comment by njarboe** [comment]
I'll can do full install from scratch with a newly created user or should I just uninstall and reinstall pmagpy and pmagpy-cli as my fresh user?

**Comment by njarboe** [comment]
Starting from the top with a new user, I installed without the basemap to start. Succeeded. I got a red highlight error about msgpack (see below), but continued and everything worked fine. pmag_gui ran and I could open the dmag and thellier programs.

After installing basemap, I get the gracefully failing message running pmag_gui_anaconda and it still runs.

After creating the pmagpy environment and activating, pmag_gui runs with no basecamp error. 
Looks good. One last suggestion. I think adding a note that the "from pmagpy import pmag" command will take a minute or two would be good. There is no indication that anything is happening and many people won't wait for over a minute for it to finish.

Successfully built scripttest
distributed 1.21.8 requires msgpack, which is not installed. (highlighted in red)
Installing collected packages: scripttest
Successfully installed scripttest-1.3

**Comment by moonshoes87** [comment]
Thanks, @njarboe.  

I will add a note to the install directions explaining that importing pmagpy for the first time is slow.

Which command did you run to produce the scripttest/msgpack error?  I am working on removing scripttest as a dependency for the pip install, since it is really only useful to developers.

**Comment by moonshoes87** [comment]
Ok.  So you're saying you saw that error when running `pip install --upgrade pip` as well?

I've taken out `pip install scripttest`, except for developer installs.  

Possibly I should add  `conda install msgpack-python` or `pip install msgpack`.

Looks there is some issue possibly related to msgpack-python being renamed to msgpack (but only on PyPI, not on conda).  https://github.com/dask/distributed/issues/1913

**Comment by njarboe** [comment]
@moonshoes87 "So you're saying you saw that error when running pip install --upgrade pip as well?"
Yes. I logged out of that test user, so I could not go back and copy the command verbatim. I guess I used update instead of upgrade as that is how I think about what is happening with that command. The word upgrade as a bit of a misnomer as many times (like this case with basecamp) the upgrade breaks things and is more of a downgrade.

**Comment by moonshoes87** [comment]
Ok, well, it doesn't seem like that warning breaks anything.  I removed scripttest as a dependency, for what that's worth.

I've also updated the Cookbook in a few more minor ways, including warning users that importing pmagpy can take a minute or more the first time.
