### ISSUE TITLE
pmagplotlib.plot_init() no longer works

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#478]
**What command was run:**
pmagplotlib.plot_init(1,5,5) from within a notebook

**What happened:**
NonGuiException                           Traceback (most recent call last)
<ipython-input-8-9f63f6ff2089> in <module>
----> 1 pmagplotlib.plot_init(1,5,5)

~/PmagPy/pmagpy/pmagplotlib.py in plot_init(fignum, w, h)
    135     plt.figure(num=fignum, figsize=(w, h), dpi=dpi)
    136     if not isServer:
--> 137         plt.get_current_fig_manager().show()
    138         # plt.get_current_fig_manager().window.wm_geometry('+%d+%d' %
    139         # (fig_x_pos,fig_y_pos)) # this only works with matplotlib.use('TKAgg')

~/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py in show(self)
   2685         optional warning.
   2686         """
-> 2687         raise NonGuiException()
   2688 
   2689     def destroy(self):

NonGuiException: 

**What I expected to happen:**

it should just initialize a plot

**Data file(s):**

**Screenshot(s):**

**PmagPy version:**

**Comment by ltauxe** [comment]
i think this will affect all plotting functions from within the notebook.

**Comment by ltauxe** [comment]
actually - it doesn't...   just some

**Comment by moonshoes87** [comment]
Yes, some of the plot interactivity stuff doesn't work very smoothly within the notebooks.  Which plotting functions in particular are you having problems with?  

In general it seems easier to save plots silently then display them with Image() as needed in the notebooks.  This is especially true with plotting routines that produce dozens or hundreds of plots -- having those all open at once (or all output into the result cell) is a mess.  What do you think?

**Comment by moonshoes87** [comment]
Trying to run ipmag.hysteresis_magic with save_plots=False

**Comment by moonshoes87** [comment]
See if we can check automatically for if we're in a notebook.

Also have a default of 5 plots.

**Comment by moonshoes87** [comment]
@ltauxe, it seems that we want three separate behaviors for plotting functions like ipmag.hysteresis_magic.

1.  Plot everything silently and save it
2.  Plot everything (or just the first five) and display it immediately (notebook)
3.  Plot everything and interactively ask users to save/continue/quit at each plot or set of plots (command line)

Does this seem right to you?

**Comment by ltauxe** [comment]
yup.  that sums it up. 
lisa

**Comment by moonshoes87** [comment]
I've modified plot_init so that it works fine within the notebook.  I've added a constant IS_NOTEBOOK to pmag_env/set_env.py, and modified plot_init to work correctly within the notebook environment.  So far so good.

I've updated ipmag.thellier_magic as a test case to fit this model.  (I know we were talking about hysteresis_magic earlier, but I did this with thellier_magic first).  It now takes an additional parameter `interactive` which does the command line type stuff.  This means that `save_plots==True` quietly saves, `save_plots==False` produces all plots without saving them (just spits them out into the notebook environment), and `interactive==True` does the regular command line thing.  I think this is a workable model, @ltauxe please feel free to try it out and comment.  Something cool that now works is that you can use interactive mode in the Python interpreter, yay!

<img width="705" alt="screen shot 2019-01-03 at 2 31 34 pm" src="https://user-images.githubusercontent.com/1836578/50665112-593fa400-0f64-11e9-9cc5-97045ad31a62.png">

**Comment by moonshoes87** [comment]
plot_init has been fixed to work with notebooks just fine.  This work of refactoring will now be continued in https://github.com/PmagPy/PmagPy/issues/424
