### ISSUE TITLE
int_scat values should be set to "t" and "f" not TRUE and FALSE

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#488]
int_scat values should be set to "t" and "f" not TRUE and FALSE

A quick grep in programs did not find where "TRUE" was being set but found it in this latest version of Tauxe 2004:
[magic_contribution_16533.txt](https://github.com/PmagPy/PmagPy/files/2665310/magic_contribution_16533.txt)

This is now caught by the validation so that data file does not pass. Might use this in the demo.

**Comment by moonshoes87** [comment]
Our list actually contains values that don't work -- "0", "False", "FALSE, "Fail", and "b" all evaluate to True.  

One option is that I could leave it flexible within PmagPy and just fix int_scat in upload_magic.  However, since you can now upload multiple MagIC files, it's possible that some people will skip using upload_magic.  

For now, I'm trying to change it so that PmagPy (basically Thellier GUI) sets values correctly to "t" or "f" but still accepts other values if found in the file.

**Comment by moonshoes87** [comment]
I’m guessing that it might not have have replaced the old values in fits you didn’t re-calculate, if scat was calculated previously.  I would try deleting the entire int_scat column, then running Thellier GUI —> save MagIC tables.  Or, I can look at  this (but not until tomorrow, possibly as late as afternoon).

**Comment by njarboe** [comment]
@moonshoes87 Ok. I can change them all to t in the file and then load into pmag_gui. Thanks.

**Comment by moonshoes87** [comment]
I have made the update so that Thellier GUI outputs "t" and "f" for SCAT.  There was some discussion of changing the validations to allow other values, and I'm not sure where we landed on that.  I am closing this issue, as it is now a MagIC issue not a PmagPy one.
