### ISSUE TITLE
Sites in data file uploaded into pmag_gui loses many required columns on the creation of a new MagIC file

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#489]
@moonshoes87, If I take this file from the current version of Bogue 2017 which passes the current validation 
[Bogue2017_16550.txt](https://github.com/PmagPy/PmagPy/files/2665329/Bogue2017_16550.txt) 
and open it up in pmag_gui, it loads up the file and I can look at the directions. I then added two interpretations and exported into the MagIC format using the defaults in the dialog and exporting specimen geographic and tilt corrected specimens.

The problem is that many values in the original file for required columns get removed. Here is a list from the new validation dialogue on the file I get from pmag_gui:
[Eastern-Sheep-Creek_Sheep-Creek_Valmy-Contact-Sheep-Creek_10.Dec.2018.txt](https://github.com/PmagPy/PmagPy/files/2665363/Eastern-Sheep-Creek_Sheep-Creek_Valmy-Contact-Sheep-Creek_10.Dec.2018.txt)
<img width="848" alt="screen shot 2018-12-10 at 3 16 09 pm" src="https://user-images.githubusercontent.com/1278789/49768487-60d79a00-fc91-11e8-9fe9-9c40c7ad5ad3.png">

**Comment by moonshoes87** [comment]
@njarboe, I'm working on this now.  

It looks like if I just do download_magic/upload_magic I get no validation errors, so the issue is something that is happening in the process of making interpretations.  I will continue to look into this.  Also, please let me know what (if anything) is most urgent for right now.

**Comment by moonshoes87** [comment]
I tried download_magic/Demag GUI 2 interpretations saving only specimen tables/upload_magic, and got these 3 errors on validation:

<img width="886" alt="screen shot 2018-12-12 at 3 24 48 pm" src="https://user-images.githubusercontent.com/1836578/49905350-2cdfae80-fe22-11e8-89a3-1424fcdffda8.png">


Taken from the file I uploaded:

Relevant row in specimens:

specimen    experiments sample  dir_alpha95 dir_comp    dir_dec dir_inc dir_n_comps dir_n_measurements  dir_\
tilt_correction dir_dang    dir_mad_free    geologic_classes    geologic_types  lithologies meas_step_max   \
meas_step_min   meas_step_unit  analysts    instrument_codes    software_packages   int_corr    citations   \
method_codes    result_quality  result_type volume
0SC09A1 **0SC09A1:LP-DIR-T**    0SC09A1     Fit 1 

Relevant rows in measurements:

measurement experiment  specimen    dir_csd dir_dec dir_inc treat_ac_field  treat_dc_field  treat_dc_field_p\
hi  treat_dc_field_theta    treat_step_num  treat_temp  citations   instrument_codes    method_codes    qual\
ity sequence    standard    meas_n_orient   meas_temp   analysts    description software_packages   magn_mom\
ent magn_x_sigma    magn_y_sigma    magn_z_sigma

0SC09A1:LP-DIR-T1   **0SC09A1:LP-DIR-T**    0SC09A1 1.0 64.9    -79.8   0.0 0   0   0   1   273 This study      \
LT-NO:LP-DIR-T  g   1   u   8   273 Scott Bogue     pmagpy-3.10.0   1.52e-05    1.16e-07    1.01e-07    1.63\
e-08
0SC09A1:LP-DIR-T2   **0SC09A1:LP-DIR-T**    0SC09A1 1.0 63.2    -79.9   0.0025  0   0   0   2   273 This study  \
    LT-AF-Z:LP-DIR-T    g   2   u   8   273 Scott Bogue     pmagpy-3.10.0   1.53e-05    1.14e-07    9.97e-08\
    1.73e-08


So this first problem seems like an error with the validations.  @rminnet, do you want me to open a separate MagIC issue for this?

**Comment by rminnett** [comment]
So, if I understand correctly, these measurements have experiment names that include colons? 

If so, this creates a problem in the specimens table because the experiments column is defined as a colon-delimited list and the validation is breaking up the experiment name and then trying to find matches that won't exist. We can either:

1) add a "no colons" validation to measurements.experiment (and to the other tables since they could have the same issue), or 

2) allow colons to be escaped with quotes so specimen.experiments could pass validation if the colon-containing experiment name is **"0SC09A1:LP-DIR-T"** instead of just **0SC09A1:LP-DIR-T**.

If you're just trying to get this to pass validation now, the experiment names could be changed to **0SC09A1_LP-DIR-T**.

**Comment by njarboe** [comment]
I think no colons in experiment names is fine. I'll look into why this contribution ended up with that and change them in the data file to underscores.

**Comment by moonshoes87** [comment]
pmag.measurements_methods3 (which is used in most conversion scripts) uses colons for measurements.experiment.  

Would we just want to replace ":" with "_", or another simple fix?  I am not sure exactly how measurements.experiment is used internally throughout PmagPy, particularly in the Demag/Thellier GUIs. @ltauxe?

This line is where measurements.experiment is set (around line 8695)

    rec["experiment"] = spec + ":" + experiment_name


experiment_name may also have even more colons depending on the type of experiment, i.e.:
                if IZ == 0 and ZI == 1:
                    experiment_name = experiment_name + ":LP-PI-ZI"  # Coe method

**Comment by njarboe** [comment]
@moonshoes87, I'm heading back from AGU this evening and will take a look at this next week. I think we can have multiple experiments on the same specimen, so we have a colon delimited list of experiments in the specimens table. I think using an _ or - instead of : should be fine but not sure what pmag_gui programs expect.

**Comment by njarboe** [comment]
Looks good.
