### ISSUE TITLE
demag_gui doesn't allow directory navigation when launched independently

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#50]
The GUI showing the current directory flashes up, but then disappears and the GUI proceeds as if you have selected your current directory.

```
Laurentia$ demag_gui.py
/Users/Laurentia/anaconda/envs/python2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
icon_path /Users/Laurentia/PmagPy/images/PmagPy.ico
-I- done sorting meas data
------------------------------ no magic_measurements.txt found---------------------------------------
```

**Comment by Caoimhinmg** [comment]
works on the lab machine and on my machine in the new version, let me know if you're still having an issue.

**Comment by Swanson-Hysell** [comment]
Demag_gui now allows directory navigation (and selection of a magic_measurement.txt file which took me a while to figure out), but after I select the directory and the main panel launches a white box that was the directory selection window covers the window (and all other windows on my computer). See image below:

<img width="1559" alt="screen shot 2016-02-09 at 2 01 53 pm" src="https://cloud.githubusercontent.com/assets/4332322/12932084/e816ca04-cf35-11e5-8320-5cdf0ecdf47e.png">

**Comment by Swanson-Hysell** [comment]
@Caoimhinmg, this ghost dialog box is still an issue when I launch demag_gui using the Anaconda distribution. Doesn't seem to be an issue in the Enthought virtual environment. Oddly, I am asked to select a magic_measurements.txt upon launch in  Anaconda, but am asked to select a directory when in the Enthought virtual environment. Thoughts on what could be causing this variability in behavior?

**Comment by Caoimhinmg** [comment]
@Swanson-Hysell, Strange the hanging box is obviously caused by a call to wx.Yield which makes this little wait screen as it should though it seems very buggy as it only occasionally works on my distro and obviously is not working for you. Why the anaconda distro seems to have trouble with the box I'd guess it's something internal, but it also seems to be ignoring my if statement for directory selection. I'm thinking it might be due to my use of python's internal boolean values for all objects I've made my if statement more explicit. Hopefully that can fix this, however I'm working on making the tests work and code clearer now so I won't upload until that is done probably later this week.

**Comment by Swanson-Hysell** [comment]
No longer an issue.
