### ISSUE TITLE
Demag_gui doc review comments and minor suggested changes

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#504]
@moonshoes87, I'm looking over the dmag_gui docs as I look over the missing column issue. Here are some comments. I'm on a Mac and just pulled from master.

On 3.4 Demag GUI quick start
1) Maybe you state elsewhere that for hotkey ctrl means command on a Mac, but unfortunately Mac also has a control key and that does not work for the hot keys. Coming directly to this page, I tried ctrl-n and it did nothing. Not a huge deal as Mac users will likely try command, but a bit confusing. Not sure if the text should be changed or Demag GUI changed so ctrl also works for the commands in addition to the command key.

On 5.1 demag_gui.py
2)"Another way to edit bounds is to double-click the list of measurement steps in the list on the left. The included steps in the currently selected interpretation are shown in highlighted in blue on the measurement list and the measurements marked “bad” are shown in highlighted in red. In the case of duplicate measurements, the first good measurement with the same treatment is used as a bound."
It is not clear how to mark a sample bad. I thought double clicking twice might do it, but it doesn't. Right click works. How about:
" Another way to edit bounds is to double-click the list of measurement steps in the list on the left. The included steps in the currently selected interpretation are shown ~~in~~ highlighted in blue on the measurement list and the measurements marked “bad” are shown ~~in~~ highlighted in red. **Bad measurements can be marked and unmarked by right clicking on them (this change takes a moment to appear).** In the case of duplicate measurements, the first good measurement with the same treatment is used as a bound."

3)"This display option can be changed in the second drop-down menu under interpretation type." I don't see this option. Also: ""This display option can be changed in the **Edit** menu under interpretation type." would be clearer unless that menu changes names on a Mac v Other.

4)"by using the drop-down menu under the label ‘interpretation type’."
Using the term label and box for the same GUI type is a bit confusing. I was looking for a drop down in the main header bar. Box is used to describe the 'Interpretation Directions and Statistics’ box, and I think that is less confusing.
Change to?
"by using the drop-down menu in the ‘Interpretation Type’ box. Not sure if you want to change all of the capitalization, but it is clearer when the docs have the same capitalization as the GUI and the next label has that treatment.

5)"select the one you wish to delete from the interpretation drop-down menu and click ‘delete’."
change to the label on the button 'delete highlighted fits'

These docs are quite good and pmag_gui is much improved since the last time I used it extensively. Thanks.

**Comment by moonshoes87** [comment]
1. We have options.  Many of the shortcuts could be made to work with cmd or ctrl on Mac.  However, others have built in OSX functionality -- for instance, ctrl up or ctrl down.  Given this inconsistency, I think it is probably better to just explain that you need to do command instead of ctrl, so I'm adding a bit about that in the quickstart section and in the main Demag GUI section.

2.  Done

3.  I believe that text is referring to the second menu here (defaults to whole plane):

<img width="189" alt="screen shot 2019-02-06 at 1 21 22 pm" src="https://user-images.githubusercontent.com/1836578/52374495-495b2a00-2a12-11e9-8390-4455b251d101.png">

I changed for that paragraph (sorry, in LaTeX):

The name of the fit can be changed from the default by typing into the drop-down box containing fit name. The default fit type is a least-squares line. You can choose different fits, such as a line anchored to the origin or a plane, by using the drop-down menu in the `Interpretation Type' box. Plane fits can be plotted as either poles, full planes, partial planes, best fit vectors, or best fit vectors and full plane ({\bf Note:} plane poles will be displayed as squares and best fit vectors will display as sideways triangles on \hyperref[higher-level-plots-and-interpretation]{high level mean plot}). This display option can be changed in the second drop-down menu in the `Interpretation Type' box.

4.  Done

5.  Changed it to 'delete fit' (still trying to keep it short for space reasons).

**Comment by njarboe** [comment]
I did not check to see how these changes look, but from your comment it looks like you dealt with everything, so I'll close the issue.
