### ISSUE TITLE
Validation check still says I have missing columns after I have added them

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#507]
On the Bogue2017 file I'm testing on, when I added some interpretations and then went to export I add two columns dir_nrm_origin and dir_polarity, saved and then the tool said I still had to add them. Went back and the columns were there but still had the error. Tried saving the grid and the same issue.

Maybe the problem is related to #506

Screen after adding the columns, saving the grid, and returning from the main screen
![screen shot 2019-01-30 at 4 25 43 pm](https://user-images.githubusercontent.com/1278789/52022205-a738c080-24ac-11e9-88cf-fa2f06322567.png)

Mainscreen showing I still have an error
![screen shot 2019-01-30 at 4 25 57 pm](https://user-images.githubusercontent.com/1278789/52022238-d0f1e780-24ac-11e9-90fd-52992ff3de81.png

Screen after going back showing the columns are there but still marked as an error.

**Comment by moonshoes87** [comment]
@njarboe, the validation is not re-run until you exit validation mode and do upload_magic again.  I can see how this could confuse people.  I will see about refactoring so that the validations for a particular table are re-run once the table window is closed -- if it is straightforward to implement, it seems like a worthwhile update.

**Comment by moonshoes87** [comment]
Validations are now being re-run when needed, so I'm closing this issue.
