### ISSUE TITLE
pmag_gui validation does not read Boolean vocabulary correctly - cannot save data to magic file

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#509]
I am trying to just download the recent upload, Bono 2019, from magic, load it into pmag_gui, and export it as a magic file to compare with the original download. 

If I uppack the data file (
[magic_contribution_16534.txt](https://github.com/PmagPy/PmagPy/files/2818669/magic_contribution_16534.txt)
) and then try to save as a magic file without doing anything else, I get these errors:

![screen shot 2019-01-31 at 10 50 18 am](https://user-images.githubusercontent.com/1278789/52077928-fc291500-2546-11e9-924d-f27af43d9dbf.png)
Looking at the specimen table in the validation tool:
![screen shot 2019-01-31 at 10 52 03 am](https://user-images.githubusercontent.com/1278789/52078005-0c40f480-2547-11e9-8c10-c5aeb0a018cc.png)
Then the specimens_error.txt file with the error:
'"t" is not in controlled vocabulary for boolean'
But the current data model on the website has the Boolean Flags as 't' and 'f'
[https://www2.earthref.org/vocabularies/controlled](url)
![screen shot 2019-01-31 at 10 52 32 am](https://user-images.githubusercontent.com/1278789/52078053-21b61e80-2547-11e9-872a-72402d87a0c6.png)

**Comment by ltauxe** [comment]
seems like we should recognize ’t’, ‘1’, ‘True’, ‘true’ (and similar for False) as being valid and then convert them to whatever MagIC wants within the GUI.  no?  
lisa

**Comment by moonshoes87** [comment]
@njarboe, yes, this is easily fixed.  Just need to add it to the boolean list.  Thanks!

**Comment by njarboe** [comment]
@moonshoes, With your changes made above is it ready for me to test again? On master?

**Comment by moonshoes87** [comment]
You can either test on master (which has all of the fixes other than Demag GUI ages stuff), or on the demag_gui branch (which has all the fixes from master AND the more experimental fixes for Demag GUI).

**Comment by njarboe** [comment]
Great. I'll use demag_gui branch and see how that works and also try it on master.

@moonshoes87 Do you know why, after I checkout the pmag_gui branch and then pull, I have to leave a merge message? I don't have to do that when just pulling from master.
Thanks.

**Comment by moonshoes87** [comment]
I'm guessing it's because I rebased master into demag_gui and then "force pushed" (`git push -f`).  I don't think it is a problem, though.

**Comment by njarboe** [comment]
There seems to be a new bug in demag_gui
These two recent uploads used to display in demag_gui put don't  work now.
I'm on master

Santos and Tauxe 2018:
[magic_contribution_16502.txt](https://github.com/PmagPy/PmagPy/files/2833423/magic_contribution_16502.txt)
<img width="709" alt="screen shot 2019-02-05 at 10 53 20 am" src="https://user-images.githubusercontent.com/1278789/52297009-9cf74600-2934-11e9-9336-fd22905f9be1.png">
<img width="1411" alt="screen shot 2019-02-05 at 10 56 02 am" src="https://user-images.githubusercontent.com/1278789/52297024-a680ae00-2934-11e9-832d-bf05ef7e16e8.png">

And Bono et al. 2019:
[magic_contribution_16502.txt](https://github.com/PmagPy/PmagPy/files/2833425/magic_contribution_16502.txt)

<img width="1266" alt="screen shot 2019-02-05 at 10 57 08 am" src="https://user-images.githubusercontent.com/1278789/52297112-d6c84c80-2934-11e9-8404-4f2669032f06.png">

**Comment by moonshoes87** [comment]
@njarboe, one thing I notice is that it works correctly if I select 'specimen' as the Coordinate System:

<img width="1552" alt="screen shot 2019-02-05 at 11 36 55 am" src="https://user-images.githubusercontent.com/1836578/52299493-602e4d80-293a-11e9-88af-fb51302fb225.png">

Do you know if Demag GUI was working correctly with these contributions with geographic coordinates before?

**Comment by njarboe** [comment]
I would say a master pull early to mid last week.

**Comment by moonshoes87** [comment]
@njarboe, I've gone back in git history as far as 64808261f45e3263c65ca20679b09dad034a8d3d (committed December 5), and the same errors are still happening, so I don't believe that this is due to a recent code change.  This makes me think that something must have changed either in the files, or perhaps in your Demag GUI settings?  Were these contributions uploaded and then re-downloaded?

**Comment by moonshoes87** [comment]
As far as I can tell, at least in 16502, this problem is happening because there is dec/inc available at the measurement level but no azimuth/dip at the sample level.  So Demag GUI tries to call `pmag.dogeo`, which then produces a bunch of `nan`s, and `zijdblock_geo` and `zdata_geo` then end up full of `nan`s.  Demag GUI thinks there is geographic data, but there actually isn't any that is *valid* and complete.  

@ltauxe, I can edit Demag GUI so that it doesn't fill in `zijdblock_geo` and `zdata_geo` if values returned by `pmag.dogeo` include `nan`.... does that make sense to you?

**Comment by moonshoes87** [comment]
Same problem applies to Bono 2019.  Not sure why/how these contributions worked before, but I am confident about why we have problems now.  I pushed a fix -- @ltauxe and @njarboe, if you would both have a look and make sure it makes sense, that would be great.

**Comment by njarboe** [comment]
Sorry about the goose chase on finding a version that worked. Not sure what kind of settings I may have changed that caused it to break. Does demag gui save what coordinate system you have selected(answer not important if you don't know of the top of your head, but if so, that could have been the problem)?

I've tested out your changes and I have got the file to go from MagIC into PmagPy and back into MagIC with minor changes in the data. This is great. I'll close this issue at this point and open new ones when needed.

**Comment by moonshoes87** [comment]
I don't think Demag GUI saves that preference, but in any case Demag GUI should only provide as options coordinate systems that are actually available.  So in that particular contribution, only specimen coordinates should have been available, regardless of what you had selected previously.  I'm going to merge all of this back onto master, since it seems to be working.

**Comment by njarboe** [comment]
Ok. I'll move back to the master branch.
