### ISSUE TITLE
make_magic_plots with a contribution with two locations only makes an "All" equal area plot

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#510]
Just pulled from master.

Trindade et al. 2018 has only locations and sites, but make_magic_plots can handle this and should make equal area plots for each locations, correct? It does make an all plot but not individual location equal area plots. That would be nice to have for the website. At the location level one would have a different equalarea plot for each one.
Here is the magic file: 
[magic_contribution_16587.txt](https://github.com/PmagPy/PmagPy/files/2838739/magic_contribution_16587.txt)
Command line when I run make_magic_plots
![screen shot 2019-02-06 at 3 29 10 pm](https://user-images.githubusercontent.com/1278789/52381261-a9a79700-2a25-11e9-99ed-cdc03553a6fc.png)
Only plot generated
![screen shot 2019-02-06 at 3 41 57 pm](https://user-images.githubusercontent.com/1278789/52381297-c9d75600-2a25-11e9-824a-9452af3b3807.png)

**Comment by ltauxe** [comment]
while we’re on this subject, i did change the default colors for the vgp and pole plots….  
lisa

**Comment by njarboe** [comment]
I just pulled from the master pmagpy repository on the server and ran make_magic_plots again and got this plot.
![lo__alho 31_si__al_01_sa___sp___co__g_ty__eqarea_](https://user-images.githubusercontent.com/1278789/52454678-88b47400-2b01-11e9-9ad1-8f437f96e119.png)

With your changes, what were you expecting? Maybe not committed and pushed? @moonshoes87 Or it runs with some non default parameters set?

**Comment by moonshoes87** [comment]
@njarboe, I haven't pushed a fix for this issue yet.  Only sites for one of the two locations are being plotted -- the reason for this was a check on the citations column so that only sites from "This study" would be plotted.  In this contribution, the sites from Alho 06 had an additional citation: "10.1038/srep24762: This study", and so all of those sites were being ignored.  With that bug fixed, this contribution produces two plots, one for each location (I will push this fix soon).

Once that is fixed, are there additional plots desired, other than one equal area plot for each location?

**Comment by moonshoes87** [comment]
@njarboe, let me know if anything else/different is desired here, otherwise I will close this issue.

**Comment by njarboe** [comment]
I'll check it out in a bit.

**Comment by njarboe** [comment]
Looking good. 
Instead of the label "All" at the top of the plot it would be better to have the location name and the number of sites. So for this one:
http://34.236.167.37/plots/16587/LO:_Alho%2006_SI:_AL_06-01_SA:__SP:__CO:_g_TY:_eqarea_.png
![screen shot 2019-02-11 at 11 40 33 am](https://user-images.githubusercontent.com/1278789/52589145-007cea00-2df3-11e9-86f8-c3e2f52e1217.png)

It would be "AL 06 - 26 sites plotted"
(not sure if 26 is the correct number, just estimating here)

@rminnett Would it be better if spaces in names were converted to underscores? I think I would prefer it for ease of use in Linux, if that does not break things.

**Comment by moonshoes87** [comment]
@njarboe, looks good.

![all_alho_06_g_eqarea](https://user-images.githubusercontent.com/1836578/52595988-121abd80-2e04-11e9-9a75-9b84cea3fd78.png)


In the medium term, I expect to create an images table and use very simple names for the plots (i.e., "1.png").  So the spaces vs underscores issue shouldn't be a problem indefinitely.  However, if it is overly annoying now, I can implement underscores (although it will take me a little bit of time since I'll need to track things titles down in each individual program, the way things are currently written).

**Comment by njarboe** [comment]
Looks good.
