### ISSUE TITLE
Add simple title to thumbnails

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#542]
All the plots sort of look the same when there are a lot of them. If you would add a title with the name of the specimen or sample or site or location on the thumbnail, I think it would save people much time when they are looking for a particular plot. It would also give a quick context of what they are looking at. site names are different than specimen names, usually.

**Comment by rminnett** [comment]
The thumbnails don't currently have a lot of padding to add any text to them:
![image](https://user-images.githubusercontent.com/1182698/54507720-d641af00-48ff-11e9-9c34-38b37e0c3da7.png)
(the blue is the thumbnail).

Instead of adding text to the image, I can add text in the browser below the thumbnail based on the filename (and later based on the content in the images table). Would that work?

**Comment by njarboe** [comment]
Yea. Space is at a premium so if in the browser just adding the, say, specimen name and not the whole filename would be preferred. The font could be bigger in most cases that way.

**Comment by moonshoes87** [comment]
Ok, I will leave this to @rminnett.  Let me know if I should do something.

**Comment by rminnett** [comment]
Superceded by https://github.com/earthref/MagIC/issues/446
