### ISSUE TITLE
Anisotropy thumbnail cropping is slightly off

### ISSUE THREAD

**Issue by rminnett** [PmagPy/PmagPy#543]
This is similar to the Equal Area plots when they are in specimen coordinates with the red line and "X". For example in https://earthref.org/MagIC/16496:

![image](https://user-images.githubusercontent.com/1182698/54507812-654ec700-4900-11e9-85cb-a94e4193b3a1.png)

Perhaps Matplotlib tight_layout() or explicitly setting the position of the axis location before cropping might help?

**Comment by moonshoes87** [comment]
Ok, I will look at this shortly.

**Comment by moonshoes87** [comment]
@rminnett, when I run make_magic_plots locally (with `isServer = True`), I seem to get the correct cropping:

![MC:_16496_TY:_aniso_conf_](https://user-images.githubusercontent.com/1836578/54723058-8d6a4000-4b23-11e9-8837-4c644b16e928.png)
![MC:_16496_TY:_aniso_conf_ thumb](https://user-images.githubusercontent.com/1836578/54723059-8d6a4000-4b23-11e9-942b-0196b3f5f913.png)
![MC:_16496_TY:_aniso_data_](https://user-images.githubusercontent.com/1836578/54723060-8d6a4000-4b23-11e9-8863-2128a5a9f154.png)
![MC:_16496_TY:_aniso_data_ thumb](https://user-images.githubusercontent.com/1836578/54723061-8e02d680-4b23-11e9-8df3-73148975d5dc.png)

I think this may be the result of the timing of the last run on the plotting server -- I may have been in the middle of some refactoring.  @njarboe, would now be a good time for you to re-run the plots?  I have made several fixes based on the last run.

**Comment by njarboe** [comment]
Ok. I'll pull and re-run shortly. I'll also add the contribution.txt and errors.txt files for Rupert.

**Comment by njarboe** [comment]
Running. 

I put in some timestamps in the log so I can get a better idea of how long it actually takes.

**Comment by njarboe** [comment]
The run has finished. Four large files not run. It took 16hr 16min. There are certainly files in my list that have a new version and both are being run that adds to this time. @rminnett, if there is an easy way you can get an updated list of contribution files on the plot server, that would be great.

The problem is with the thumbnails, not the plots being off and that problem still exists.
See plots and files :http://34.236.167.37/plots/16496/

**Comment by njarboe** [comment]
![Screen Shot 2019-03-21 at 10 04 18 AM](https://user-images.githubusercontent.com/1278789/54770614-d58b7000-4bc0-11e9-89c8-f9d9f7d7c0e1.png)

**Comment by rminnett** [comment]
> @rminnett, if there is an easy way you can get an updated list of contribution files on the plot server, that would be great.

Sure, @njarboe, do you want all of the latest versions of activated contributions or just the most recent back to a certain date?

**Comment by moonshoes87** [comment]
@njarboe, it looks like you are still running the old aniso_magic in make_magic_plots instead of the new aniso_magic.  I just downloaded the magic_contribution_16496.txt from your link, downloaded it, and ran make_magic_plots.  These are the thumbnails I got:

![MC:_16496_TY:_aniso_conf_ thumb](https://user-images.githubusercontent.com/1836578/54776209-da562100-4bcc-11e9-817e-3fec342683c1.png)
![MC:_16496_TY:_aniso_data_ thumb](https://user-images.githubusercontent.com/1836578/54776211-daeeb780-4bcc-11e9-926f-b07113043aca.png)

I also notice that the plot names you are getting are different from the plot names that I am getting:

<img width="678" alt="Screen Shot 2019-03-21 at 11 32 09 AM" src="https://user-images.githubusercontent.com/1836578/54776295-0a052900-4bcd-11e9-995a-e7ecc2bb8e24.png">

<img width="355" alt="Screen Shot 2019-03-21 at 11 32 49 AM" src="https://user-images.githubusercontent.com/1836578/54776320-17221800-4bcd-11e9-8677-0c6a3748c378.png">

Based on that I conclude that you must be somehow using an older copy of make_magic_plots.  I switched to using `aniso_magic.py -new` as of this [commit](https://github.com/PmagPy/PmagPy/commit/12df1e231a060f59007d8c1735cd8e6332f4ce65).

Try `git log` and see the latest commit you have.

**Comment by njarboe** [comment]
The first two in my git log are:

commit 372c72d7526824de9bb756c673a84784d95017d7
Author: Lori J <mintblue87@gmail.com>
Date:   Wed Mar 20 16:13:55 2019 -0700

    fixes for aniso_magic, #531

commit fa1eaeb9bb5cf496353292df410a6f62602d0ef8
Author: Lori J <mintblue87@gmail.com>
Date:   Wed Mar 20 14:58:50 2019 -0700

    update environment.yml, #503

**Comment by njarboe** [comment]
I did a hard reset and will test out the plots on 16496.

**Comment by njarboe** [comment]
Set server back to True, but still have the problem.

**Comment by njarboe** [comment]
Looked at commit and it shows the "-new" added but I looked at make_magic_plots.py on github with the browser and the "-new" changes are not in make_magic_plots.py. There must have been some reversion. I'll make the two changes in make_magic_plots.

**Comment by moonshoes87** [comment]
@njarboe, has this been resolved?

**Comment by njarboe** [comment]
@moonshoes87  Not yet. Is that the expected git log? 

I updated may python packages using conda. That is probably the issue. What is the best command to do that in the future and are there packages I need to reset after?

What do you do when your packages are messed up?

**Comment by njarboe** [comment]
Reinstalled anaconda and pmagpy. Now working. I'll re-run all the plots shortly.

**Comment by moonshoes87** [comment]
@njarboe, I am glad to hear it!  One option for fixing package versions is to can clone the environment from within the PmagPy directory:

    conda env create --file environment.yml

This will make a new conda environment called pmagpy which you can then activate:

    conda activate pmagpy

That environment will then have all the specific packages that are confirmed to work as expected.  I know this works for OSX, not sure about Windows/Linux.  You can also use the environment.yml file to check the version of a package you have installed against the vetted packages in the environment list.  

That said, I do find that I occasionally need to reinstall Anaconda (maybe every 6 months), because something gets messed up and I can't seem to re-set it.
