### ISSUE TITLE
demag_gui and thellier_gui

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#550]
**Is your feature request related to a problem? Please describe.**

Right now these GUIs only work on measurements.txt.  It would be nice if an alternate file name could be used.  

**Describe the solution you'd like**

under File, there should be an option to choose a different name for the measurements.txt file.

**Additional context**

**Comment by moonshoes87** [comment]
@ltauxe, in this situation, should the GUI use the specimens.txt/samples.txt/sites.txt that are found in the current working directory, OR in the directory of the selected file if those are different?

**Comment by moonshoes87** [comment]
@ltauxe, I've changed Demag GUI so that it lets you pick a measurements file if there isn't one available in your initial working directory.  It's a little more complicated to get it to re-set in the middle, but hopefully this is helpful.  You can choose an arbitrary .txt or .magic file using the GUI (if there is no measurements.txt file in your WD), or you can use the -f option on the command line.

**Comment by ltauxe** [comment]
thanks!   i’ll check it out.  

lisa

**Comment by ltauxe** [comment]
hmmm.  i guess the directory containing the measurements table.

**Comment by moonshoes87** [comment]
Ok, that's what I did (use the measurement file directory as the WD).  Now you can also open a new measurements file while running Demag GUI -- this required a bit of surgery on the Demag GUI reset_backend() function.  Test it out!

I will work on Thellier GUI next.

**Comment by moonshoes87** [comment]
@ltauxe, I just now got to checking on Thellier GUI for this, and it seems like it is already implemented.  It is in File --> Open MagIC measurement file.  

If it *doesn't* work for you, please reopen this issue!

**Comment by moonshoes87** [comment]
I just added a -f option to thellier_gui.py.
