### ISSUE TITLE
KeyError: 'treat_ac_field' with ipmag.download_magic("magic_contribution_16533.txt") in notebook

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#563]
**What command was run:**

```
ipmag.download_magic("magic_contribution_16533.txt", dir_path="data_files/download_magic", 
                     input_dir_path="data_files/download_magic")
status,data=cb.add_sites_to_meas_table('data_files/download_magic')
df=data[data.method_codes.str.contains('LT-T-Z')] # select the thermal demag data
df=df[['specimen','treat_temp','magn_moment','quality']]
df=df.dropna(subset=['treat_temp','magn_moment'])
ipmag.plot_dmag(data=df,title="Thermal demag",fignum=1)
```

Within PmagPy_plots_analysis notebook

**What happened:**

```
KeyError: 'treat_ac_field'
```

**PmagPy version:**
master at time of this commit: https://github.com/PmagPy/PmagPy/commit/d4970774f75360b1a00f4a7655073117c133b582

**Comment by moonshoes87** [comment]
It seems that the problem here is this line:

df=df[['specimen','treat_temp','magn_moment','quality']]

**Comment by moonshoes87** [comment]
Sorry, I hit the wrong key and that posted prematurely.

The problem is that this line:

```
df=df[['specimen','treat_temp','magn_moment','quality']]
```

Removes the column `treat_ac_field`, which is the default value used for `dmag_key` in `ipmag.plot_dmag`.  So we can fix this with:

 `ipmag.plot_dmag(data=df,title="Thermal demag",fignum=1, dmag_key='treat_temp')`.

We can either fix this example, or we could add a line to `ipmag.plot_dmag` that searches for other dmag_keys if `treat_ac_field` is not available.  

@Swanson-Hysell, let me know what you think!

**Comment by Swanson-Hysell** [comment]
Fixing that example seems fine. I just did so in the notebook.
