### ISSUE TITLE
ipmag.dayplot_magic() not ingesting data

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#564]
**What command was run:**

```
ipmag.dayplot_magic(path_to_file='data_files/dayplot_magic',hyst_file='specimens.txt')
```

Note that this cell of the notebook previously referred to the function ipmag.dayplot() but that function not longer appears to exist.

**What happened:**

```
-W- Couldn't read in samples data
-I- Make sure you've provided the correct file name
-W- Couldn't read in samples data
-I- Make sure you've provided the correct file name
```

**What I expected to happen:**

It to make plots like the command line program.

**PmagPy version:**

Master at time of this commit: https://github.com/PmagPy/PmagPy/commit/aecc11a7dcb052974be48f7bf467b0fe606c7fed

**Comment by moonshoes87** [comment]
@Swanson-Hysell, thanks for finding this.  I have been working through the plotting programs to eliminate some unnecessary repetition (dayplot_magic had a function in ipmag that was almost identically replicated in dayplot_magic.py).  I did some refactoring so that this function could be used in dayplot_magic.py and have defaults that are more in line with the other plotting programs.  I apparently didn't get to checking it in the notebooks yet.

It looks to me like your example does still basically work in PmagPy_plot_analysis.ipynb.  The message:

`-W- Couldn't read in samples data` is caused by trying to propagate the location name down to the specimen level so that the plot can be named with more detail.  I think it makes sense suppress that message -- I'll make a separate issue for that.  But the example does seem to create and save the files:

<img width="930" alt="Screen Shot 2019-04-24 at 12 52 40 PM" src="https://user-images.githubusercontent.com/1836578/56689425-e895d200-668f-11e9-9935-3b60e9371d2c.png">

Those plots could be displayed with Image("_Day.svg") and soon.

We probably want to just set save=False, though.  In the notebook environment that will result in all created plots being displayed and not saved.

![Screen Shot 2019-04-24 at 12 52 02 PM](https://user-images.githubusercontent.com/1836578/56689492-09f6be00-6690-11e9-8730-3977401f1cd2.png)

I won't make that change unless you give me the go-ahead, since I've seen the git hell that can ensue from working on the same notebook.

Are you seeing a different behavior, or does this clarify things?

**Comment by Swanson-Hysell** [comment]
This clarifies things. Seems like there are instances where one might want to display and save, but this approach is fine and I have updated the example in the notebook.
