### ISSUE TITLE
ipmag.upload_magic is unhappy with the new external_results format

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#598]
**What command was run:**

ipmag.upload_magic(dir_path='Kaulial Kas',concat=True)

**What happened:**
A lot of angry warnings:  
-W- these rows have problems:
 row: 53, name: 1408.2
row: 56, name: 1461.9
row: 57, name: 1461.9
row: 58, name: 1461.9
row: 60, name: 1501.8  ...
(for full error output see error file)

**What I expected to happen:**

it to create an upload file without problems. 

**Data file(s):**

[Kaulial Kas.zip](https://github.com/PmagPy/PmagPy/files/4051408/Kaulial.Kas.zip)

**Screenshot(s):**

**PmagPy version:**
"pmagpy-4.2.31"

**Comment by moonshoes87** [comment]
The reason for these errors is because the data model requires that the external_results column should contain a value from the controlled vocabulary External Results Type:

<img width="1000" alt="Screen Shot 2020-01-24 at 1 42 20 PM" src="https://user-images.githubusercontent.com/1836578/73106082-6866fc00-3eaf-11ea-8101-32d644494220.png">

Perhaps this validation should be changed, or other values should be added to the controlled vocabulary list?

**Comment by moonshoes87** [comment]
Ah, sorry, I got it wrong -- the validation is messed up because it is expecting the whole string to be a controlled vocabulary, instead of just the first part.  I will fix this.

**Comment by rminnett** [comment]
I was working on this earlier in the week, but got sidetracked before I
finished testing it. I can commit my changes if you want to test it for me?

**Comment by moonshoes87** [comment]
@rminnett, you mean to the MagIC validation, or in the PmagPy validation?

**Comment by rminnett** [comment]
In PmagPy - I can issue a pull request so you can see if they help or if
you prefer to implement the fix differently.

Rupert

**Comment by moonshoes87** [comment]
pull request would be great, thanks Rupert!

**Comment by moonshoes87** [comment]
I am closing this issue in favor of https://github.com/PmagPy/PmagPy/pull/601
