### ISSUE TITLE
floats and integers within MagicDataFrame are all in there as strings

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#65]
I am just starting to use the MagicDataFrame object in some code and am bumping into the problem that the values that should be floats and integers within the DataFrame are all in there as strings.

I can change them myself by doing something like:
```
Halls1974_sites['dir_dec'] = pd.to_numeric(Halls1974_sites['dir_dec'])
```
but given that most of the columns are always floats or always integers it seems like having the correct dtype should be a feature of the MagicDataFrame object.

Thoughts, @moonshoes87?

**Comment by moonshoes87** [comment]
We can get the information about dtype for a column from the data model.  

These are the possible types:

String, Dictionary, Text, List, Number, Flag, Timestamp, Integer, Matrix


Here’s some code for what that could look like for some of the types:
H


One weird thing is that dtype won’t show up as ‘str’ or ‘int’ if there are np.nan or None values in that column, but that probably isn’t important.  We could use “” as the null value in String columns and 0 as the null value in integer columns, but that is probably too weird and inconsistent.  I don’t think the column’s dtype is really crucial for the most part, since we will usually exclude null values or use a pandas accessor like .str which itself ignores null values of whatever type.

The downside of putting this functionality into the __init__ is that it would require downloading the data model immediately, which isn’t currently done by default since it isn’t required for everything and takes a little time.  I think I will just add a method for correctly casting all dtypes in a DataFrame, and we can decide later whether or not we want it to be called during __init__.  We would need to call this function either before doing calculations OR whenever reading in from a file or from a wxPython grid.  Also, we should decide how we want to treat the other dtypes like Dictionary, Matrix, and List.  

I will add in that method today.  Thoughts on the other issues?

**Comment by Swanson-Hysell** [comment]
Overall this plan sounds good. One comment is that I think it is potentially dangerous to have 0 be a null value in integer columns given that unlike "" it actually has a meaning. 

I guess another question is that in my experience, pandas/python is good at intuiting what the dtype is. If this was happening, there wouldn't have to be importing of the data model etc. Do you understand why floats in the tables are coming in as strings?

**Comment by moonshoes87** [comment]
Yes, I agree about point number 1.  I’ll take that out — I was just experimenting to see how I could get the dtype to come out as integer.  0 is not a good null value.  

As to point number 2, it looks like the problem is pmag.magic_read, which reads in everything as a string.  I should probably just use pd.read_table instead — that would likely be more efficient anyway.  It might still be useful to have a casting method, but this might solve the entire problem.

**Comment by ltauxe** [comment]
yes that would be great.  much more straigtht forward.  
lisa

**Comment by moonshoes87** [comment]
I’m about to push the fix.  We’re now using pd.read_table which figures out the dtypes pretty well.  Everything seems to be working, but it is possible that there could be some lingering issues — i.e., places in the existing code that expect a string that will no longer find one.  I.e., val == “1” vs. val == 1.  Hopefully this shouldn’t be too big of an issue, but we should keep an eye out for problems of this nature.

**Comment by Swanson-Hysell** [comment]
Great. That fix is doing the trick for the issue I was having. Will certainly keep an eye out for unintended consequences.

**Comment by moonshoes87** [comment]
Great! I think likely problems were just in the 3.0 compatible plotting programs, and I’m hopeful that I caught all of them.  But we’ll see :)
