### ISSUE TITLE
cit_magic3 fails with Canopy Python

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#68]
The "builtins" module isn't part of the Canopy package, although __future__ is installed.  (not sure if this is relevant.... [builtins issue](https://github.com/datamade/dedupe/issues/374))

Because of this, cit_magic3 fails with an import error.  Also, pdb is referenced in the code but never imported.  I fixed these issues locally so that I can run cit_magic3, but I didn't want to muck around with it without understanding why it was set up that way!

**Comment by ltauxe** [comment]
muck away!

**Comment by Swanson-Hysell** [comment]
Do go ahead and muck away. That the builtins import statement can simply be removed or commented out for the moment (it is some Python3 code and snuck into the main repo).

Some context for why this line of code ended up in there:
We have been exploring how tricky it will be to get all of PmagPy running in Python 3 rather than Python 2.7. It turns out that it isn't very tricky at all. At present, @Caoimhinmg has a fork of PmagPy that runs in Python 3 including the GUIs (using the wxPython library Phoenix: https://wxpython.org/Phoenix/docs/html/index.html). This Python2 to Python3 transition needs to be made at some point before long given that the sun sets on Python 2.7 in 2020. @moonshoes87 it would be great if at some point you are able to play around with the https://github.com/Caoimhinmg/PmagPy running it using both a Python2 and Python3 distro (it should work in both, although @Caoimhinmg can provide some caveats). It has been a pleasant surprise that the wxPython code is effectively the same and that the 2to3 translator in the standard Python library (https://docs.python.org/2/library/2to3.html) did the trick on the rest of the code.

**Comment by Swanson-Hysell** [comment]
Is this still an issue @moonshoes87?

**Comment by moonshoes87** [comment]
sorry for the delay!  I was on a hut-to-hut mountain bike trip.  

This issue is resolved for me.  I'm hoping to have a look at the Python 2 --> 3 stuff soon.
