### ISSUE TITLE
Add Change in Color  in Plots when Measurement Selected

### ISSUE THREAD

**Issue by sslotznick** [PmagPy/PmagPy#71]
It would be a great addition to the Pmag_GUI program if whenever a measurement was selected on the measurement list the color of it would change in the Zijderveld/Orthographic diagram and in the Equal Area/Stereonet diagram.  This would allow us to know which measurement we are looking at quickly even if the labels are written on the other portion of the vector (DEC v. INC).

Attached is a GIF showing how this works in the Craig Jones PaleoMag software
![craigjonespointhighlight_med](https://cloud.githubusercontent.com/assets/22084198/18598955/a01ac7be-7c0a-11e6-95f2-ad6fbf62d761.gif)

**Comment by Caoimhinmg** [comment]
I assume you mean this for the Demag GUI? I like the idea, however, it will be exceedingly slow if I don't break up some GUI functions to make it more manageable, but I've been meaning to do that for a long time to help with optimization. I'll let you know how it progresses.

**Comment by Swanson-Hysell** [comment]
Yes. Demag_gui is what is meant. 

One thought is that when the fits are drawn, both the fits and the ends points that are chosen render quite quickly. If similar machinary was used for highlighting the points (effectively drawing another symbol/color over the rendered data points) I think it would be pretty quick.

**Comment by Caoimhinmg** [comment]
Okay, I did this by adjusting the method of plotting the figures, partly to break the draw_figure method into parts so the GUI doesn't have to redraw all plots as it has always done when it does redraw anything. Also because if I drew over the original plot I would have to save the over drawn points so they can be removed or create a new axis to plot on, which is almost the same thing. It might be a bit faster if I do rewrite it that way though a bit more complicated mechanically use a bit more code and memory. I think it's plenty fast in this form but let me know what you think of it as is. Also I think it might be good to show the selected measurement on the M/M0 plot as well so I was going to add that before closing this issue. Any suggestions on the colors chosen or about the suggestion of adding this to the M/M0 plot?
