### ISSUE TITLE
error in demag gui tests

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#75]
I'm getting some errors when I run the demag gui tests.
These three tests produce the same error:  test_read_write_redo, test_read_write_pmag_tables, test_ie_buttons.
`AttributeError: 'Demag_GUI' object has no attribute 'get_ie_open'`

I had a merge conflict with the test_demag_gui.py, but I thought I fixed that...  Could one of you have a look at this, @Swanson-Hysell or @Caoimhinmg?

**Comment by Caoimhinmg** [comment]
Sorry for the delayed response @moonshoes87 I've just pushed a fix for this. It's a non essential part of the GUI, just calling for a boolean that tells if the interpretation editor is open. I changed the test calls for ie_open from a encapsulation function get_ie_open to just ie_open because the function was not really being used internally in the GUI so a little pointless.

**Comment by moonshoes87** [comment]
Great!  I wasn’t sure if the failing test was actually meaningful, so I thought I’d check in because of making a new release :)  Thanks!
