### ISSUE TITLE
Demag GUI selection of temperature bounds

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#76]
When I open Demag GUI, I can initially only select bounds by clicking on the steps in the lower left corner.  After I've clicked on a step, the drop-down Bounds in the upper left appear and I can edit using those.  It seems like the Bounds drop-down should work from the start, or we should remove that way of interacting with the parameters.  

I can dig into this, but it will probably be easier for one of you who have been working on Demag GUI more...

**Comment by Swanson-Hysell** [comment]
Before the dropdown boxes work, one has to click the **add fit** button or create a fit by clicking on the steps. Once add fit is clicked then the fit can be modified using the drop-down windows. I think it makes sense to keep the functionality this way.

**Comment by ltauxe** [comment]
Just so you all know, I just invited my grad student Hanna Asefaw to be a contributor to PmagPy.  Welcome to the party, Hanna. 
lisa

**Comment by Swanson-Hysell** [comment]
Excellent! Welcome Hanna.

**Comment by Swanson-Hysell** [comment]
Speaking of contributors, I just noticed that @ltauxe your status as a member of the PmagPy organization is set to private which I assume is not intentional:

<img width="241" alt="screen shot 2016-10-06 at 11 18 01 pm" src="https://cloud.githubusercontent.com/assets/4332322/19180531/51c35fb0-8c1b-11e6-862c-9d2ba9e92431.png">

You can click on yourself in the People list on the PmagPy organization main page and then click on "Private" to change it to "Public":

<img width="1005" alt="screen shot 2016-10-06 at 11 20 07 pm" src="https://cloud.githubusercontent.com/assets/4332322/19180547/7c9636c2-8c1b-11e6-991e-625f16510029.png">

**Comment by ltauxe** [comment]
Oh thanks

**Comment by ltauxe** [comment]
After a too long absence, I’m about to start testing the 3.0 version of Pmag GUI on a new dataset. but i have some questions:  
1) is this pmag_gui3   separate from Pmag GUI 2.5?  
2) Can I replace thellier_gui with thellier_gui3.0?  
3)  is demag_gui now compatible with both 2.5 and 3.0 like thellier_gui3.0?   




lisa

**Comment by moonshoes87** [comment]
1.  Pmag GUI 3 is still separate (pmag_gui3.py) but after a little testing could probably be renamed.  It must be run with the -DM 3 switch, though.  I didn’t want to rely on detecting a 2.5 vs 3.0 file, because Pmag GUI includes a conversion tool and I wanted to be able to force the use of 3.0 even with 2.5 files present.  There is a new pip release so you can use that or the regular git version to check it out.

2 & 3.  I think so!

**Comment by moonshoes87** [comment]
Thanks, @Swanson-Hysell.  Sounds good!
