### ISSUE TITLE
demag_gui.py 

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#83]
@Caoimhinmg @Swanson-Hysell 

this is now working pretty much - but there is problem calculating best fit lines that doesn't occur in zeq_magic.py.    I get this error:  
![screen shot 2016-10-20 at 8 59 04 am](https://cloud.githubusercontent.com/assets/174861/19568024/c958038a-96a4-11e6-8189-1909e3ec90fc.png)
with this  pmag_specimens.txt file and 
[pmag_specimens.txt](https://github.com/PmagPy/PmagPy/files/542202/pmag_specimens.txt)
 
and this magic_measruements table.  
[magic_measurements.txt](https://github.com/PmagPy/PmagPy/files/542199/magic_measurements.txt)

**Comment by Swanson-Hysell** [comment]
The problem here is stemming from a misordering of the measurement steps that is occuring. There are some samples where the steps are being ordered fine and the fits are therefore able to be made such as 355-U1456A-1H-1_W_62. It looks like such samples have measurement_number numbers that proceed in order in the magic_measurements file.

<img width="258" alt="screen shot 2016-10-20 at 10 22 51 am" src="https://cloud.githubusercontent.com/assets/4332322/19570641/b9df766c-96af-11e6-8dbd-a75a9999856a.png">

The samples where the steps aren't appearing in order in demag_gui are the ones causing the issue given that the lower and upper bounds provided appear out of order compared to the data. For example, in 355-U1456A-27F-1_W_35 (shown below) the NRM measurement has the highest measurement number in the magic_measurements.txt file (27) and is being shown last. The 0.01 and 0.1 T steps both have a measurement number of 1.

<img width="250" alt="screen shot 2016-10-20 at 10 20 02 am" src="https://cloud.githubusercontent.com/assets/4332322/19571087/9337eb6e-96b1-11e6-8168-6de5158f953f.png">

Here are what the data look like in the measurements for that specimen:

<img width="392" alt="screen shot 2016-10-20 at 10 39 41 am" src="https://cloud.githubusercontent.com/assets/4332322/19571082/8d8c4c96-96b1-11e6-8517-6b795aa18f6e.png">


 @Caoimhinmg, is the measurement number what is being used to set the order measurements appear in demag_gui? And is this thus the root of the problem?

**Comment by Caoimhinmg** [comment]
Thanks for the error report @ltauxe  this is a good one.

So I've been having trouble with data sorting during read in and I'm not totally sure the best method to resolve this so far. So here's what I have tried:

* Leaving measurement data alone and assuming it is presorted before read in, which in this case is more or less correct and would fix the above problem, but for some data sets if this isn't true the whole thing breaks down, also then if NRM isn't first normalization errors could occur. This is what zeq_magic does to the best of my knowledge.
* Sorting by measurement number which seems the most logical it's supposed to be an index telling which measurements came first chronologically, but for data sets like this the measurement number is basically nonsensical for a few samples like 355-U1456A-10H-1_W_60 in this data set which has indices ['1', '1', '2', '2', '3', '3', '4', '7', '10', '13', '16', '19', '22'] for it's measurement data.

So I'm not really sure if there is a catch all fix to this problem, for now I am just going to stop sorting data so that @ltauxe problem is resolved and because it'll speed everything up considerably. Is there any standard other people are using @moonshoes87 or @rminnett for sorting measurement data? or is the presorting assumption good for all cases?

**Comment by Swanson-Hysell** [comment]
It looks like @Caoimhinmg and I commented at exactly the same time. So @Caoimhinmg, does the code currently sort by measurement number? I agree that approach typically makes sense, but clearly it breaks down for the indices in these data.

**Comment by Caoimhinmg** [comment]
Well, @Swanson-Hysell, until the push I just made just after our comments it was sorting by specimen then by measurement number if it was there. If not it would try to find an NRM for each specimen and make the first NRM first so the normalization wouldn't be wrong. All done using the internal python sorting algorithm which I think is time sort.

So after  the last commit it now just assumes everything is presorted as that seems to be the convention used by zeq_magic and was how the GUI used to work. I only added the sorting as an additional check when I revamped the data read in a couple weeks ago because I didn't want bad normalizations. Though due to the problems I figured I'd just remove it.

**Comment by Swanson-Hysell** [comment]
That sounds good. I think taking the approach of bring in the data in the order it is within the magic_measurements file is an approach that will be less prone to messing things up. I just opened that data using the version you updated and it looks to be going a good job with it so I will close this issue for now.

**Comment by ltauxe** [comment]
ahh.  that is because the data are a combination of imports from three different instruments and two different labs.  I didn’t re-number the measurement numbers (which I will do of course before uploading.)  I just wanted to look at the data quickly.  
lisa
