### ISSUE TITLE
Windows Standalone Support

### ISSUE THREAD

**Issue by Caoimhinmg** [PmagPy/PmagPy#86]
So @Swanson-Hysell pointed out to me that the Windows Standalone is lagging far behind the rest of the project on releases. I've understood that it's been hard for @moonshoes87 to maintain it because as everyone knows py2exe can be a pain. I thought I'd look into compiling on my computer a standalone version of Pmag GUI using Pyinstaller which doesn't allow cross compiling, but as I have a windows distribution on half my hard drive this isn't an issue. Now 2 things came out of this:
- First occasionally Pmag GUI needs to know where some data files are so I couldn't just make a single binary I had to bundle those text files along with it and rewrite a little code to make sure it could always find it. Thanks to the good developing practices used for this import though it was relatively easy.
- Second Pyinstaller is not fast. It doesn't compile the python down to machine code in any way. As far as I can tell it just bundles a binary python interpreter in with binaries of the python files used and then on execution kind of on the run unpacks them and parses them through the bundled interpreter. It takes near a full 40 seconds to launch on my laptop.

So I guess the point of this issue is I would like to help continue support of a windows and maybe a linux binary as it seems a good way to help newcomers to the project and people who just want the program to run in their lab. Though this is a less than ideal binary as it has to be run next to the data models file 
I've included in the attached google drive link to an archive. Can those with the ability to run windows binaries check this out, and if it seems to be working @moonshoes87 could we work on making this binary a new release for the Windows standalone so that it's more up to date with the current state of the project? Also if anyone has any suggestions for optimizing this binary I'd be willing to try any ideas.

https://drive.google.com/file/d/0ByqHHbKOuiclOXc2QzVkYXJ2a2s/view?usp=sharing

**Comment by njarboe** [comment]
Hello all,

I have not been very active with PmagPy recently but would like to get more
involved as we roll out the 3.0 data model and get ready for the MagIC
workshop. Is there any reason to test on Windows 7 or should we just work
with the latest Windows 10? Please excuse me if you have already decided to
work with only the latest Windows 10.

Thaks,
Nick J.

**Comment by Caoimhinmg** [comment]
@njarboe I agree a Windows 10 binary would be the best release, especially if it ends up backwards compatible with the older Windows distros which it should be. However, I don't have Windows 10 to compile on. I've been avoiding the upgrade due to Windows habit to ignore your partition table and erase everything but itself. If someone else who has Windows 10 wants to take a hack at compiling it using pyinstaller I can hand off the script I'm using, or we can go back to trying py2exe and cross compiling which is usually a significantly more challenging prospect. It also might be worth checking if the current binary runs on Windows 10 as is I'm not sure how large an architecture change there is between the two distributions. One way or another though we should upgrade this standalone it's far out of date and could be a roadblock for any windows users looking to join the project.

**Comment by njarboe** [comment]
@Caoimhinmg What Windows are you running? I have access to Windows 10 and Windows 7 via Parallels virtual machines on my Mac laptop. These are very slow, however, and painful to use. Hopefully I can upgrade to a faster machine shortly. @moonshoes87 I know making the Windows standalones are a pain (What Windows do you use?), but it would be great if you could put them together soon for people who might come to the MagIC workshop to look at. How long does it take (If I remember right there is very high variance on the time to build and debug)? Maybe we could get one now, one a week or so before AGU (Dec 12-16), and one week before the workshop (Jan 24-27)? Would that suck up too much time? It is hard to see creating them less often and having them useful to people when so many improvements are being made at the moment.

**Comment by moonshoes87** [comment]
I actually have a (very crappy) laptop with Windows 10.  

I had previously spent a decent amount of time investigating Pyinstaller but ran into some fundamental compatibility problems between it and Canopy Python -- trying to handle the imports send it into an infinite recursion loop, because of how Canopy is set up.  Anaconda with Pyinstaller seems to be working better, though, which is great!  It's a relief after how much time I have spent with py2exe and not getting reliable success.

I tried downloading the binary and although it started very slowly, it did seem to work.  One note is that it is probably useful to change this line:

    app = wx.App(redirect=False)
    # to instead:
    app = wx.App(redirect=True)

That allows users to see the command line output in a wxPython-generated window.

It would be good to try running it on a completely "clean" Windows computer -- i.e., someone who hasn't installed Python, Microsoft Visual C++ Redistributable Package, or anything like that...

**Comment by moonshoes87** [comment]
@njarboe, I don't even have a reliable way of creating a Windows executable.  What kept happening was that I would compile a binary that worked great on my Windows machine, but failed on Rupert's test.  Because of that it was pretty much impossible for me to debug. 

I think that @Caoimhinmg's solution with Pyinstaller might work, though.  I'd rather try to move forward with getting Anaconda + Pyinstaller working than to go back to my old Canopy + Py2exe method, which proved really unreliable.  @Caoimhinmg and I are meeting tomorrow, so maybe we can discuss more how to go forward with that.

**Comment by njarboe** [comment]
@moonshoes87 I have a clean version of Windows 10. Nothing else installed yet. Are the cookbook/pmagpy instructions up to date for how we want people to set up? I can try a fresh install in the next couple of days and let you know the hang-ups. Looks like we will be changing the system soon. Are you guys Skyping? Would you like me to join you? I would like to get a handle on the install as hopefully people will be trying it out before the workshop.

**Comment by moonshoes87** [comment]
That's great, first priority I would say is try out Kevin's new Pmag GUI distribution:  https://drive.google.com/file/d/0ByqHHbKOuiclOXc2QzVkYXJ2a2s/view?usp=sharing.

If that works, we'll have some good evidence for the viability of Anaconda + Pyinstaller.

Second priority, you can try installing in the standard way that we are now recommending in the Cookbook: install Canopy, pip install pmagpy, and pip install pmagpy-cli.  

It would be great to thoroughly test out Kevin's distribution first, though, because one of the issues I have had with Windows is that the executables generated sometimes depend on other pieces of background code being installed with Python, etc.  Thanks for testing this out!

@Caoimhinmg  and I are meeting tomorrow in some virtual format at 2 p.m. (shall we say Skype?  or  google?), and you're welcome to join.

**Comment by Caoimhinmg** [comment]
@njarboe I dual boot a Windows 7 64 bit and a Ubuntu based Linux Mint 17.3 64 bit on both my laptops and the Windows 7 64 bit is where the above binary comes from which I have tested on my 2 computers. @moonshoes87 I'd suggest google hangout as we already have each others emails and it would be great to have @njarboe there too at least to hammer out this windows standalone issue.

**Comment by njarboe** [comment]
I'll try running Kevin's distribution on my not clean Windows 7 and clean Windows 10. Hopefully before tomorrow's meeting. I have a gmail account njarboe@gmail.com. I have not used google hangout in years. If I am on my gmail will I just see an invite to the meeting?

**Comment by Caoimhinmg** [comment]
As long as hangouts is enabled you should get a pop-up when one of us calls you if you have gmail open. Hangouts is enabled by default on normal gmail accounts I only mention the enabled thing because for some reason organization tied gmails can turn it off or mess with who can call who.

**Comment by njarboe** [comment]
Great. Catch you tomorrow.

**Comment by ltauxe** [comment]
my google email is ltauxe88@gmail.com.   i can try to ‘hangout’ sometime.  i’m there now…
lisa

**Comment by Caoimhinmg** [comment]
Now that the windows binary is about as up to date as the others I figured I'd close this issue to keep the issue panel clean with current projects and bugs only.
