### ISSUE TITLE
Improving Support for Plane Fits in PmagPy Demag GUI

### ISSUE THREAD

**Issue by sslotznick** [PmagPy/PmagPy#87]
It would be great if we were able to view/export the location of a plane's best fit (in geographic and tilt-corrected coordinates) that are used in the calculation of a given Fischer mean.  Note that this will change with each Fischer fit.  This could be done through extra columns in the magic measurements file or somehow with the Fischer means. Additionally if we could plot a plane’s “best fit” in Demag GUI on the site/location mean stereonet that would be great for visualization.

It would be also nice to clearly note in the Cookbook or even in the Demag Gui Interface, something about the relative weighting of lines and planes for the Fischer mean calculations.

**Comment by Swanson-Hysell** [comment]
I need to dig into the code a bit more to figure out where this can be exposed. @ltauxe, where is the combining lines and planes functionality living within pmag.py? What Sarah is looking for is being able to visualize and export the results of the iterative search (i.e. the set of N directions in your parlance from the Essentials text reproduced below). Is this something you have implemented in the code before?

## Combining lines and planes (text from https://earthref.org/MagIC/books/Tauxe/Essentials/WebBook3ap3.html#x22-240000C.2.2)

- Calculate M directed lines (two in our case) and N great circles (one in our case) using principal component analysis (see Chapter 9) or Fisher statistics.
- Assume that the primary direction of magnetization for the samples with great circles lies somewhere along the great circle path (i.e., within the plane).
- Assume that the set of M directed lines and N unknown directions are drawn from a Fisher distribution.
- Iteratively search along the great circle paths for directions that maximize the resultant vector R for the M + N directions.
- Having found the set of N directions that lie along their respective great circles, estimate the mean direction using Equation 11.7 and κ as:
![webbook3514x](https://cloud.githubusercontent.com/assets/4332322/19630076/e35c88f6-9937-11e6-85f6-c0743b7ab991.png)
     
The cone of 95% confidence about the mean is given by:
![webbook3515x](https://cloud.githubusercontent.com/assets/4332322/19630086/087368da-9938-11e6-9820-7054fbeb1a1c.png)
where N′ = M + N∕2 and p = .02

**Comment by ltauxe** [comment]
There is a funcioon dolnp (and also dolnp3.0) in pmag.py   
lisa

**Comment by Caoimhinmg** [comment]
Well as this thread has been dead for a bit I thought I'd give it a bit of a bump. I went ahead and dug into the functions mentioned by @ltauxe which I've used before in Demag_GUI and the iterative section you talk about @Swanson-Hysell is on line 3344 (if I'm reading this right) for the old data model dolnp (which is all that matters as dolnp3 just translates 3.0->2.5 then calls dolnp). @sslotznick would it be possible to get a bit more clarification on the kind of visualization you're looking for in Demag GUI if I were to encapsulate this iterative section in a function I could call it both in dolnp and by Demag GUI then export the data to a dialog plot or make it a toggle menu choice for the main GUI's high level means plot. I'm not sure I completely understand how you want the data visualized on that plot right now though or exactly what data you want there, do you just want to see each vector it tries (XX in the code I think if anyone is looking there) or just the best fit?

**Comment by sslotznick** [comment]
On the location/site mean plot I would like to just see the best fit vector when the Fischer mean is plotted...when using planes in fischer mean calculations you are actually using this best fit so it should be shown on the stereonet plot along with the line fits.  Personally, I don't think the planes need to be plotted in this means stereonet if the best fit is, but others might disagree.  So on the toggle menu for plane display full, partial, or poles of planes you could add best fit and/or you could offer in the means toggle menu a separate fischer and fischer with best fit on plane (although the fischer means should be the same).  Of course the best fit depends on the other fischer lines and planes will change if a fit is marked bad in the interpretation editor...therefore, it would need to update and on the sample equal area would constantly change as more fits are added.  Therefore, I think only plotting the best fit vector on the high level means plot makes the most sense.

**Comment by Caoimhinmg** [comment]
Okay, I get it. It's going to take a bit more thought than I expected...I'm going to basically do a fisher mean of the data on display exporting at each stage the best fit to each of the planes and then plot that in place of the planes currently displayed on the high level mean plot. Think I'll stick the option in the drop down menu for the plane fit display as suggested and it will change the planes on the high levels plot to best fit vectors leaving the planes on the specimen equal area plot. This does poise a few problems to optimization schemes I've put in place for the high level plot but I can put in a special case it'll likely be slower than the other display options if just marginally. This implementation does poise one final problem I would like your input on @sslotznick . The case of display all interpretations. Where all interpretations for a sample/site/location/study is shown you get groups of different components to which a fisher mean can be applied separately or collectively. So as I figure it, it would be better to display the best fit vector of each plane fit according to a mean with respect to the other interpretations in that component (identified by a shared name) rather than to a mean of every component and their interpretations. Does this sound right?

**Comment by Swanson-Hysell** [comment]
I think that it is helpful as a visualization to see the planes. That way one can visualize how well they are intersecting with one another. So it might make sense to have a planes+best_fit_on_plane display option. 

@Caoimhinmg, note that the Fisher mean is already taking the best fits on the planes into account. The issue is that the best fits are not being displayed. (It also looks like they aren't being exported? Which is functionality that is important if one is interpreting plane fits)

**Comment by ltauxe** [comment]
I agree.  I had that in lnp_magic.py and i use it a lot.  
lisa

**Comment by Caoimhinmg** [comment]
@Swanson-Hysell I can add both a best fit and a planes+best fit option to the drop down menu no problem, and I get that the best fits are already being calculated and factored in it's just that with the code set up as is I have no way of getting to them as they're all local calculations and variables. I do still need to know which best fit to save when doing means with respect to say just the component or all interpretations particularly because especially during export this question becomes imperative as it will result in two separate answers. As to the details of the export, it does seem like the dir_dec and dir_inc exported are the pole coordinates not the best fit. I could replace those entries with the best fit dec and inc and mag, but if you want both preserved on export I'll have to get a new set of variables added to the data model. Which of these sounds like the right design? I'd guess replace dir_dec, _inc and mag with the best fit as that is what matters in the means and take best fit with respect just to the component's data. I'd just like to check the exact design before I dig in too deep and end up with the wrong result and have to hack it.

**Comment by Caoimhinmg** [comment]
@sslotznick and @Swanson-Hysell this has been implemented, I forgot to tag the last few commits on it, but I've given it a few tests and in data model 3.0 only Demag GUI outputs dir_dec/inc as the normal vector of a plain fit and dir_bfv_dec/inc are the best fit vector. Reopen or open another issue if there is anything more you all want done on this topic. Also sorry for the long delay on implementing this.
