### ISSUE TITLE
Demag GUI display of interpretation type options

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#96]
This view in Demag GUI doesn't allow a user to actually read what option they are choosing:

![screen shot 2016-12-16 at 1 02 45 pm](https://cloud.githubusercontent.com/assets/1836578/21278479/40825434-c390-11e6-8fb9-fcede226d500.png)

In the past I've tried to solve a similar problem by having a mouseover event cause the full text to pop up:  https://wiki.wxpython.org/MouseOvers.  The problem is, this solution seemed to overload wxPython and make everything go slowly or crash.  That might have been a product of using an old version of wx on Windows at the time that I was originally attempting this, so the above solution may work.  

I can try to implement a UI solution when I've finished a few other things, or if someone else wants to take it that's fine too.

**Comment by Caoimhinmg** [comment]
I haven't looked at the code yet, but mouse over events sometimes cause rapid event fire which locks up the GUI event handler. In short term I'll just put abbreviations and edit the in context documentation (https://www.wxpython.org/docs/api/wx.ContextHelp-class.html) so that the curious can just check what they mean. I'm also pushing changes to the cookbook soon that expose to the user that there is in context help so it's not so obscure to find. Later I'll see if I can crack the mouse over idea so it's easier.
